import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        arabic: ["var(--dealix-font-arabic)", "Noto Kufi Arabic", "Noto Naskh Arabic", "Cairo", "IBM Plex Sans Arabic", "system-ui", "sans-serif"],
        display: ["var(--dealix-font-display)", "Cairo", "Noto Kufi Arabic", "Poppins", "system-ui", "sans-serif"],
        body: ["var(--dealix-font-body)", "Inter", "Noto Sans Arabic", "Tajawal", "system-ui", "sans-serif"],
        mono: ["var(--dealix-font-mono)", "JetBrains Mono", "IBM Plex Mono", "Fira Code", "monospace"],
        heading: ["var(--dealix-font-heading)", "Noto Kufi Arabic", "Cairo", "Inter", "system-ui", "sans-serif"],
      },
      colors: {
        brand: {
          navy: {
            50: "var(--dealix-navy-50)",
            100: "var(--dealix-navy-100)",
            200: "var(--dealix-navy-200)",
            300: "var(--dealix-navy-300)",
            400: "var(--dealix-navy-400)",
            500: "var(--dealix-navy-500)",
            600: "var(--dealix-navy-600)",
            700: "var(--dealix-navy-700)",
            800: "var(--dealix-navy-800)",
            900: "var(--dealix-navy-900)",
            950: "var(--dealix-navy-950)",
          },
          gold: {
            50: "var(--dealix-gold-50)",
            100: "var(--dealix-gold-100)",
            200: "var(--dealix-gold-200)",
            300: "var(--dealix-gold-300)",
            400: "var(--dealix-gold-400)",
            500: "var(--dealix-gold-500)",
            600: "var(--dealix-gold-600)",
            700: "var(--dealix-gold-700)",
            800: "var(--dealix-gold-800)",
            900: "var(--dealix-gold-900)",
            950: "var(--dealix-gold-950)",
          },
          emerald: {
            50: "var(--dealix-emerald-50)",
            100: "var(--dealix-emerald-100)",
            200: "var(--dealix-emerald-200)",
            300: "var(--dealix-emerald-300)",
            400: "var(--dealix-emerald-400)",
            500: "var(--dealix-emerald-500)",
            600: "var(--dealix-emerald-600)",
            700: "var(--dealix-emerald-700)",
            800: "var(--dealix-emerald-800)",
            900: "var(--dealix-emerald-900)",
            950: "var(--dealix-emerald-950)",
          },
          slate: {
            50: "var(--dealix-slate-50)",
            100: "var(--dealix-slate-100)",
            200: "var(--dealix-slate-200)",
            300: "var(--dealix-slate-300)",
            400: "var(--dealix-slate-400)",
            500: "var(--dealix-slate-500)",
            600: "var(--dealix-slate-600)",
            700: "var(--dealix-slate-700)",
            800: "var(--dealix-slate-800)",
            900: "var(--dealix-slate-900)",
            950: "var(--dealix-slate-950)",
          },
        },
        background: "var(--dealix-bg)",
        foreground: "var(--dealix-text)",
        card: {
          DEFAULT: "var(--dealix-surface)",
          foreground: "var(--dealix-text)",
        },
        popover: {
          DEFAULT: "var(--dealix-surface)",
          foreground: "var(--dealix-text)",
        },
        primary: {
          DEFAULT: "var(--dealix-primary)",
          foreground: "var(--dealix-text-inverse)",
        },
        secondary: {
          DEFAULT: "var(--dealix-accent)",
          foreground: "var(--dealix-navy-500)",
        },
        muted: {
          DEFAULT: "var(--dealix-bg-muted)",
          foreground: "var(--dealix-text-muted)",
        },
        accent: {
          DEFAULT: "var(--dealix-accent)",
          foreground: "var(--dealix-navy-500)",
        },
        destructive: {
          DEFAULT: "var(--dealix-error)",
          foreground: "var(--dealix-white)",
        },
        border: "var(--dealix-border)",
        input: "var(--dealix-border)",
        ring: "var(--dealix-accent)",
        sidebar: {
          DEFAULT: "var(--dealix-navy-500)",
          foreground: "var(--dealix-slate-100)",
          primary: "var(--dealix-accent)",
          "primary-foreground": "var(--dealix-white)",
          accent: "var(--dealix-navy-600)",
          "accent-foreground": "var(--dealix-slate-200)",
          border: "var(--dealix-navy-600)",
          ring: "var(--dealix-accent)",
        },
        chart: {
          "1": "var(--dealix-navy-500)",
          "2": "var(--dealix-gold-500)",
          "3": "var(--dealix-emerald-500)",
          "4": "#2563eb",
          "5": "#7c3aed",
        },
      },
      borderRadius: {
        none: "0",
        xs: "var(--dealix-radius-xs)",
        sm: "var(--dealix-radius-sm)",
        md: "var(--dealix-radius-md)",
        lg: "var(--dealix-radius-lg)",
        xl: "var(--dealix-radius-xl)",
        "2xl": "var(--dealix-radius-2xl)",
        full: "var(--dealix-radius-full)",
      },
      boxShadow: {
        none: "none",
        xs: "var(--dealix-shadow-xs)",
        sm: "var(--dealix-shadow-sm)",
        md: "var(--dealix-shadow-md)",
        lg: "var(--dealix-shadow-lg)",
        xl: "var(--dealix-shadow-xl)",
        "2xl": "var(--dealix-shadow-2xl)",
        "gold-sm": "var(--dealix-shadow-gold-sm)",
        "gold-md": "var(--dealix-shadow-gold-md)",
        "gold-lg": "var(--dealix-shadow-gold-lg)",
        "emerald-sm": "var(--dealix-shadow-emerald-sm)",
        "emerald-md": "var(--dealix-shadow-emerald-md)",
      },
      spacing: {
        "0.5": "2px",
        "1.5": "6px",
        "2.5": "10px",
        "3.5": "14px",
        "7": "28px",
        "9": "36px",
        "11": "44px",
        "14": "56px",
        "28": "112px",
        "32": "128px",
        "36": "144px",
        "40": "160px",
        "44": "176px",
        "48": "192px",
        "52": "208px",
        "56": "224px",
        "60": "240px",
        "64": "256px",
        "72": "288px",
        "80": "320px",
        "96": "384px",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-down": {
          from: { opacity: "0", transform: "translateY(-12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-left": {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "pulse-gold": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212,168,67,0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(212,168,67,0)" },
        },
        "pulse-emerald": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(5,150,105,0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(5,150,105,0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out forwards",
        "fade-in-up": "fade-in-up 0.5s ease-out forwards",
        "fade-in-down": "fade-in-down 0.4s ease-out forwards",
        "slide-up": "slide-up 0.5s cubic-bezier(0.2, 0.8, 0.2, 1) forwards",
        "slide-down": "slide-down 0.4s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
        "slide-in-left": "slide-in-left 0.4s ease-out forwards",
        "pulse-gold": "pulse-gold 2s infinite",
        "pulse-emerald": "pulse-emerald 2s infinite",
        shimmer: "shimmer 2s infinite linear",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.19, 1, 0.22, 1)",
        "in-expo": "cubic-bezier(0.7, 0, 0.84, 0)",
        "bounce": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
