#!/usr/bin/env python3
"""Dealix verify_*.py catalog builder.

Offline, dependency-free scan of `scripts/verify_*.py` that reads each
module's docstring (first line only) and renders a markdown table mapping
script -> one-line purpose. Scripts with no module docstring are listed as
"(no docstring — needs one)" rather than a guessed purpose.

Usage:
    python3 scripts/ops/build_verify_catalog.py            # print the table
    python3 scripts/ops/build_verify_catalog.py --check    # verify docs/ops/VERIFY_SCRIPTS_CATALOG.md is in sync

Exit code (--check only):
    0  catalog file matches the current scripts/verify_*.py set
    1  catalog file is missing or stale — regenerate it
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = ROOT / "scripts"
CATALOG_PATH = ROOT / "docs" / "ops" / "VERIFY_SCRIPTS_CATALOG.md"
NO_DOCSTRING = "(no docstring — needs one)"


def module_docstring_first_line(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return NO_DOCSTRING
    doc = ast.get_docstring(tree)
    if not doc:
        return NO_DOCSTRING
    first_line = doc.strip().splitlines()[0].strip()
    return first_line or NO_DOCSTRING


def collect_rows() -> list[tuple[str, str]]:
    scripts = sorted(SCRIPTS_DIR.glob("verify_*.py"), key=lambda p: p.name)
    return [(p.name, module_docstring_first_line(p)) for p in scripts]


def render(rows: list[tuple[str, str]]) -> str:
    lines = [
        "# Dealix verify_*.py Catalog",
        "",
        "Generated by `scripts/ops/build_verify_catalog.py`. Do not hand-edit —",
        "regenerate with:",
        "",
        "```bash",
        "python3 scripts/ops/build_verify_catalog.py > docs/ops/VERIFY_SCRIPTS_CATALOG.md",
        "```",
        "",
        f"Total scripts: {len(rows)}",
        "",
        "| Script | Purpose |",
        "|---|---|",
    ]
    lines.extend(f"| `scripts/{name}` | {purpose} |" for name, purpose in rows)
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify docs/ops/VERIFY_SCRIPTS_CATALOG.md matches the current scripts/verify_*.py set.",
    )
    args = parser.parse_args()

    rows = collect_rows()
    rendered = render(rows)

    if args.check:
        if not CATALOG_PATH.exists():
            print(f"MISSING: {CATALOG_PATH}")
            raise SystemExit(1)
        current = CATALOG_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"STALE: {CATALOG_PATH} does not match scripts/verify_*.py — regenerate it")
            raise SystemExit(1)
        print(f"OK: {CATALOG_PATH} in sync ({len(rows)} scripts)")
        raise SystemExit(0)

    sys.stdout = sys.stdout.reconfigure(encoding="utf-8", errors="strict")
    print(rendered, end="")


if __name__ == "__main__":
    main()
