#!/usr/bin/env python3
"""Verify Hermes Founder Intelligence fits 8192 ctx after distill.

Usage: python scripts/ops/verify_hermes_smart.py
Exit 0 if packet < 8192 tokens budget, 1 if overflow would recur.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

PACKET_SCRIPT = Path("/home/dealix/.hermes/scripts/dealix_founder_evidence_packet.sh")
REPO_PACKET = Path("scripts/ops/dealix_founder_evidence_packet.distilled.sh")
JOBS_JSON = Path("/home/dealix/.hermes/cron/jobs.json")
CTX = 8192
CHARS_PER_TOKEN = 4
OVERHEAD_TOKENS = 3500  # SOUL + skills + tools + router prefix estimate


def estimate_tokens(chars: int) -> int:
    return chars // CHARS_PER_TOKEN


def main() -> int:
    # Measure live packet
    try:
        out = subprocess.check_output([str(PACKET_SCRIPT)], text=True, timeout=10)
        live_chars = len(out)
        live_tokens = estimate_tokens(live_chars)
        print(f"LIVE_PACKET: {live_chars} chars ~{live_tokens} tokens")
    except Exception as e:
        print(f"FAIL: cannot run live packet: {e}", file=sys.stderr)
        return 1

    # Check repo packet exists
    if REPO_PACKET.exists():
        repo_chars = len(REPO_PACKET.read_text())
        print(f"REPO_PACKET_FILE: {repo_chars} chars (script itself, not output)")
    else:
        print("WARN: repo distilled packet script missing")

    # Estimate full prompt
    full_chars = live_chars + OVERHEAD_TOKENS * CHARS_PER_TOKEN
    # Actually overhead is tokens, convert back
    full_tokens = live_tokens + OVERHEAD_TOKENS
    # More accurate: measure via old accounting 13777 base + packet
    # Alternative estimate using measured base
    print(f"EST_FULL_TOKENS: ~{full_tokens} (packet {live_tokens} + overhead {OVERHEAD_TOKENS})")
    print(f"CTX_BUDGET: {CTX}")
    margin = CTX - full_tokens
    print(f"MARGIN: {margin} tokens")

    # Check jobs.json
    try:
        jobs = json.loads(JOBS_JSON.read_text())
        for job in jobs.get("jobs", []):
            if job.get("id") == "34d8d39ce69f":
                print(f"JOB no_agent={job.get('no_agent')} enabled={job.get('enabled')} model={job.get('model')}")
                if job.get("no_agent") is True:
                    print("NOTE: job is script-only (no_agent:true) — intelligence not regenerated by LLM. Flip to false after verifying margin >0.")
                else:
                    print("JOB is agent-enabled — will use LLM with packet")
                break
    except Exception as e:
        print(f"WARN: cannot read jobs.json: {e}")

    # Check last intelligence staleness
    intel = Path("/opt/dealix/company-os/founder-os/current/HERMES_FOUNDER_INTELLIGENCE.md")
    if intel.exists():
        import time
        age_hours = (time.time() - intel.stat().st_mtime) / 3600
        print(f"INTEL_AGE: {age_hours:.1f}h")
        if age_hours > 48:
            print("WARN: intelligence stale >48h (expected daily regen)")
    else:
        print("WARN: intelligence file missing")

    if full_tokens < CTX:
        print("VERDICT: PASS — packet fits 8192 ctx, safe to re-enable agent mode")
        return 0
    else:
        print(f"VERDICT: FAIL — overflow by {full_tokens - CTX} tokens, need further distillation or ctx increase to 16384", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
