"""Saudi / Arabic intelligence layer (deterministic helpers)."""

from __future__ import annotations

from auto_client_acquisition.saudi_layer.arabic_qa import (
    DIMENSION_NAMES_AR,
    DIMENSION_WEIGHTS,
    ArabicQADimensions,
    QAResult,
    arabic_qa_score,
    evaluate_qa,
    find_lowest_dimension,
)
from auto_client_acquisition.saudi_layer.arabic_style import (
    ARABIC_STYLE_RULES,
    FORMAL_CLOSINGS,
    FORMAL_GREETINGS,
    HONORIFICS_MAP,
    STYLE_RULES_AR,
    get_all_style_rule_names,
    get_style_rule,
    honorific_for_title,
)
from auto_client_acquisition.saudi_layer.bilingual_reports import (
    BILINGUAL_REPORT_KEYS,
    BilingualReport,
    BilingualSection,
    bilingual_report_complete,
    create_default_bilingual_report,
    fix_mixed_direction,
    generate_bilingual_pdf_html,
    is_rtl,
    wrap_arabic_css,
)
from auto_client_acquisition.saudi_layer.city_region_normalizer import (
    SAUDI_REGIONS,
    get_all_cities,
    get_all_region_names_ar,
    get_all_region_names_en,
    get_cities_in_region,
    get_city_coordinates,
    get_region_for_city,
    is_valid_city,
    normalize_city_name,
)
from auto_client_acquisition.saudi_layer.forbidden_claims import (
    FORBIDDEN_CLAIMS_ARABIC,
    forbidden_arabic_claim_detected,
    get_claim,
    get_claims_by_category,
    render_permitted_alternative,
    safe_alternative,
)
from auto_client_acquisition.saudi_layer.pdpl_aware_language import (
    PDPLAssessment,
    PDPLConsentRecord,
    PDPL_DATA_CATEGORIES,
    PDPL_DISCLOSURE_AR,
    PDPL_DISCLOSURE_EN,
    PDPL_HINT_AR,
    PDPL_SAFE_PHRASES_AR,
    PDPL_SAFE_PHRASES_EN,
    REQUIRED_DISCLOSURE_ELEMENTS_AR,
    REQUIRED_DISCLOSURE_ELEMENTS_EN,
    assess_pdpl_compliance,
    get_pdpl_disclosure,
    pdpl_required_disclosure_missing,
)
from auto_client_acquisition.saudi_layer.proof_safe_language import (
    ALLOWED_PHRASES_L3,
    ALLOWED_PHRASES_L4,
    ALLOWED_PHRASES_L5,
    ClaimAssessment,
    GENERIC_SAFE_PHRASES,
    LEVEL_LABELS,
    LEVEL_LABELS_EN,
    PROOF_SAFE_PHRASE_AR,
    ProofLevel,
    assess_claim_safety,
    get_proof_safe_footer,
    safe_phrase_for_level,
)
from auto_client_acquisition.saudi_layer.saudi_sector_taxonomy import (
    SAUDI_B2B_SECTORS,
    SAUDI_SECTORS,
    get_all_sectors,
    get_sector_by_code,
    get_sector_isic,
    get_sector_naics,
    get_sector_names_ar,
    get_sub_sectors,
    sector_known,
    search_sectors,
)
from auto_client_acquisition.saudi_layer.whatsapp_boundary import (
    WHATSAPP_ALLOWED_ACTIONS,
    WHATSAPP_POSTURE_AR,
    WHATSAPP_POSTURE_EN,
    WHATSAPP_RULES,
    WhatsAppBoundaryCheck,
    WhatsAppRelationshipType,
    check_whatsapp_boundary,
)

__all__ = [
    # Saudi sectors
    "SAUDI_B2B_SECTORS",
    "SAUDI_SECTORS",
    "get_all_sectors",
    "get_sector_by_code",
    "get_sector_isic",
    "get_sector_naics",
    "get_sector_names_ar",
    "get_sub_sectors",
    "sector_known",
    "search_sectors",
    # City/region
    "SAUDI_REGIONS",
    "get_all_cities",
    "get_all_region_names_ar",
    "get_all_region_names_en",
    "get_cities_in_region",
    "get_city_coordinates",
    "get_region_for_city",
    "is_valid_city",
    "normalize_city_name",
    # Arabic style
    "ARABIC_STYLE_RULES",
    "FORMAL_CLOSINGS",
    "FORMAL_GREETINGS",
    "HONORIFICS_MAP",
    "STYLE_RULES_AR",
    "get_all_style_rule_names",
    "get_style_rule",
    "honorific_for_title",
    # Forbidden claims
    "FORBIDDEN_CLAIMS_ARABIC",
    "forbidden_arabic_claim_detected",
    "get_claim",
    "get_claims_by_category",
    "render_permitted_alternative",
    "safe_alternative",
    # Arabic QA
    "ArabicQADimensions",
    "DIMENSION_NAMES_AR",
    "DIMENSION_WEIGHTS",
    "QAResult",
    "arabic_qa_score",
    "evaluate_qa",
    "find_lowest_dimension",
    # PDPL
    "PDPLAssessment",
    "PDPLConsentRecord",
    "PDPL_DATA_CATEGORIES",
    "PDPL_DISCLOSURE_AR",
    "PDPL_DISCLOSURE_EN",
    "PDPL_HINT_AR",
    "PDPL_SAFE_PHRASES_AR",
    "PDPL_SAFE_PHRASES_EN",
    "REQUIRED_DISCLOSURE_ELEMENTS_AR",
    "REQUIRED_DISCLOSURE_ELEMENTS_EN",
    "assess_pdpl_compliance",
    "get_pdpl_disclosure",
    "pdpl_required_disclosure_missing",
    # Proof-safe
    "ALLOWED_PHRASES_L3",
    "ALLOWED_PHRASES_L4",
    "ALLOWED_PHRASES_L5",
    "ClaimAssessment",
    "GENERIC_SAFE_PHRASES",
    "LEVEL_LABELS",
    "LEVEL_LABELS_EN",
    "PROOF_SAFE_PHRASE_AR",
    "ProofLevel",
    "assess_claim_safety",
    "get_proof_safe_footer",
    "safe_phrase_for_level",
    # WhatsApp
    "WHATSAPP_ALLOWED_ACTIONS",
    "WHATSAPP_POSTURE_AR",
    "WHATSAPP_POSTURE_EN",
    "WHATSAPP_RULES",
    "WhatsAppBoundaryCheck",
    "WhatsAppRelationshipType",
    "check_whatsapp_boundary",
    # Bilingual reports
    "BILINGUAL_REPORT_KEYS",
    "BilingualReport",
    "BilingualSection",
    "bilingual_report_complete",
    "create_default_bilingual_report",
    "fix_mixed_direction",
    "generate_bilingual_pdf_html",
    "is_rtl",
    "wrap_arabic_css",
]
