export type Capability = {
  id: string;
  nameAr: string;
  nameEn: string;
  summary: string;
  outcomes: string[];
};

export type SectorProfile = {
  key: string;
  slug: string;
  nameAr: string;
  nameEn: string;
  focus: string;
  problems: string[];
  capabilityIds: string[];
  examples: string[];
};

export const capabilityCatalog: Capability[] = [
  { id: "strategy", nameAr: "الاستراتيجية والتحول", nameEn: "Strategy & Transformation", summary: "تحويل أهداف النمو والتحول إلى operating model وأولويات وقرارات قابلة للتنفيذ والقياس.", outcomes: ["خارطة قرار وتنفيذ", "Value baseline", "Operating model واضح"] },
  { id: "agents", nameAr: "وكلاء AI وأتمتة الـWorkflows", nameEn: "AI Agents & Workflow Automation", summary: "تصميم workflows وagents محكومة بالصلاحيات والموافقات فوق الأدوات الحالية، بدون فرض استبدال شامل للـstack.", outcomes: ["خفض العمل اليدوي", "تقليل handoffs", "تنفيذ محكوم"] },
  { id: "revenue", nameAr: "الإيراد والعمليات التجارية", nameEn: "Revenue & Commercial Operations", summary: "ترتيب pipeline والمتابعات والعروض والـnext actions وربطها بالدليل بدل النشاط الشكلي.", outcomes: ["متابعة أوضح", "Quote velocity", "Commercial proof"] },
  { id: "customer", nameAr: "عمليات وخدمة العملاء", nameEn: "Customer Operations", summary: "تنظيم الاستقبال والتصنيف والمتابعة والتصعيد وخدمة العملاء عبر قنوات متعددة مع حدود موافقة واضحة.", outcomes: ["زمن استجابة أقل", "Ownership أوضح", "قابلية قياس الخدمة"] },
  { id: "knowledge", nameAr: "عقل الشركة والوثائق", nameEn: "Knowledge & Document Intelligence", summary: "تحويل الملفات والسياسات والمراسلات والمعرفة التشغيلية إلى سياق قابل للبحث والاستخدام في القرار والعمل.", outcomes: ["بحث أسرع", "تقليل فقد المعرفة", "قرارات بسياق موحد"] },
  { id: "data", nameAr: "البيانات وذكاء القرار", nameEn: "Data & Decision Intelligence", summary: "ربط مصادر البيانات، بناء مؤشرات تشغيلية، وتقديم decision intelligence مع فصل الإشارة عن الإثبات.", outcomes: ["رؤية تنفيذية", "استثناءات قابلة للتصرف", "قياس قبل/بعد"] },
  { id: "procurement", nameAr: "المشتريات والعطاءات", nameEn: "Procurement & Tender Intelligence", summary: "قراءة فرص الشراء والعطاءات والوثائق، استخراج المتطلبات، وتحضير readiness وdecision packs دون افتراض أهلية أو علاقة.", outcomes: ["فرز أسرع للفرص", "متطلبات أوضح", "قرار Bid / Partner / Hold"] },
  { id: "integration", nameAr: "التكاملات وMCP", nameEn: "Integration, MCP & Automation Fabric", summary: "ربط CRM وERP والبريد والملفات وواجهات API وMCP ضمن مسار مراقب وقابل للاختبار والرجوع.", outcomes: ["تقليل الجزر", "Reliability أعلى", "Traceability"] },
  { id: "trust", nameAr: "حوكمة وموثوقية AI", nameEn: "AI Governance & Reliability", summary: "صلاحيات، approvals، evaluation، receipts وproof gates تقلل أخطار agent/tool misuse وتمنع الادعاء غير المثبت.", outcomes: ["حدود صلاحية", "قابلية مراجعة", "اختبارات موثوقية"] },
  { id: "security", nameAr: "جاهزية الأمن السيبراني التشغيلية", nameEn: "Cybersecurity Operations Readiness", summary: "تشخيص فجوات التشغيل والأدلة والاستجابة والتكاملات الأمنية كجاهزية وتحسين تشغيلي، لا كشهادة امتثال.", outcomes: ["Evidence map", "Control workflow", "Incident readiness"] },
  { id: "finance", nameAr: "عمليات المالية وFatoora", nameEn: "Finance Operations & Fatoora Readiness", summary: "تحسين تدفقات الفوترة والتحصيل والاستثناءات والجاهزية التقنية للتكاملات المالية حسب سياق العميل.", outcomes: ["استثناءات أقل", "تحصيل أوضح", "Integration readiness"] },
  { id: "managed-ai", nameAr: "تشغيل AI مُدار", nameEn: "Managed AI Operations", summary: "تشغيل ومراقبة workflows وagents بعد إثبات الحاجة، مع cost routing وobservability وapproval boundaries.", outcomes: ["تشغيل مستمر", "تكلفة مضبوطة", "تحسين دوري"] },
  { id: "market", nameAr: "الوصول للسوق والشركاء", nameEn: "Saudi Market Access & Partner Intelligence", summary: "بحث السوق والقطاعات والشركاء وقنوات التوزيع والمشتريات وتحويلها إلى قرارات قابلة للتحقق دون خلط البحث بالعلاقة.", outcomes: ["Opportunity radar", "Partner hypotheses", "Go-to-market decisions"] },
  { id: "productization", nameAr: "Dealix OS وتحويل الحلول إلى منتجات", nameEn: "Dealix OS & Productization", summary: "تحويل الأنماط المتكررة المثبتة إلى Company Brain وOpportunity Graph وApproval وProof ثم منتجات قابلة للتوسع.", outcomes: ["IP قابل لإعادة الاستخدام", "Runtime موحد", "Product path"] },
];

export const sectorCatalog: SectorProfile[] = [
  { key: "government_b2g", slug: "government-b2g", nameAr: "الحكومة والقطاع العام", nameEn: "Government & B2G", focus: "القرارات، البيانات، المشتريات، إدارة البرامج والجاهزية التشغيلية.", problems: ["Document-heavy workflows", "Procurement complexity", "Decision latency"], capabilityIds: ["procurement", "knowledge", "data", "trust", "integration"], examples: ["تحضير readiness لفرصة شراء عامة", "تلخيص متطلبات ووثائق كبيرة", "ربط evidence بالقرار والتنفيذ"] },
  { key: "construction_epc", slug: "construction-epc", nameAr: "الإنشاءات والمقاولات وEPC", nameEn: "Construction & EPC", focus: "المشاريع، العطاءات، الوثائق، الموردون والاستثناءات التشغيلية.", problems: ["Project delay", "Tender/document load", "Supplier friction"], capabilityIds: ["procurement", "knowledge", "data", "agents", "integration"], examples: ["فرز RFQ/RFP", "استخراج مخاطر ووثائق المشروع", "توجيه الاستثناءات للمالك الصحيح"] },
  { key: "industrial_manufacturing", slug: "industrial-manufacturing", nameAr: "الصناعة والتصنيع", nameEn: "Industrial & Manufacturing", focus: "الجودة، الصيانة، سلسلة التوريد، المعرفة الفنية وقرارات المصنع.", problems: ["Quality exceptions", "Manual handoffs", "Knowledge loss"], capabilityIds: ["data", "agents", "knowledge", "integration", "managed-ai"], examples: ["تحليل استثناءات الجودة", "مساعد معرفة فنية", "لوحة قرار للمشاكل التشغيلية"] },
  { key: "logistics_supply_chain", slug: "logistics-supply-chain", nameAr: "اللوجستيات وسلاسل الإمداد", nameEn: "Logistics & Supply Chain", focus: "الشحن، التخطيط، الموردون، الاستثناءات وخدمة العملاء.", problems: ["Operational exception overload", "Supplier friction", "Reporting delay"], capabilityIds: ["data", "customer", "agents", "integration", "knowledge"], examples: ["تصنيف الاستثناءات", "متابعة SLA", "تجميع بيانات التشغيل للقرار"] },
  { key: "energy_utilities_oil_gas", slug: "energy-utilities-oil-gas", nameAr: "الطاقة والمرافق والنفط والغاز", nameEn: "Energy, Utilities & Oil/Gas", focus: "العمليات الحرجة، الوثائق الفنية، الموردون، المخاطر والموثوقية.", problems: ["Approval delay", "Document chaos", "Operational risk"], capabilityIds: ["knowledge", "trust", "data", "integration", "procurement"], examples: ["Knowledge operations", "Evidence workflows", "تحليل وثائق الموردين والمشاريع"] },
  { key: "mining_metals", slug: "mining-metals", nameAr: "التعدين والمعادن", nameEn: "Mining & Metals", focus: "المشاريع، الأصول، الموردون، التقارير والقرارات الميدانية.", problems: ["Project delay", "Reporting delay", "Supplier friction"], capabilityIds: ["data", "knowledge", "procurement", "agents", "integration"], examples: ["قرار مشاريع وموردين", "تقارير استثناءات", "استخراج متطلبات تشغيلية"] },
  { key: "real_estate_proptech", slug: "real-estate-proptech", nameAr: "العقار وPropTech", nameEn: "Real Estate & PropTech", focus: "المبيعات والتأجير وخدمة العملاء وإدارة الأصول والوثائق.", problems: ["Lead leakage", "Slow follow-up", "Document-heavy operations"], capabilityIds: ["revenue", "customer", "knowledge", "agents", "data"], examples: ["متابعة فرص العقار", "تصنيف استفسارات العملاء", "ذكاء وثائق العقود والأصول"] },
  { key: "healthcare", slug: "healthcare", nameAr: "الرعاية الصحية", nameEn: "Healthcare", focus: "تشغيل المعرفة والخدمة والبيانات والعمليات الإدارية مع حساسية عالية للبيانات.", problems: ["Support backlog", "Knowledge fragmentation", "Approval delay"], capabilityIds: ["knowledge", "customer", "trust", "data", "integration"], examples: ["بحث معرفي داخلي", "توجيه طلبات الخدمة", "حوكمة استخدام AI والبيانات"] },
  { key: "finance_fintech_insurance", slug: "finance-fintech-insurance", nameAr: "المالية وFinTech والتأمين", nameEn: "Finance, FinTech & Insurance", focus: "العمليات المنظمة، خدمة العملاء، الأدلة، المخاطر والتكاملات.", problems: ["Approval delay", "Compliance burden", "Customer operations load"], capabilityIds: ["trust", "data", "customer", "integration", "finance"], examples: ["Evidence-first workflow", "تصنيف العمليات والاستثناءات", "ربط قرار المخاطر بالـproof"] },
  { key: "retail_commerce_ecommerce", slug: "retail-commerce-ecommerce", nameAr: "التجزئة والتجارة الإلكترونية", nameEn: "Retail, Commerce & E-commerce", focus: "الإيراد، تجربة العميل، المخزون، الدعم والتسويق التشغيلي.", problems: ["Conversion leakage", "Support backlog", "Inventory exceptions"], capabilityIds: ["revenue", "customer", "data", "agents", "integration"], examples: ["متابعة conversion leakage", "توجيه دعم العملاء", "لوحات استثناءات مخزون ومبيعات"] },
  { key: "tourism_hospitality", slug: "tourism-hospitality", nameAr: "السياحة والضيافة", nameEn: "Tourism & Hospitality", focus: "الضيف، الحجوزات، التشغيل، التقييمات والفروع.", problems: ["Guest response delay", "Review overload", "Operational inconsistency"], capabilityIds: ["customer", "data", "agents", "knowledge", "revenue"], examples: ["تصنيف التقييمات والشكاوى", "متابعة الحجوزات والطلبات", "تقارير تشغيلية للفروع"] },
  { key: "professional_services", slug: "professional-services", nameAr: "الخدمات المهنية والاستشارية", nameEn: "Professional Services", focus: "المقترحات، التسليم، المعرفة، المشاريع والإيراد.", problems: ["Proposal delay", "Knowledge loss", "Follow-up failure"], capabilityIds: ["revenue", "knowledge", "agents", "data", "productization"], examples: ["Proposal intelligence", "Company Brain", "Delivery/proof workspace"] },
  { key: "technology_saas_si", slug: "technology-saas-si", nameAr: "التقنية وSaaS والتكامل", nameEn: "Technology, SaaS & Systems Integration", focus: "النمو، المنتج، الدعم، التكاملات، AI governance والموثوقية.", problems: ["Product/support fragmentation", "Integration failure", "AI governance risk"], capabilityIds: ["agents", "integration", "trust", "managed-ai", "productization"], examples: ["Agent reliability", "MCP/integration fabric", "Productized AI workflows"] },
  { key: "telecom_media_marketing", slug: "telecom-media-marketing", nameAr: "الاتصالات والإعلام والتسويق", nameEn: "Telecom, Media & Marketing", focus: "العملاء، المحتوى، العمليات، البيانات والإيراد عبر قنوات متعددة.", problems: ["Customer backlog", "Campaign fragmentation", "Reporting delay"], capabilityIds: ["customer", "revenue", "data", "agents", "knowledge"], examples: ["Customer routing", "Content operations", "Decision intelligence"] },
  { key: "education_training", slug: "education-training", nameAr: "التعليم والتدريب", nameEn: "Education & Training", focus: "المحتوى والمعرفة، رحلة المتعلم، التسجيل والتشغيل المؤسسي.", problems: ["Knowledge fragmentation", "Manual support", "Enrollment leakage"], capabilityIds: ["knowledge", "customer", "agents", "data", "revenue"], examples: ["مساعد معرفة للمحتوى", "تصنيف طلبات المتعلمين", "رصد funnel التسجيل"] },
  { key: "agriculture_food_water", slug: "agriculture-food-water", nameAr: "الزراعة والغذاء والمياه", nameEn: "Agriculture, Food & Water", focus: "سلسلة الإمداد، الجودة، العمليات، الموردون والتقارير.", problems: ["Quality failure", "Supplier friction", "Reporting delay"], capabilityIds: ["data", "procurement", "agents", "knowledge", "integration"], examples: ["استثناءات الجودة", "تقييم الموردين", "تقارير تشغيلية قابلة للتصرف"] },
  { key: "mobility_automotive", slug: "mobility-automotive", nameAr: "التنقل والسيارات", nameEn: "Mobility & Automotive", focus: "المبيعات وخدمة العملاء والأسطول والصيانة والاستثناءات.", problems: ["Lead leakage", "Service backlog", "Operational exceptions"], capabilityIds: ["revenue", "customer", "data", "agents", "integration"], examples: ["متابعة المبيعات", "توجيه طلبات الخدمة", "لوحة استثناءات الأسطول"] },
  { key: "export_import_rhq", slug: "export-import-rhq", nameAr: "التصدير والاستيراد والمقار الإقليمية", nameEn: "Export, Import & RHQ", focus: "دخول السوق، الشركاء، الوثائق، التجارة والتشغيل عبر مناطق متعددة.", problems: ["Market entry friction", "Partner uncertainty", "Document complexity"], capabilityIds: ["market", "knowledge", "procurement", "integration", "strategy"], examples: ["Market-entry decision pack", "Partner route research", "Workflow للوثائق والمتطلبات"] },
  { key: "creative_sports_gaming", slug: "creative-sports-gaming", nameAr: "القطاعات الإبداعية والرياضة والألعاب", nameEn: "Creative, Sports & Gaming", focus: "الجمهور، الرعايات، المحتوى، الفعاليات والعمليات الرقمية.", problems: ["Audience fragmentation", "Sponsorship workflow", "Content operations load"], capabilityIds: ["data", "revenue", "customer", "agents", "market"], examples: ["Audience intelligence", "Sponsorship pipeline support", "Content/approval workflow"] },
  { key: "associations_nonprofits", slug: "associations-nonprofits", nameAr: "الجمعيات والقطاع غير الربحي", nameEn: "Associations & Nonprofits", focus: "المستفيدون، المعرفة، البرامج، التقارير والشراكات.", problems: ["Reporting burden", "Stakeholder follow-up", "Knowledge loss"], capabilityIds: ["knowledge", "customer", "data", "market", "agents"], examples: ["تقارير برامج", "توجيه طلبات المستفيدين", "Partner intelligence"] },
];

export const capabilityById = Object.fromEntries(capabilityCatalog.map((item) => [item.id, item])) as Record<string, Capability>;
export const sectorBySlug = Object.fromEntries(sectorCatalog.map((item) => [item.slug, item])) as Record<string, SectorProfile>;
