// AUTO-GENERATED by scripts/dealix/generate_site_catalog.py — do not edit by hand.
// Public catalog only: 5 core systems + 20 sector solutions.
// The 40 internal systems and routing are intentionally NOT exposed here.

export interface CoreSystem { id: string; nameAr: string; nameEn: string; promiseAr: string; outcomeAr: string; }
export interface SectorNeed { id: string; nameAr: string; coreSystem: string; }
export interface SectorSolution { id: string; nameAr: string; needs: SectorNeed[]; coreSystems: string[]; }

export const coreSystems: CoreSystem[] = [
  {
    "id": "revenue-operating-system",
    "nameAr": "نظام تشغيل الإيرادات",
    "nameEn": "Revenue Operating System",
    "promiseAr": "نُنظّم رحلة العميل من أول تواصل حتى تكرار الشراء، ونكشف أين تضيع الإيرادات.",
    "outcomeAr": "خريطة تسرب إيرادات + عملية مبيعات واضحة + لوحة عملاء موحّدة."
  },
  {
    "id": "executive-command-os",
    "nameAr": "نظام القيادة التنفيذية",
    "nameEn": "Executive Command OS",
    "promiseAr": "نعطي المؤسس صورة يومية واضحة: ماذا يحدث، ما الأولوية، وأين الخطر.",
    "outcomeAr": "لوحة مؤشرات + أولويات يومية + مراجعة أسبوعية + توقع إيرادات."
  },
  {
    "id": "follow-up-recovery-os",
    "nameAr": "نظام استرجاع المتابعات",
    "nameEn": "Follow-up Recovery OS",
    "promiseAr": "نلتقط كل عميل لم تتم متابعته ونعيد تفعيل الصفقات المهجورة.",
    "outcomeAr": "تسلسل متابعة منظم + سرعة رد + استرجاع صفقات + تقرير استرجاع."
  },
  {
    "id": "whatsapp-client-os",
    "nameAr": "نظام عملاء واتساب",
    "nameEn": "WhatsApp Client OS",
    "promiseAr": "نُحوّل فوضى واتساب إلى قناة منظمة بقوالب وفرز ومواعيد.",
    "outcomeAr": "صندوق منظم + قوالب معتمدة + إدارة مواعيد + تقارير محادثات."
  },
  {
    "id": "proposal-proof-os",
    "nameAr": "نظام العروض والإثبات",
    "nameEn": "Proposal & Proof OS",
    "promiseAr": "نبني عروضًا تُقنع وتُثبت القيمة برقم وقصة نجاح، لا بوعود.",
    "outcomeAr": "عروض جاهزة + تسعير منضبط + حزمة إثبات + مكتبة اعتراضات."
  }
];

export const sectorSolutions: SectorSolution[] = [
  {
    "id": "marketing-agencies",
    "nameAr": "وكالات التسويق",
    "needs": [
      {
        "id": "revenue-leak-detection",
        "nameAr": "كشف تسرب الإيرادات",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "slow-lead-response",
        "nameAr": "بطء الرد على العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "missed-followups",
        "nameAr": "متابعات ضائعة",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "weak-pipeline-visibility",
        "nameAr": "ضعف وضوح خط الأنابيب",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "low-proposal-winrate",
        "nameAr": "ضعف قبول العروض",
        "coreSystem": "proposal-proof-os"
      }
    ],
    "coreSystems": [
      "revenue-operating-system",
      "follow-up-recovery-os",
      "executive-command-os",
      "proposal-proof-os"
    ]
  },
  {
    "id": "training-companies",
    "nameAr": "شركات التدريب",
    "needs": [
      {
        "id": "weak-pipeline-visibility",
        "nameAr": "ضعف وضوح خط الأنابيب",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "low-proposal-winrate",
        "nameAr": "ضعف قبول العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "no-proof-of-value",
        "nameAr": "غياب إثبات القيمة",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "whatsapp-chaos",
        "nameAr": "فوضى واتساب",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "manual-reporting",
        "nameAr": "تقارير يدوية متعبة",
        "coreSystem": "executive-command-os"
      }
    ],
    "coreSystems": [
      "executive-command-os",
      "proposal-proof-os",
      "whatsapp-client-os"
    ]
  },
  {
    "id": "clinics",
    "nameAr": "العيادات",
    "needs": [
      {
        "id": "whatsapp-chaos",
        "nameAr": "فوضى واتساب",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "manual-reporting",
        "nameAr": "تقارير يدوية متعبة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "inconsistent-pricing",
        "nameAr": "تسعير غير منضبط",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-onboarding",
        "nameAr": "ضعف إدماج العملاء الجدد",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "churn-risk",
        "nameAr": "خطر فقد العملاء",
        "coreSystem": "revenue-operating-system"
      }
    ],
    "coreSystems": [
      "whatsapp-client-os",
      "executive-command-os",
      "proposal-proof-os",
      "revenue-operating-system"
    ]
  },
  {
    "id": "real-estate",
    "nameAr": "العقار",
    "needs": [
      {
        "id": "weak-onboarding",
        "nameAr": "ضعف إدماج العملاء الجدد",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "churn-risk",
        "nameAr": "خطر فقد العملاء",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "no-sales-process",
        "nameAr": "غياب عملية مبيعات واضحة",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "lead-source-blindness",
        "nameAr": "عمى مصادر العملاء",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "unqualified-leads",
        "nameAr": "عملاء غير مؤهّلين",
        "coreSystem": "follow-up-recovery-os"
      }
    ],
    "coreSystems": [
      "revenue-operating-system",
      "executive-command-os",
      "follow-up-recovery-os"
    ]
  },
  {
    "id": "professional-services",
    "nameAr": "الخدمات المهنية",
    "needs": [
      {
        "id": "lead-source-blindness",
        "nameAr": "عمى مصادر العملاء",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "unqualified-leads",
        "nameAr": "عملاء غير مؤهّلين",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "slow-quote-turnaround",
        "nameAr": "بطء إصدار العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-upsell",
        "nameAr": "ضعف البيع الإضافي",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "team-accountability-gap",
        "nameAr": "فجوة المساءلة في الفريق",
        "coreSystem": "executive-command-os"
      }
    ],
    "coreSystems": [
      "executive-command-os",
      "follow-up-recovery-os",
      "proposal-proof-os",
      "revenue-operating-system"
    ]
  },
  {
    "id": "recruitment",
    "nameAr": "التوظيف",
    "needs": [
      {
        "id": "weak-upsell",
        "nameAr": "ضعف البيع الإضافي",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "team-accountability-gap",
        "nameAr": "فجوة المساءلة في الفريق",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "no-daily-priorities",
        "nameAr": "غياب أولويات يومية واضحة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "customer-data-scatter",
        "nameAr": "تشتت بيانات العملاء",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "abandoned-deals",
        "nameAr": "صفقات مهجورة بلا متابعة",
        "coreSystem": "follow-up-recovery-os"
      }
    ],
    "coreSystems": [
      "revenue-operating-system",
      "executive-command-os",
      "follow-up-recovery-os"
    ]
  },
  {
    "id": "saas",
    "nameAr": "منتجات SaaS",
    "needs": [
      {
        "id": "customer-data-scatter",
        "nameAr": "تشتت بيانات العملاء",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "abandoned-deals",
        "nameAr": "صفقات مهجورة بلا متابعة",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "no-case-studies",
        "nameAr": "غياب قصص النجاح",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "inbound-overflow",
        "nameAr": "تدفق رسائل غير منظّم",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "appointment-noshow",
        "nameAr": "غياب العملاء عن المواعيد",
        "coreSystem": "whatsapp-client-os"
      }
    ],
    "coreSystems": [
      "revenue-operating-system",
      "follow-up-recovery-os",
      "proposal-proof-os",
      "whatsapp-client-os"
    ]
  },
  {
    "id": "logistics",
    "nameAr": "اللوجستيات",
    "needs": [
      {
        "id": "inbound-overflow",
        "nameAr": "تدفق رسائل غير منظّم",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "appointment-noshow",
        "nameAr": "غياب العملاء عن المواعيد",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "weak-reactivation",
        "nameAr": "ضعف إعادة تفعيل العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "revenue-forecast-gap",
        "nameAr": "غياب توقع الإيرادات",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "revenue-leak-detection",
        "nameAr": "كشف تسرب الإيرادات",
        "coreSystem": "revenue-operating-system"
      }
    ],
    "coreSystems": [
      "whatsapp-client-os",
      "follow-up-recovery-os",
      "executive-command-os",
      "revenue-operating-system"
    ]
  },
  {
    "id": "restaurants",
    "nameAr": "المطاعم",
    "needs": [
      {
        "id": "revenue-forecast-gap",
        "nameAr": "غياب توقع الإيرادات",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "revenue-leak-detection",
        "nameAr": "كشف تسرب الإيرادات",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "slow-lead-response",
        "nameAr": "بطء الرد على العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "missed-followups",
        "nameAr": "متابعات ضائعة",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "weak-pipeline-visibility",
        "nameAr": "ضعف وضوح خط الأنابيب",
        "coreSystem": "executive-command-os"
      }
    ],
    "coreSystems": [
      "executive-command-os",
      "revenue-operating-system",
      "follow-up-recovery-os"
    ]
  },
  {
    "id": "education",
    "nameAr": "التعليم",
    "needs": [
      {
        "id": "missed-followups",
        "nameAr": "متابعات ضائعة",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "weak-pipeline-visibility",
        "nameAr": "ضعف وضوح خط الأنابيب",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "low-proposal-winrate",
        "nameAr": "ضعف قبول العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "no-proof-of-value",
        "nameAr": "غياب إثبات القيمة",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "whatsapp-chaos",
        "nameAr": "فوضى واتساب",
        "coreSystem": "whatsapp-client-os"
      }
    ],
    "coreSystems": [
      "follow-up-recovery-os",
      "executive-command-os",
      "proposal-proof-os",
      "whatsapp-client-os"
    ]
  },
  {
    "id": "ecommerce",
    "nameAr": "التجارة الإلكترونية",
    "needs": [
      {
        "id": "no-proof-of-value",
        "nameAr": "غياب إثبات القيمة",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "whatsapp-chaos",
        "nameAr": "فوضى واتساب",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "manual-reporting",
        "nameAr": "تقارير يدوية متعبة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "inconsistent-pricing",
        "nameAr": "تسعير غير منضبط",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-onboarding",
        "nameAr": "ضعف إدماج العملاء الجدد",
        "coreSystem": "revenue-operating-system"
      }
    ],
    "coreSystems": [
      "proposal-proof-os",
      "whatsapp-client-os",
      "executive-command-os",
      "revenue-operating-system"
    ]
  },
  {
    "id": "healthcare",
    "nameAr": "الرعاية الصحية",
    "needs": [
      {
        "id": "inconsistent-pricing",
        "nameAr": "تسعير غير منضبط",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-onboarding",
        "nameAr": "ضعف إدماج العملاء الجدد",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "churn-risk",
        "nameAr": "خطر فقد العملاء",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "no-sales-process",
        "nameAr": "غياب عملية مبيعات واضحة",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "lead-source-blindness",
        "nameAr": "عمى مصادر العملاء",
        "coreSystem": "executive-command-os"
      }
    ],
    "coreSystems": [
      "proposal-proof-os",
      "revenue-operating-system",
      "executive-command-os"
    ]
  },
  {
    "id": "legal-services",
    "nameAr": "الخدمات القانونية",
    "needs": [
      {
        "id": "no-sales-process",
        "nameAr": "غياب عملية مبيعات واضحة",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "lead-source-blindness",
        "nameAr": "عمى مصادر العملاء",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "unqualified-leads",
        "nameAr": "عملاء غير مؤهّلين",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "slow-quote-turnaround",
        "nameAr": "بطء إصدار العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-upsell",
        "nameAr": "ضعف البيع الإضافي",
        "coreSystem": "revenue-operating-system"
      }
    ],
    "coreSystems": [
      "revenue-operating-system",
      "executive-command-os",
      "follow-up-recovery-os",
      "proposal-proof-os"
    ]
  },
  {
    "id": "accounting-firms",
    "nameAr": "مكاتب المحاسبة",
    "needs": [
      {
        "id": "slow-quote-turnaround",
        "nameAr": "بطء إصدار العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-upsell",
        "nameAr": "ضعف البيع الإضافي",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "team-accountability-gap",
        "nameAr": "فجوة المساءلة في الفريق",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "no-daily-priorities",
        "nameAr": "غياب أولويات يومية واضحة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "customer-data-scatter",
        "nameAr": "تشتت بيانات العملاء",
        "coreSystem": "revenue-operating-system"
      }
    ],
    "coreSystems": [
      "proposal-proof-os",
      "revenue-operating-system",
      "executive-command-os"
    ]
  },
  {
    "id": "construction",
    "nameAr": "المقاولات",
    "needs": [
      {
        "id": "no-daily-priorities",
        "nameAr": "غياب أولويات يومية واضحة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "customer-data-scatter",
        "nameAr": "تشتت بيانات العملاء",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "abandoned-deals",
        "nameAr": "صفقات مهجورة بلا متابعة",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "no-case-studies",
        "nameAr": "غياب قصص النجاح",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "inbound-overflow",
        "nameAr": "تدفق رسائل غير منظّم",
        "coreSystem": "whatsapp-client-os"
      }
    ],
    "coreSystems": [
      "executive-command-os",
      "revenue-operating-system",
      "follow-up-recovery-os",
      "proposal-proof-os",
      "whatsapp-client-os"
    ]
  },
  {
    "id": "automotive",
    "nameAr": "السيارات",
    "needs": [
      {
        "id": "no-case-studies",
        "nameAr": "غياب قصص النجاح",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "inbound-overflow",
        "nameAr": "تدفق رسائل غير منظّم",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "appointment-noshow",
        "nameAr": "غياب العملاء عن المواعيد",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "weak-reactivation",
        "nameAr": "ضعف إعادة تفعيل العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "revenue-forecast-gap",
        "nameAr": "غياب توقع الإيرادات",
        "coreSystem": "executive-command-os"
      }
    ],
    "coreSystems": [
      "proposal-proof-os",
      "whatsapp-client-os",
      "follow-up-recovery-os",
      "executive-command-os"
    ]
  },
  {
    "id": "beauty-wellness",
    "nameAr": "التجميل والعناية",
    "needs": [
      {
        "id": "weak-reactivation",
        "nameAr": "ضعف إعادة تفعيل العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "revenue-forecast-gap",
        "nameAr": "غياب توقع الإيرادات",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "revenue-leak-detection",
        "nameAr": "كشف تسرب الإيرادات",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "slow-lead-response",
        "nameAr": "بطء الرد على العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "missed-followups",
        "nameAr": "متابعات ضائعة",
        "coreSystem": "follow-up-recovery-os"
      }
    ],
    "coreSystems": [
      "follow-up-recovery-os",
      "executive-command-os",
      "revenue-operating-system"
    ]
  },
  {
    "id": "events-management",
    "nameAr": "إدارة الفعاليات",
    "needs": [
      {
        "id": "slow-lead-response",
        "nameAr": "بطء الرد على العملاء",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "missed-followups",
        "nameAr": "متابعات ضائعة",
        "coreSystem": "follow-up-recovery-os"
      },
      {
        "id": "weak-pipeline-visibility",
        "nameAr": "ضعف وضوح خط الأنابيب",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "low-proposal-winrate",
        "nameAr": "ضعف قبول العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "no-proof-of-value",
        "nameAr": "غياب إثبات القيمة",
        "coreSystem": "proposal-proof-os"
      }
    ],
    "coreSystems": [
      "follow-up-recovery-os",
      "executive-command-os",
      "proposal-proof-os"
    ]
  },
  {
    "id": "interior-design",
    "nameAr": "التصميم الداخلي",
    "needs": [
      {
        "id": "low-proposal-winrate",
        "nameAr": "ضعف قبول العروض",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "no-proof-of-value",
        "nameAr": "غياب إثبات القيمة",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "whatsapp-chaos",
        "nameAr": "فوضى واتساب",
        "coreSystem": "whatsapp-client-os"
      },
      {
        "id": "manual-reporting",
        "nameAr": "تقارير يدوية متعبة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "inconsistent-pricing",
        "nameAr": "تسعير غير منضبط",
        "coreSystem": "proposal-proof-os"
      }
    ],
    "coreSystems": [
      "proposal-proof-os",
      "whatsapp-client-os",
      "executive-command-os"
    ]
  },
  {
    "id": "financial-services",
    "nameAr": "الخدمات المالية",
    "needs": [
      {
        "id": "manual-reporting",
        "nameAr": "تقارير يدوية متعبة",
        "coreSystem": "executive-command-os"
      },
      {
        "id": "inconsistent-pricing",
        "nameAr": "تسعير غير منضبط",
        "coreSystem": "proposal-proof-os"
      },
      {
        "id": "weak-onboarding",
        "nameAr": "ضعف إدماج العملاء الجدد",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "churn-risk",
        "nameAr": "خطر فقد العملاء",
        "coreSystem": "revenue-operating-system"
      },
      {
        "id": "no-sales-process",
        "nameAr": "غياب عملية مبيعات واضحة",
        "coreSystem": "revenue-operating-system"
      }
    ],
    "coreSystems": [
      "executive-command-os",
      "proposal-proof-os",
      "revenue-operating-system"
    ]
  }
];
