#!/usr/bin/env python3
"""Dealix Enterprise Readiness Model — capability scorer.

Answers the master-prompt question "how do you know you have arrived?" by
measuring *organizational capability*, not features. It scores the platform
across ten enterprise-maturity dimensions using ``readiness_manifest.yaml``
(generated by ``scripts/build_platform_scaffold.py``).

Scoring per system:
    module_status:          implemented = 60   incomplete = 20
    operating_layer_status: verified   = +40   scaffolded = +20   planned = +0

A dimension score is the mean of the systems that advance it. The verdict:
    >= 85 all dimensions  -> ARRIVED
    >= 60 every dimension -> ON_TRACK
    otherwise             -> EARLY

Usage:
    python platform/readiness_model.py
    python platform/readiness_model.py --json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MANIFEST = Path(__file__).resolve().parent / "readiness_manifest.yaml"

MODULE_POINTS = {"implemented": 60, "incomplete": 20, "missing": 0}
LAYER_POINTS = {"verified": 40, "scaffolded": 20, "planned": 0}
ARRIVED, ON_TRACK = 85, 60


def parse_manifest(text: str) -> tuple[list[str], list[dict]]:
    """Minimal parser for the fixed manifest format (no external deps)."""
    dimensions: list[str] = []
    systems: list[dict] = []
    current: dict | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if line.startswith("dimensions:"):
            inner = line.split("[", 1)[1].rsplit("]", 1)[0]
            dimensions = [d.strip() for d in inner.split(",") if d.strip()]
        elif line.lstrip().startswith("- key:"):
            current = {"key": line.split(":", 1)[1].strip()}
            systems.append(current)
        elif current is not None and ":" in line:
            k, v = (p.strip() for p in line.split(":", 1))
            if k in ("dimensions",):
                inner = v.strip("[]")
                current[k] = [x.strip() for x in inner.split(",") if x.strip()]
            elif k in ("phase", "key", "path", "risk_tier",
                       "module_status", "operating_layer_status"):
                current[k] = v
    return dimensions, systems


def system_score(s: dict) -> int:
    return (MODULE_POINTS.get(s.get("module_status", "missing"), 0)
            + LAYER_POINTS.get(s.get("operating_layer_status", "planned"), 0))


def score(dimensions: list[str], systems: list[dict]) -> dict:
    per_dim: dict[str, dict] = {}
    for dim in dimensions:
        contributing = [s for s in systems if dim in s.get("dimensions", [])]
        if contributing:
            avg = round(sum(system_score(s) for s in contributing) / len(contributing), 1)
        else:
            avg = 0.0
        per_dim[dim] = {
            "score": avg,
            "systems": [s["key"] for s in contributing],
            "status": "arrived" if avg >= ARRIVED else "on_track" if avg >= ON_TRACK else "early",
        }
    scores = [d["score"] for d in per_dim.values()]
    if scores and all(v >= ARRIVED for v in scores):
        verdict = "ARRIVED"
    elif scores and all(v >= ON_TRACK for v in scores):
        verdict = "ON_TRACK"
    else:
        verdict = "EARLY"
    return {
        "verdict": verdict,
        "overall": round(sum(scores) / len(scores), 1) if scores else 0.0,
        "dimensions": per_dim,
        "system_count": len(systems),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", action="store_true", help="emit JSON")
    args = ap.parse_args()

    if not MANIFEST.exists():
        print(f"manifest not found: {MANIFEST}", file=sys.stderr)
        print("run: python scripts/build_platform_scaffold.py", file=sys.stderr)
        return 1

    dimensions, systems = parse_manifest(MANIFEST.read_text(encoding="utf-8"))
    result = score(dimensions, systems)

    if args.json:
        print(json.dumps(result, indent=2))
        return 0

    print("Dealix Enterprise Readiness Model")
    print("=" * 52)
    print(f"systems measured: {result['system_count']}")
    print(f"overall capability: {result['overall']}/100\n")
    print(f"{'dimension':<26}{'score':>8}  status")
    print("-" * 52)
    for dim, d in result["dimensions"].items():
        print(f"{dim:<26}{d['score']:>8}  {d['status']}")
    print("-" * 52)
    print(f"DEALIX_ENTERPRISE_MATURITY_VERDICT={result['verdict']}")
    print("\nNote: module_status reflects existing auto_client_acquisition/*")
    print("code; operating_layer_status reflects this governing layer. Lift")
    print("scores by completing each system's readiness.md checklist.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
