min_version = "2026.9.9"

[settings]
lockfile = true
experimental = true

[tools]
actionlint = "latest"
age = "latest"
bat = "latest"
black = "latest"
bottom = "latest"
checkov = "latest"
conftest = "latest"
cosign = "latest"
cyclonedx = "latest"
delta = "latest"
direnv = "latest"
duckdb = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gitleaks = "latest"
grype = "latest"
hadolint = "latest"
hurl = "latest"
hyperfine = "latest"
just = "latest"
jq = "latest"
k6 = "latest"
lychee = "latest"
oha = "latest"
osv-scanner = "latest"
pre-commit = "latest"
rclone = "latest"
restic = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
syft = "latest"
taplo = "latest"
task = "latest"
trivy = "latest"
trufflehog = "latest"
uv = "latest"
vale = "latest"
watchexec = "latest"
xh = "latest"
yq = "latest"
zizmor = "latest"
zoxide = "latest"
