"""Deterministic, exact-scope gate for Dealix commercial external effects.

This module is an authority *verifier*, not an authority source.  It cannot grant
consent, create a relationship, approve a commercial commitment, or execute a
provider call.  Provider adapters may execute only when this gate returns
``READY_FOR_PROVIDER_EXECUTION`` for the exact action fingerprint and the
runtime authority switches are already enabled by canonical governance.
"""
from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

ActionClass = Literal[
    "EMAIL_SEND",
    "WHATSAPP_SEND",
    "COMPANY_SOCIAL_PUBLISH",
    "CUSTOMER_QUOTE_SEND",
    "TENDER_SUBMISSION",
    "CONTRACT_COMMITMENT",
    "PAYMENT",
    "REFUND",
    "FOUNDER_LINKEDIN_MANUAL",
]
PurposeClass = Literal[
    "DIRECT_MARKETING",
    "INBOUND_REPLY",
    "REQUESTED_FOLLOWUP",
    "TRANSACTIONAL",
    "CUSTOMER_QUOTE",
    "TENDER_SUBMISSION",
    "PUBLIC_PUBLISH",
    "CONTRACT",
    "PAYMENT",
    "REFUND",
]
ApprovalState = Literal["PENDING", "APPROVED", "REVOKED", "EXPIRED", "UNKNOWN"]
RiskClass = Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]

UNKNOWN = "UNKNOWN_NOT_EVIDENCE_BACKED"
SCHEMA = "dealix.external-action-packet.v1"


def _aware(value: str, *, field: str) -> datetime:
    text = value.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError as exc:  # pragma: no cover - pydantic tests cover callers
        raise ValueError(f"{field} must be ISO-8601") from exc
    if parsed.tzinfo is None:
        raise ValueError(f"{field} must include timezone")
    return parsed.astimezone(UTC)


def _refs(values: list[str], *, field: str, allow_empty: bool = False) -> list[str]:
    cleaned = [str(value).strip() for value in values if str(value).strip()]
    if len(cleaned) != len(values):
        raise ValueError(f"{field} cannot contain blank references")
    if not cleaned and not allow_empty:
        raise ValueError(f"{field} requires evidence")
    return cleaned


def canonical_content_sha256(*, destination: str, subject: str, body: str) -> str:
    """Hash the exact commercial message material without storing it in receipts."""
    payload = json.dumps(
        {"destination": destination.strip(), "subject": subject, "body": body},
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


class RuntimeAuthority(BaseModel):
    """Effective runtime switches. Defaults can only deny, never grant authority."""

    model_config = ConfigDict(extra="forbid")

    external_send: bool = False
    public_publish: bool = False
    named_quote: bool = False
    tender_submission: bool = False
    legal_commitment: bool = False
    payment_or_refund: bool = False
    connector_write: bool = False


class ExternalActionPacket(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: str = SCHEMA
    action_id: str = Field(..., min_length=1)
    action_class: ActionClass
    purpose_class: PurposeClass
    destination: str = Field(..., min_length=1)
    channel: str = Field(..., min_length=1)
    artifact_ref: str = Field(..., min_length=1)
    content_sha256: str = Field(..., min_length=64, max_length=64)
    identity_or_relationship_ref: str = ""
    consent_or_channel_eligibility_ref: str = ""
    suppression_check_ref: str = Field(..., min_length=1)
    suppression_clear: bool = False
    claim_evidence_refs: list[str] = Field(default_factory=list)
    sender_identity_ref: str = Field(..., min_length=1)
    opt_out_mechanism_ref: str = ""
    risk_class: RiskClass = "MEDIUM"
    exact_scope: str = Field(..., min_length=1)
    expires_at: str = Field(..., min_length=1)
    provider: str = Field(..., min_length=1)
    idempotency_key: str = Field(..., min_length=1)
    action_fingerprint: str = Field(..., min_length=64, max_length=64)

    @field_validator("content_sha256", "action_fingerprint")
    @classmethod
    def _hex64(cls, value: str) -> str:
        text = value.strip().lower()
        if len(text) != 64 or any(ch not in "0123456789abcdef" for ch in text):
            raise ValueError("must be a 64-character lowercase SHA-256 hex digest")
        return text

    @field_validator("expires_at")
    @classmethod
    def _timestamp(cls, value: str) -> str:
        _aware(value, field="packet.expires_at")
        return value


class ApprovalEnvelope(BaseModel):
    """Projection of canonical approval evidence; never generated by this gate."""

    model_config = ConfigDict(extra="forbid")

    approval_id: str = Field(..., min_length=1)
    action_fingerprint: str = Field(..., min_length=64, max_length=64)
    exact_scope: str = Field(..., min_length=1)
    authority_class: str = Field(..., min_length=1)
    approval_state: ApprovalState
    approval_state_ref: str = Field(..., min_length=1)
    state_checked_at: str = Field(..., min_length=1)
    expires_at: str = Field(..., min_length=1)
    evidence_refs: list[str] = Field(default_factory=list)

    @field_validator("action_fingerprint")
    @classmethod
    def _fingerprint(cls, value: str) -> str:
        text = value.strip().lower()
        if len(text) != 64 or any(ch not in "0123456789abcdef" for ch in text):
            raise ValueError("action_fingerprint must be SHA-256")
        return text

    @field_validator("state_checked_at", "expires_at")
    @classmethod
    def _approval_timestamp(cls, value: str) -> str:
        _aware(value, field="approval timestamp")
        return value


class ExecutionDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verdict: str
    action_fingerprint: str
    provider_execution_allowed: bool
    approval_valid: bool
    runtime_authority_pass: bool
    reasons: list[str]
    required_next_action: str


def build_external_action_packet(
    *,
    action_id: str,
    action_class: ActionClass,
    purpose_class: PurposeClass,
    destination: str,
    channel: str,
    artifact_ref: str,
    content_sha256: str,
    identity_or_relationship_ref: str = "",
    consent_or_channel_eligibility_ref: str = "",
    suppression_check_ref: str,
    suppression_clear: bool,
    claim_evidence_refs: list[str],
    sender_identity_ref: str,
    opt_out_mechanism_ref: str = "",
    risk_class: RiskClass = "MEDIUM",
    exact_scope: str,
    expires_at: str,
    provider: str,
    idempotency_key: str,
) -> ExternalActionPacket:
    material = {
        "action_id": action_id.strip(),
        "action_class": action_class,
        "purpose_class": purpose_class,
        "destination": destination.strip(),
        "channel": channel.strip(),
        "artifact_ref": artifact_ref.strip(),
        "content_sha256": content_sha256.strip().lower(),
        "identity_or_relationship_ref": identity_or_relationship_ref.strip(),
        "consent_or_channel_eligibility_ref": consent_or_channel_eligibility_ref.strip(),
        "suppression_check_ref": suppression_check_ref.strip(),
        "suppression_clear": bool(suppression_clear),
        "claim_evidence_refs": sorted(_refs(claim_evidence_refs, field="claim_evidence_refs")),
        "sender_identity_ref": sender_identity_ref.strip(),
        "opt_out_mechanism_ref": opt_out_mechanism_ref.strip(),
        "risk_class": risk_class,
        "exact_scope": exact_scope.strip(),
        "expires_at": expires_at.strip(),
        "provider": provider.strip(),
        "idempotency_key": idempotency_key.strip(),
    }
    canonical = json.dumps(material, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    fingerprint = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    return ExternalActionPacket(**material, action_fingerprint=fingerprint)


def _required_runtime_switches(action_class: ActionClass) -> tuple[str, ...]:
    mapping: dict[str, tuple[str, ...]] = {
        "EMAIL_SEND": ("external_send", "connector_write"),
        "WHATSAPP_SEND": ("external_send", "connector_write"),
        "COMPANY_SOCIAL_PUBLISH": ("public_publish", "connector_write"),
        "CUSTOMER_QUOTE_SEND": ("external_send", "named_quote", "connector_write"),
        "TENDER_SUBMISSION": ("tender_submission", "connector_write"),
        "CONTRACT_COMMITMENT": ("legal_commitment", "external_send", "connector_write"),
        "PAYMENT": ("payment_or_refund", "connector_write"),
        "REFUND": ("payment_or_refund", "connector_write"),
        "FOUNDER_LINKEDIN_MANUAL": (),
    }
    return mapping[action_class]


def evaluate_external_action(
    packet: ExternalActionPacket,
    *,
    approval: ApprovalEnvelope | None,
    runtime: RuntimeAuthority | None = None,
    evaluated_at: str | None = None,
) -> ExecutionDecision:
    runtime = runtime or RuntimeAuthority()
    now = _aware(evaluated_at, field="evaluated_at") if evaluated_at else datetime.now(UTC)
    reasons: list[str] = []

    if packet.action_class == "FOUNDER_LINKEDIN_MANUAL":
        return ExecutionDecision(
            verdict="MANUAL_NATIVE_ONLY",
            action_fingerprint=packet.action_fingerprint,
            provider_execution_allowed=False,
            approval_valid=False,
            runtime_authority_pass=False,
            reasons=["PERSONAL_LINKEDIN_AUTOMATION_BLOCKED"],
            required_next_action="FOUNDER_MANUAL_NATIVE",
        )

    packet_expiry = _aware(packet.expires_at, field="packet.expires_at")
    if packet_expiry <= now:
        reasons.append("PACKET_EXPIRED")
    if not packet.suppression_clear:
        reasons.append("SUPPRESSED_OR_SUPPRESSION_NOT_PROVEN_CLEAR")
    if not packet.suppression_check_ref.strip():
        reasons.append("MISSING_SUPPRESSION_CHECK_REF")
    if not packet.sender_identity_ref.strip():
        reasons.append("MISSING_SENDER_IDENTITY_REF")
    if not packet.claim_evidence_refs:
        reasons.append("MISSING_CLAIM_EVIDENCE_REFS")

    is_message = packet.action_class in {"EMAIL_SEND", "WHATSAPP_SEND", "CUSTOMER_QUOTE_SEND", "CONTRACT_COMMITMENT"}
    if is_message and not packet.identity_or_relationship_ref.strip():
        reasons.append("MISSING_IDENTITY_OR_RELATIONSHIP_REF")

    if packet.purpose_class == "DIRECT_MARKETING":
        if not packet.consent_or_channel_eligibility_ref.strip():
            reasons.append("DIRECT_MARKETING_CONSENT_NOT_PROVEN")
        if not packet.opt_out_mechanism_ref.strip():
            reasons.append("DIRECT_MARKETING_OPT_OUT_NOT_PROVEN")

    if packet.action_class == "WHATSAPP_SEND" and not packet.consent_or_channel_eligibility_ref.strip():
        reasons.append("WHATSAPP_KNOWN_CONSENTED_OR_INBOUND_BASIS_NOT_PROVEN")

    approval_valid = False
    if approval is None:
        reasons.append("EXACT_ACTION_APPROVAL_MISSING")
    else:
        checked = _aware(approval.state_checked_at, field="approval.state_checked_at")
        approval_expiry = _aware(approval.expires_at, field="approval.expires_at")
        if checked > now:
            reasons.append("APPROVAL_STATE_CHECKED_IN_FUTURE")
        if approval.approval_state != "APPROVED":
            reasons.append(f"APPROVAL_STATE_{approval.approval_state}")
        if approval_expiry <= now:
            reasons.append("APPROVAL_EXPIRED")
        if approval.action_fingerprint != packet.action_fingerprint:
            reasons.append("APPROVAL_FINGERPRINT_MISMATCH")
        if approval.exact_scope != packet.exact_scope:
            reasons.append("APPROVAL_SCOPE_MISMATCH")
        if approval.authority_class != packet.action_class:
            reasons.append("APPROVAL_AUTHORITY_CLASS_MISMATCH")
        if not approval.approval_state_ref.strip() or not approval.evidence_refs:
            reasons.append("APPROVAL_EVIDENCE_INCOMPLETE")
        approval_valid = not any(reason.startswith("APPROVAL_") or reason == "EXACT_ACTION_APPROVAL_MISSING" for reason in reasons)

    switches = _required_runtime_switches(packet.action_class)
    missing_switches = [name for name in switches if not bool(getattr(runtime, name))]
    if missing_switches:
        reasons.append("RUNTIME_AUTHORITY_DISABLED:" + ",".join(sorted(missing_switches)))
    runtime_pass = not missing_switches

    hard_reasons = [r for r in reasons if not r.startswith("RUNTIME_AUTHORITY_DISABLED:")]
    if hard_reasons:
        verdict = "HOLD_NOT_EXECUTION_ELIGIBLE"
        next_action = "REPAIR_EVIDENCE_OR_EXACT_APPROVAL"
    elif not runtime_pass:
        verdict = "READY_BUT_RUNTIME_AUTHORITY_DISABLED"
        next_action = "KEEP_HELD_UNTIL_CANONICAL_RUNTIME_AUTHORITY_IS_EXPLICITLY_ENABLED"
    else:
        verdict = "READY_FOR_PROVIDER_EXECUTION"
        next_action = "EXECUTE_ONCE_WITH_IDEMPOTENCY_AND_WRITE_PROVIDER_RECEIPT"

    return ExecutionDecision(
        verdict=verdict,
        action_fingerprint=packet.action_fingerprint,
        provider_execution_allowed=verdict == "READY_FOR_PROVIDER_EXECUTION",
        approval_valid=approval_valid,
        runtime_authority_pass=runtime_pass,
        reasons=reasons,
        required_next_action=next_action,
    )


__all__ = [
    "UNKNOWN",
    "SCHEMA",
    "ApprovalEnvelope",
    "ExecutionDecision",
    "ExternalActionPacket",
    "RuntimeAuthority",
    "build_external_action_packet",
    "canonical_content_sha256",
    "evaluate_external_action",
]
