"""Diagnostic Engine — bilingual brief composer.

Pure local composition: no LLM calls, no external HTTP. Reads the
real Service Readiness Matrix at ``docs/registry/SERVICE_READINESS_MATRIX.yaml``
(list-shaped bundles + services, NOT a dict-of-dicts) and produces an
Arabic-first / English-secondary markdown brief tagged
``approval_required``.

This engine intentionally mirrors the rendering logic of
``scripts/dealix_diagnostic.py`` so the CLI + API + tests share one
source of truth. The CLI delegates to ``generate_diagnostic`` rather
than duplicating the markdown.
"""
from __future__ import annotations

from datetime import UTC, date, datetime
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

from auto_client_acquisition.diagnostic_engine.schemas import (
    DiagnosticRequest,
    DiagnosticResult,
)


_PROJECT_ROOT = Path(__file__).resolve().parents[2]
MATRIX_PATH = _PROJECT_ROOT / "docs" / "registry" / "SERVICE_READINESS_MATRIX.yaml"


# Sector → recommended bundle. Mirrors the CLI's _SECTOR_DEFAULTS.
SECTOR_BUNDLE_MAP: dict[str, str] = {
    "b2b_services": "growth_starter",
    "b2b_saas": "growth_starter",
    "agency": "partnership_growth",
    "training_consulting": "growth_starter",
    "local_services": "growth_starter",
    "ecommerce_b2c": "growth_starter",
    "real_estate": "growth_starter",
    "healthcare_clinic": "growth_starter",
}


_SAFETY_NOTES: tuple[str, ...] = (
    "هذا الموجز للمراجعة فقط — لن يُرسَل أيّ رسالة دون موافقة المؤسس.",
    "Brief is for review only — no outbound message sent without founder approval.",
    "نلتزم بنظام حماية البيانات الشخصية (PDPL) وقواعد التواصل المسموحة.",
    "PDPL + contactability rules respected end-to-end.",
)


@lru_cache(maxsize=1)
def _load_matrix() -> dict[str, Any]:
    if not MATRIX_PATH.exists():
        return {"bundles": [], "services": []}
    with MATRIX_PATH.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    data.setdefault("bundles", [])
    data.setdefault("services", [])
    return data


def list_supported_sectors() -> list[str]:
    return sorted(SECTOR_BUNDLE_MAP.keys())


def _bundle_dict(matrix: dict[str, Any], bundle_id: str) -> dict[str, Any]:
    for b in matrix.get("bundles") or []:
        if b.get("id") == bundle_id:
            return b
    return {}


def _services_in_bundle(matrix: dict[str, Any], bundle_id: str) -> list[dict[str, Any]]:
    return [
        s for s in matrix.get("services") or []
        if s.get("bundle") == bundle_id
    ]


def _recommended_bundle_for(sector: str) -> str:
    return SECTOR_BUNDLE_MAP.get(sector, "growth_starter")


def _render_markdown(
    *,
    company: str,
    sector: str,
    region: str,
    pipeline_state: str,
    bundle_id: str,
    bundle_name_ar: str,
    bundle_name_en: str,
    bundle_summary_ar: str,
    bundle_summary_en: str,
    services: list[dict[str, Any]],
) -> str:
    today = date.today().isoformat()
    pipeline_text = pipeline_state.strip() or "(غير محدّد — املأ بعد المكالمة الاستكشافيّة)"
    pipeline_text_en = pipeline_state.strip() or "(unknown — fill after the discovery call)"

    md: list[str] = []

    # Header
    md.append(f"# Diagnostic — {company}")
    md.append("")
    md.append(f"> **Date:** {today}  \\")
    md.append(f"> **Sector:** `{sector}`  \\")
    md.append(f"> **Region:** `{region}`  \\")
    md.append("> **Generated by:** Dealix Diagnostic Engine (manual review required before send)")
    md.append("")
    md.append("---")
    md.append("")

    # Arabic primary
    md.append("## القراءة السريعة (عربي)")
    md.append("")
    md.append(f"**الشركة:** {company}")
    md.append(f"**القطاع:** {sector} — {region}")
    md.append("")
    md.append("**الوضع الحاليّ كما وُصف:**")
    md.append(f"> {pipeline_text}")
    md.append("")
    md.append("**التشخيص الأوّليّ — الفجوات الأكثر أهميّة:**")
    md.append("1. لا يوجد مسار واضح للاستقبال + التأهيل + الردّ خلال SLA محدّد.")
    md.append("2. الردّ يعتمد على المؤسس، ممّا يخلق عنق زجاجة بعد ساعات الذروة.")
    md.append("3. لا توجد أدلّة مكتوبة (Proof Pack) لإقناع العميل التالي.")
    md.append("")
    md.append(f"**التوصية:** ابدؤوا بـ **{bundle_name_ar}** ({bundle_id}).")
    if bundle_summary_ar:
        md.append(f"> {bundle_summary_ar}")
    md.append("")
    md.append("**ما يشمله الـ Pilot 7 أيّام (499 ريال):**")
    for s in services[:7]:
        sid = s.get("service_id", "?")
        name_ar = s.get("name_ar", sid)
        sla = s.get("sla", "—")
        md.append(f"- `{sid}` — {name_ar} (SLA: {sla})")
    md.append("")
    md.append("**ما لن نفعله:**")
    md.append("- ❌ لا cold WhatsApp ولا cold email — موافقة العميل شرط.")
    md.append("- ❌ لا scraping ولا قوائم مشتراة.")
    md.append("- ❌ لا التزام بأرقام/ترتيب — التزام بالعمل والـ Proof Pack.")
    md.append("- ❌ لا خصم آليّ — الدفع عبر Moyasar test mode بإشراف المؤسس.")
    md.append("")
    md.append("**التسعير:** Pilot 499 ريال (سعر تعريفيّ ثابت حتّى العميل #5).")
    md.append("")
    md.append("---")
    md.append("")

    # English secondary
    md.append("## Executive summary (English)")
    md.append("")
    md.append(f"**Company:** {company}")
    md.append(f"**Sector / region:** {sector} / {region}")
    md.append("")
    md.append("**Current state (as described):**")
    md.append(f"> {pipeline_text_en}")
    md.append("")
    md.append("**Initial assessment — top three gaps:**")
    md.append("1. No structured inbound → qualification → reply pipeline with explicit SLAs.")
    md.append("2. Reply path depends on the founder, creating a bottleneck after peak hours.")
    md.append("3. No written Proof Pack to convince the next prospect.")
    md.append("")
    md.append(f"**Recommended starting bundle:** **{bundle_name_en}** (`{bundle_id}`).")
    if bundle_summary_en:
        md.append(f"> {bundle_summary_en}")
    md.append("")
    md.append("**Pilot 7 days, 499 SAR — included:**")
    for s in services[:7]:
        sid = s.get("service_id", "?")
        name_en = s.get("name_en", sid)
        sla = s.get("sla", "—")
        md.append(f"- `{sid}` — {name_en} (SLA: {sla})")
    md.append("")
    md.append("**What we will NOT do:**")
    md.append("- ❌ No cold WhatsApp / cold email — explicit consent required.")
    md.append("- ❌ No scraping or purchased lists.")
    md.append("- ❌ No revenue / ranking commitment — only the work + Proof Pack.")
    md.append("- ❌ No auto-charge — Moyasar test-mode invoice, founder-supervised.")
    md.append("")
    md.append("**Pricing:** 499 SAR Pilot (locked introductory price until customer #5).")
    md.append("")
    md.append("---")
    md.append("")
    md.append("> ⚠️ **Founder review required before sending.**")
    return "\n".join(md)


def generate_diagnostic(request: DiagnosticRequest) -> DiagnosticResult:
    matrix = _load_matrix()
    bundle_id = _recommended_bundle_for(request.sector)
    bundle = _bundle_dict(matrix, bundle_id)
    services = _services_in_bundle(matrix, bundle_id)

    bundle_name_ar = bundle.get("name_ar", bundle_id)
    bundle_name_en = bundle.get("name_en", bundle_id)
    bundle_summary_ar = bundle.get("summary_ar", "")
    bundle_summary_en = bundle.get("summary_en", "")

    md = _render_markdown(
        company=request.company,
        sector=request.sector,
        region=request.region,
        pipeline_state=request.pipeline_state,
        bundle_id=bundle_id,
        bundle_name_ar=bundle_name_ar,
        bundle_name_en=bundle_name_en,
        bundle_summary_ar=bundle_summary_ar,
        bundle_summary_en=bundle_summary_en,
        services=services,
    )

    return DiagnosticResult(
        company=request.company,
        recommended_bundle=bundle_id,
        bundle_name_ar=bundle_name_ar,
        bundle_name_en=bundle_name_en,
        services_in_bundle=[s.get("service_id", "?") for s in services],
        markdown_ar_en=md,
        approval_status="approval_required",
        safety_notes=list(_SAFETY_NOTES),
    )
