"""Canonical commercial runtime surfaces that quarantine retired price/offer authority."""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, ConfigDict, Field

from api.security.api_key import require_admin_key
from dealix.commercial_ops.objections import match_objections
from dealix.revenue_ops_autopilot.policies import INVOICE_DRAFT_ALLOWED_LEAD_STAGES
from dealix.revenue_ops_autopilot.schemas import EvidenceEvent, InvoiceDraftRecord
from dealix.revenue_ops_autopilot.store import get_autopilot_store, uid
from dealix.revenue_ops_autopilot.war_room import normalize_lead

router = APIRouter(tags=["commercial-runtime-truth"])

CANONICAL_PRIMARY_OFFER_ID = "revenue_command_pilot_30d"
CANONICAL_ENTRY_OFFER_ID = "free_mini_diagnostic"


class CustomerSpecificInvoiceDraftPayload(BaseModel):
    """Record an invoice draft from an already-approved customer-specific quote.

    This payload intentionally contains no tier/catalog field. The amount is copied from
    the approved quote authority and is never generated by this endpoint.
    """

    model_config = ConfigDict(extra="forbid")

    lead_id: str = Field(..., min_length=1)
    approved_amount_sar: float = Field(..., gt=0)
    qualified_discovery_ref: str = Field(..., min_length=1)
    customer_specific_scope_ref: str = Field(..., min_length=1)
    quote_authority_ref: str = Field(..., min_length=1)


def _require_non_blank(value: str, *, field_name: str) -> str:
    cleaned = value.strip()
    if not cleaned:
        raise HTTPException(
            status_code=422,
            detail={"reason": "commercial_authority_ref_required", "field": field_name},
        )
    return cleaned


def _append_evidence_event(
    *,
    event_type: str,
    summary: str,
    entity_type: str = "",
    entity_id: str = "",
) -> EvidenceEvent:
    ev = EvidenceEvent(
        id=uid("ev"),
        event_type=event_type,
        entity_type=entity_type,
        entity_id=entity_id,
        summary=summary,
    )
    return get_autopilot_store().append_evidence(ev)


@router.get("/api/v1/public/services")
async def public_services_catalog_canonical() -> dict[str, Any]:
    """Expose the current quote-only buying path with no public price authority."""
    return {
        "entry_offer": {
            "id": CANONICAL_ENTRY_OFFER_ID,
            "label_ar": "Mini Diagnostic مجاني",
            "label_en": "Free Mini Diagnostic",
            "price_model": "free",
        },
        "primary_offer": {
            "id": CANONICAL_PRIMARY_OFFER_ID,
            "label_ar": "Revenue Command Pilot — 30 يومًا",
            "label_en": "Revenue Command Pilot — 30 Days",
            "duration_days": 30,
            "price_model": "customer_specific_quote_only",
            "public_fixed_pricing": False,
            "public_checkout": False,
        },
        "buying_path": [
            "FREE_MINI_DIAGNOSTIC",
            "QUALIFIED_DISCOVERY",
            "CUSTOMER_SPECIFIC_QUOTE",
            "REVENUE_COMMAND_PILOT_30D",
            "VERIFIED_PAYMENT",
            "DELIVERY",
            "CUSTOMER_VALIDATED_PROOF",
        ],
        "guardrails": {
            "no_public_fixed_price": True,
            "no_public_checkout": True,
            "quote_requires_qualified_discovery": True,
            "quote_requires_explicit_authority": True,
            "invoice_is_not_payment": True,
        },
    }


@router.get(
    "/api/v1/ops-autopilot/leads/{lead_id}/meeting-brief",
    dependencies=[Depends(require_admin_key)],
)
async def ops_lead_meeting_brief_canonical(
    lead_id: str,
    locale: str = "ar",
) -> dict[str, Any]:
    lead = get_autopilot_store().get_lead(lead_id)
    if not lead:
        raise HTTPException(status_code=404, detail="lead_not_found")
    lead = normalize_lead(lead)

    questions_ar = [
        "أين يضيع الإيراد بعد أول تواصل؟",
        "من يملك المتابعة اليوم (اسم/دور)؟",
        "هل CRM موثوق للـ AI أم توجد فجوات مصدر؟",
        "هل توجد موافقة قبل أي إجراء خارجي؟",
        "ما المشكلة المحددة التي تستحق Mini Diagnostic الآن؟",
        "ما baseline وطريقة الإثبات التي ستحدد نجاح Pilot لمدة 30 يومًا؟",
    ]
    pain_blob = " ".join(
        filter(
            None,
            [lead.pain_hypothesis, lead.pain, lead.company, lead.segment, lead.industry],
        ),
    )
    objection_hints = match_objections(pain_blob, limit=4)
    if not objection_hints:
        objection_hints = match_objections("crm وكالة سعر", limit=3)

    return {
        "lead_id": lead_id,
        "company": lead.company,
        "segment": lead.segment,
        "pain_hypothesis": lead.pain_hypothesis or lead.pain,
        "discovery_questions_ar": questions_ar,
        "demo_path": f"/{locale}/business-now#strategy",
        "entry_offer": CANONICAL_ENTRY_OFFER_ID,
        "recommended_offer": CANONICAL_PRIMARY_OFFER_ID,
        "offer_route": [
            "FREE_MINI_DIAGNOSTIC",
            "QUALIFIED_DISCOVERY",
            "CUSTOMER_SPECIFIC_QUOTE",
            "REVENUE_COMMAND_PILOT_30D",
        ],
        "outreach_draft_ar": lead.outreach_draft_snippet_ar,
        "objection_hints": objection_hints,
        "policy_ar": (
            "لا سعر عام · لا ضمان ROI · لا إرسال آلي · "
            "العرض المخصص فقط بعد Qualified Discovery."
        ),
    }


@router.post(
    "/api/v1/invoices/draft",
    dependencies=[Depends(require_admin_key)],
)
async def invoice_create_draft_from_approved_quote(
    body: CustomerSpecificInvoiceDraftPayload,
) -> dict[str, Any]:
    lead_id = _require_non_blank(body.lead_id, field_name="lead_id")
    qualified_discovery_ref = _require_non_blank(
        body.qualified_discovery_ref,
        field_name="qualified_discovery_ref",
    )
    customer_specific_scope_ref = _require_non_blank(
        body.customer_specific_scope_ref,
        field_name="customer_specific_scope_ref",
    )
    quote_authority_ref = _require_non_blank(
        body.quote_authority_ref,
        field_name="quote_authority_ref",
    )

    store = get_autopilot_store()
    lead_bind = store.get_lead(lead_id)
    if not lead_bind:
        raise HTTPException(status_code=404, detail="lead_not_found")
    if lead_bind.stage not in INVOICE_DRAFT_ALLOWED_LEAD_STAGES:
        raise HTTPException(
            status_code=422,
            detail={
                "reason": "invoice_draft_blocked_until_scope_sent",
                "current_stage": lead_bind.stage,
                "allowed_lead_stages": sorted(INVOICE_DRAFT_ALLOWED_LEAD_STAGES),
            },
        )

    inv = InvoiceDraftRecord(
        id=uid("inv"),
        lead_id=lead_id,
        tier="customer_specific_quote",
        amount_sar=body.approved_amount_sar,
        line_items_ar=[
            "Revenue Command Pilot — 30 يومًا — نطاق عميل مخصص ومعتمد",
            "المبلغ منسوخ من عرض العميل المعتمد؛ مسودة الفاتورة ليست دفعًا.",
        ],
        status="approval_required",
        governance_note_ar=(
            "مسودة فقط: لا إرسال، لا رابط دفع، ولا تحصيل تلقائي. "
            "تتطلب موافقة مستقلة وإثبات دفع مستقل."
        ),
    )
    store.append_invoice_draft(inv)

    try:
        from auto_client_acquisition.approval_center import get_default_approval_store
        from auto_client_acquisition.approval_center.schemas import ApprovalRequest

        get_default_approval_store().create(
            ApprovalRequest(
                object_type="invoice_draft",
                object_id=inv.id,
                action_type="payment_reminder",
                action_mode="approval_required",
                channel="finance_manual",
                summary_ar=(
                    "مسودة فاتورة من عرض عميل مخصص ومعتمد؛ "
                    "تحتاج موافقة مستقلة قبل أي إرسال أو طلب دفع."
                ),
            ),
        )
    except Exception:
        pass

    _append_evidence_event(
        event_type="invoice_draft_created_from_customer_specific_quote",
        summary=(
            f"id={inv.id} lead_id={lead_id} "
            f"qualified_discovery_ref={qualified_discovery_ref} "
            f"customer_specific_scope_ref={customer_specific_scope_ref} "
            f"quote_authority_ref={quote_authority_ref} "
            f"approved_amount_sar={body.approved_amount_sar} "
            "payment_verified=false"
        ),
        entity_type="invoice_draft",
        entity_id=inv.id,
    )
    return {
        "item": inv.model_dump(mode="json"),
        "authority": {
            "qualified_discovery_ref": qualified_discovery_ref,
            "customer_specific_scope_ref": customer_specific_scope_ref,
            "quote_authority_ref": quote_authority_ref,
            "amount_source": "approved_customer_specific_quote",
            "payment_verified": False,
        },
    }
