"""Self-Growth OS — read-only endpoints.

This is a deliberately small surface. It exposes the Service
Activation Console payload over the API so dashboards and the
founder daily brief can consume the same source of truth as
``/status.html``. No external actions, no live writes.

The full Self-Growth OS (search radar, content drafts, distribution
planner, etc.) is *deferred* — see ``docs/SELF_GROWTH_OS_SCOPE.md``.
Each subsequent phase will land as its own router with its own
tests after explicit founder approval.
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/api/v1/self-growth", tags=["self-growth"])

REPO_ROOT = Path(__file__).resolve().parents[2]
MATRIX_JSON = REPO_ROOT / "landing" / "assets" / "data" / "service-readiness.json"
SEO_REPORT = REPO_ROOT / "docs" / "SEO_AUDIT_REPORT.json"


def _load_json(path: Path) -> dict:
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                f"{path.name} not generated yet. "
                "Run scripts/export_service_readiness_json.py and "
                "scripts/seo_audit.py."
            ),
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=f"{path.name} is not valid JSON: {exc.msg}",
        ) from exc


@router.get("/status")
async def self_growth_status() -> dict:
    """Summary of what the Self-Growth OS currently exposes.

    This endpoint is the cheapest dashboard probe — it tells callers
    which sub-payloads are available without fetching them.
    """
    return {
        "service_activation_available": MATRIX_JSON.exists(),
        "seo_audit_available": SEO_REPORT.exists(),
        "deferred_phases_doc": "docs/SELF_GROWTH_OS_SCOPE.md",
        "guardrails": {
            "no_live_send": True,
            "no_scraping": True,
            "no_cold_outreach": True,
            "approval_required_for_external_actions": True,
        },
    }


@router.get("/service-activation")
async def service_activation_matrix() -> dict:
    """Return the Service Activation Matrix exactly as the static
    landing site consumes it.

    Source of truth: ``docs/registry/SERVICE_READINESS_MATRIX.yaml``
    Regenerated by: ``scripts/export_service_readiness_json.py``
    """
    return _load_json(MATRIX_JSON)


@router.get("/seo/audit")
async def seo_audit_report() -> dict:
    """Return the latest technical-SEO audit report.

    Generated by: ``scripts/seo_audit.py``
    """
    return _load_json(SEO_REPORT)
