"""Self-Growth OS — read-only endpoints + safe-publishing-gate POST.

Exposes the Service Activation Matrix, SEO audit, tool registry,
and a publishing-gate check. All endpoints are pure reads except
``/publishing/check`` which evaluates a string against the
forbidden-claims regex without storing it.

No external send / charge / scrape paths. No auto-write to DB.
Drafts go to the existing ApprovalGate (Redis) — not handled here.
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, Body, HTTPException

from auto_client_acquisition.self_growth_os import (
    safe_publishing_gate,
    service_activation_matrix,
    seo_technical_auditor,
    tool_registry,
)

router = APIRouter(prefix="/api/v1/self-growth", tags=["self-growth"])

REPO_ROOT = Path(__file__).resolve().parents[2]
MATRIX_JSON = REPO_ROOT / "landing" / "assets" / "data" / "service-readiness.json"
SEO_REPORT = REPO_ROOT / "docs" / "SEO_AUDIT_REPORT.json"


def _load_json(path: Path) -> dict:
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                f"{path.name} not generated yet. "
                "Run scripts/export_service_readiness_json.py and "
                "scripts/seo_audit.py."
            ),
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=f"{path.name} is not valid JSON: {exc.msg}",
        ) from exc


@router.get("/status")
async def self_growth_status() -> dict:
    """Summary of what the Self-Growth OS currently exposes.

    This endpoint is the cheapest dashboard probe — it tells callers
    which sub-payloads are available without fetching them.
    """
    return {
        "service_activation_available": MATRIX_JSON.exists(),
        "seo_audit_available": SEO_REPORT.exists(),
        "deferred_phases_doc": "docs/SELF_GROWTH_OS_SCOPE.md",
        "guardrails": {
            "no_live_send": True,
            "no_scraping": True,
            "no_cold_outreach": True,
            "approval_required_for_external_actions": True,
        },
    }


@router.get("/service-activation")
async def get_service_activation_payload() -> dict:
    """Return the Service Activation Matrix exactly as the static
    landing site consumes it.

    Source of truth: ``docs/registry/SERVICE_READINESS_MATRIX.yaml``
    Regenerated by: ``scripts/export_service_readiness_json.py``
    """
    return _load_json(MATRIX_JSON)


@router.get("/seo/audit")
async def seo_audit_report() -> dict:
    """Return the latest technical-SEO audit report.

    Generated by: ``scripts/seo_audit.py``
    """
    return _load_json(SEO_REPORT)


@router.get("/service-activation/{service_id}")
async def service_activation_one(service_id: str) -> dict:
    """Return the typed activation check for one service.

    Wraps ``self_growth_os.service_activation_matrix.check_service``.
    """
    try:
        check = service_activation_matrix.check_service(service_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return check.model_dump(mode="json")


@router.get("/service-activation-candidates")
async def service_activation_candidates() -> dict:
    """Return services currently `partial` or `pilot` ranked by
    closeness to Live. Useful for the founder's weekly review."""
    try:
        candidates = service_activation_matrix.candidates_for_promotion()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return {
        "count": len(candidates),
        "candidates": [c.model_dump(mode="json") for c in candidates],
    }


@router.get("/tooling")
async def tooling_audit() -> dict:
    """Return the optional-tooling registry with installed/missing flags.

    Wraps ``self_growth_os.tool_registry.audit``. Pure introspection;
    never installs anything.
    """
    rows = tool_registry.audit()
    missing_core = tool_registry.core_required_missing()
    return {
        "tools": [r.model_dump(mode="json") for r in rows],
        "core_required_missing": missing_core,
        "summary": {
            "total": len(rows),
            "installed": sum(1 for r in rows if r.installed),
            "missing": sum(1 for r in rows if not r.installed),
            "missing_required": len(missing_core),
        },
    }


@router.get("/seo/audit/summary")
async def seo_audit_summary() -> dict:
    """Compact view of the SEO audit — easier for dashboards.

    Wraps ``self_growth_os.seo_technical_auditor.summary`` plus the
    advisory-gap histogram.
    """
    try:
        return {
            "summary": seo_technical_auditor.summary(),
            "perimeter_clean": seo_technical_auditor.is_perimeter_clean(),
            "advisory_gap_breakdown": seo_technical_auditor.gap_count(),
        }
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@router.post("/publishing/check")
async def publishing_check(payload: dict = Body(...)) -> dict:
    """Run the safe-publishing gate over a draft string.

    Body: ``{"text": "<the draft to check>", "language": "ar"|"en"|"bilingual"}``
    Returns the typed ``SafePublishingResult`` — never stores the
    text; the caller owns persistence (typically via ApprovalGate).
    """
    text = payload.get("text")
    if not isinstance(text, str) or not text.strip():
        raise HTTPException(
            status_code=400,
            detail="payload.text must be a non-empty string",
        )
    language_raw = str(payload.get("language", "ar")).lower()
    try:
        from auto_client_acquisition.self_growth_os.schemas import Language
        language = Language(language_raw)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail=f"language must be one of ar/en/bilingual; got {language_raw!r}",
        ) from None

    result = safe_publishing_gate.check_text(text, language=language)
    return result.model_dump(mode="json")
