"""Self-Growth OS — read-only endpoints + safe-publishing-gate POST.

Exposes the Service Activation Matrix, SEO audit, tool registry,
and a publishing-gate check. All endpoints are pure reads except
``/publishing/check`` which evaluates a string against the
forbidden-claims regex without storing it.

No external send / charge / scrape paths. No auto-write to DB.
Drafts go to the existing ApprovalGate (Redis) — not handled here.
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, Body, HTTPException

from auto_client_acquisition.self_growth_os import (
    daily_growth_loop,
    geo_aio_radar,
    internal_linking_planner,
    partner_distribution_radar,
    proof_snippet_engine,
    safe_publishing_gate,
    seo_technical_auditor,
    service_activation_matrix,
    tool_registry,
    weekly_growth_scorecard,
)

router = APIRouter(prefix="/api/v1/self-growth", tags=["self-growth"])

REPO_ROOT = Path(__file__).resolve().parents[2]
MATRIX_JSON = REPO_ROOT / "landing" / "assets" / "data" / "service-readiness.json"
SEO_REPORT = REPO_ROOT / "docs" / "SEO_AUDIT_REPORT.json"


def _load_json(path: Path) -> dict:
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                f"{path.name} not generated yet. "
                "Run scripts/export_service_readiness_json.py and "
                "scripts/seo_audit.py."
            ),
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=f"{path.name} is not valid JSON: {exc.msg}",
        ) from exc


@router.get("/status")
async def self_growth_status() -> dict:
    """Summary of what the Self-Growth OS currently exposes.

    This endpoint is the cheapest dashboard probe — it tells callers
    which sub-payloads are available without fetching them.
    """
    return {
        "service_activation_available": MATRIX_JSON.exists(),
        "seo_audit_available": SEO_REPORT.exists(),
        "deferred_phases_doc": "docs/SELF_GROWTH_OS_SCOPE.md",
        "guardrails": {
            "no_live_send": True,
            "no_scraping": True,
            "no_cold_outreach": True,
            "approval_required_for_external_actions": True,
        },
    }


@router.get("/service-activation")
async def get_service_activation_payload() -> dict:
    """Return the Service Activation Matrix exactly as the static
    landing site consumes it.

    Source of truth: ``docs/registry/SERVICE_READINESS_MATRIX.yaml``
    Regenerated by: ``scripts/export_service_readiness_json.py``
    """
    return _load_json(MATRIX_JSON)


@router.get("/seo/audit")
async def seo_audit_report() -> dict:
    """Return the latest technical-SEO audit report.

    Generated by: ``scripts/seo_audit.py``
    """
    return _load_json(SEO_REPORT)


@router.get("/service-activation/{service_id}")
async def service_activation_one(service_id: str) -> dict:
    """Return the typed activation check for one service.

    Wraps ``self_growth_os.service_activation_matrix.check_service``.
    """
    try:
        check = service_activation_matrix.check_service(service_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return check.model_dump(mode="json")


@router.get("/service-activation-candidates")
async def service_activation_candidates() -> dict:
    """Return services currently `partial` or `pilot` ranked by
    closeness to Live. Useful for the founder's weekly review."""
    try:
        candidates = service_activation_matrix.candidates_for_promotion()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return {
        "count": len(candidates),
        "candidates": [c.model_dump(mode="json") for c in candidates],
    }


@router.get("/tooling")
async def tooling_audit() -> dict:
    """Return the optional-tooling registry with installed/missing flags.

    Wraps ``self_growth_os.tool_registry.audit``. Pure introspection;
    never installs anything.
    """
    rows = tool_registry.audit()
    missing_core = tool_registry.core_required_missing()
    return {
        "tools": [r.model_dump(mode="json") for r in rows],
        "core_required_missing": missing_core,
        "summary": {
            "total": len(rows),
            "installed": sum(1 for r in rows if r.installed),
            "missing": sum(1 for r in rows if not r.installed),
            "missing_required": len(missing_core),
        },
    }


@router.get("/seo/audit/summary")
async def seo_audit_summary() -> dict:
    """Compact view of the SEO audit — easier for dashboards.

    Wraps ``self_growth_os.seo_technical_auditor.summary`` plus the
    advisory-gap histogram.
    """
    try:
        return {
            "summary": seo_technical_auditor.summary(),
            "perimeter_clean": seo_technical_auditor.is_perimeter_clean(),
            "advisory_gap_breakdown": seo_technical_auditor.gap_count(),
        }
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@router.get("/geo/audit")
async def geo_audit() -> dict:
    """AI-search readiness audit over our own landing pages.

    Wraps ``self_growth_os.geo_aio_radar.audit_all``. Never calls
    any AI engine; never scrapes any third-party site. Pure
    structural measurement.
    """
    return geo_aio_radar.audit_all()


@router.get("/internal-linking")
async def internal_linking_report() -> dict:
    """Link graph + orphan/CTA/broken-link audit over landing pages.

    Wraps ``self_growth_os.internal_linking_planner.build_graph``.
    """
    return internal_linking_planner.build_graph()


@router.get("/scorecard/weekly")
async def weekly_scorecard() -> dict:
    """Aggregated weekly scorecard. Counts only what's anchored to
    real artifacts in the repo — no fake metrics.

    Wraps ``self_growth_os.weekly_growth_scorecard.build_scorecard``.
    """
    return weekly_growth_scorecard.build_scorecard()


@router.get("/daily-loop")
async def daily_loop() -> dict:
    """Compose the daily growth loop — one screen of what to do today.

    Wraps ``self_growth_os.daily_growth_loop.build_today``. Composes:
    top 3 founder decisions (from personal-operator), service nearest
    to Live (from matrix), today's partner focus (rotating from the
    catalog), top 3 SEO gap pages (from geo_aio_radar), perimeter
    status, and open loops needing founder attention.

    Pure read-only composition. No external send. No DB writes.
    """
    return daily_growth_loop.build_today()


@router.post("/proof-snippet/render")
async def proof_snippet_render(event: dict = Body(...)) -> dict:
    """Render one ProofEvent dict into a typed snippet result.

    Body shape (required fields):
      - event_type: str
      - service_id: str
      - outcome_metric: str
      - outcome_value: any
      - consent_for_publication: bool

    Optional:
      - customer_anonymized, customer_display_name (only used if consent)
      - sla_period_days, service_bundle

    Returns the snippet pair (Arabic + English) plus the decision,
    approval_status, and audience flag. NEVER persists. NEVER sends.
    """
    result = proof_snippet_engine.render(event)
    return result.to_dict()


@router.post("/proof-snippet/render-batch")
async def proof_snippet_render_batch(payload: dict = Body(...)) -> dict:
    """Render many ProofEvents at once. Body: ``{"events": [{...}, ...]}``"""
    events = payload.get("events")
    if not isinstance(events, list):
        raise HTTPException(
            status_code=400,
            detail="payload.events must be a list of ProofEvent dicts",
        )
    return proof_snippet_engine.render_batch(events)


@router.get("/proof-snippet/boundaries")
async def proof_snippet_boundaries() -> dict:
    """Document the proof-snippet engine's safety rules."""
    return proof_snippet_engine.boundaries()


@router.post("/proof-pack/assemble")
async def proof_pack_assemble(payload: dict = Body(...)) -> dict:
    """Assemble many ProofEvents into a customer-shareable pack.

    Body:
      - events: list[ProofEventDict]  (required, non-empty)
      - customer_handle: str          (optional; default 'Saudi B2B customer')
      - period_label: str             (optional; e.g. '2026-05 Pilot')

    Returns a typed ProofPackDocument with bilingual markdown.
    Always ``approval_status=approval_required``. Pack is blocked
    if any event is invalid OR the assembled markdown contains
    forbidden vocabulary at the document level.
    """
    events = payload.get("events")
    if not isinstance(events, list):
        raise HTTPException(
            status_code=400,
            detail="payload.events must be a list of ProofEvent dicts",
        )
    if not events:
        raise HTTPException(
            status_code=400,
            detail="payload.events must be non-empty",
        )
    handle = str(payload.get("customer_handle") or "Saudi B2B customer")
    period = str(payload.get("period_label") or "")
    return proof_snippet_engine.render_pack(
        events, customer_handle=handle, period_label=period
    )


@router.get("/partner-radar")
async def partner_radar_summary() -> dict:
    """Return the static partner-category catalog (8 categories).

    Wraps ``self_growth_os.partner_distribution_radar.summary``. Each
    category is a CLASS of partners (B2B agency, sales consultant,
    CRM implementer, …), not a specific company. Founder picks
    individual partners from their own network. NEVER scrapes any
    directory or social network.
    """
    return partner_distribution_radar.summary()


@router.get("/partner-radar/{category_id}")
async def partner_radar_one(category_id: str) -> dict:
    """Return one partner category with its full draft pack."""
    try:
        return partner_distribution_radar.get_category(category_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@router.get("/partner-radar/drafts/safety-check")
async def partner_radar_safety() -> dict:
    """Run every catalog warm-intro draft through the safe-publishing
    gate. The founder calls this before approving outreach to confirm
    none of the drafts contain forbidden vocabulary.
    """
    return partner_distribution_radar.safe_drafts()


@router.post("/publishing/check")
async def publishing_check(payload: dict = Body(...)) -> dict:
    """Run the safe-publishing gate over a draft string.

    Body: ``{"text": "<the draft to check>", "language": "ar"|"en"|"bilingual"}``
    Returns the typed ``SafePublishingResult`` — never stores the
    text; the caller owns persistence (typically via ApprovalGate).
    """
    text = payload.get("text")
    if not isinstance(text, str) or not text.strip():
        raise HTTPException(
            status_code=400,
            detail="payload.text must be a non-empty string",
        )
    language_raw = str(payload.get("language", "ar")).lower()
    try:
        from auto_client_acquisition.self_growth_os.schemas import Language
        language = Language(language_raw)
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail=f"language must be one of ar/en/bilingual; got {language_raw!r}",
        ) from None

    result = safe_publishing_gate.check_text(text, language=language)
    return result.model_dump(mode="json")
