"""Read-only access to the SEO audit report.

Wraps ``docs/SEO_AUDIT_REPORT.json`` (generated by
``scripts/seo_audit.py``). This module never modifies pages; it
just surfaces audit findings in a typed shape for the API and
other modules.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = REPO_ROOT / "docs" / "SEO_AUDIT_REPORT.json"


def load_report() -> dict:
    if not REPORT_PATH.exists():
        raise FileNotFoundError(
            f"SEO audit report not found at {REPORT_PATH}. "
            "Run `python scripts/seo_audit.py` first."
        )
    return json.loads(REPORT_PATH.read_text(encoding="utf-8"))


def summary() -> dict[str, int]:
    """Return ``{total_pages, pages_with_required_gap, pages_with_advisory_gap}``."""
    return dict(load_report().get("summary") or {})


def pages_with_required_gaps() -> list[dict]:
    """Pages still missing a required tag (title, meta description,
    viewport, html lang, html dir). The CI gate fails if this is
    non-empty, so this list should normally be ``[]``."""
    return [p for p in load_report().get("pages") or [] if p.get("missing_required")]


def pages_with_advisory_gaps() -> list[dict]:
    """Pages missing canonical / Open Graph / twitter:card. These are
    pinned to the per-file allowlist in ``tests/test_seo_audit.py``
    and shrink as the founder approves OG copy."""
    return [p for p in load_report().get("pages") or [] if p.get("missing_advisory")]


def gap_count() -> dict[str, int]:
    """Histogram of which advisory checks fail most often. Useful for
    deciding which one batch of OG copy to author next."""
    counter: dict[str, int] = {}
    for page in load_report().get("pages") or []:
        for adv in page.get("missing_advisory") or []:
            counter[adv] = counter.get(adv, 0) + 1
    return dict(sorted(counter.items(), key=lambda x: -x[1]))


def is_perimeter_clean() -> bool:
    """True iff there are zero required gaps (the CI invariant)."""
    return summary().get("pages_with_required_gap", 0) == 0
