"""Emit the PUBLIC website catalog from seeds.

Outputs:
  - src/marketing/catalog.ts   (TypeScript data consumed by React pages)
  - data/site/site_routes.yaml (route manifest used by check_site_routes.py)

Public exposure rule (enforced here): the website shows ONLY the 5 core
systems and the 20 sector solutions. The 40 internal systems and the internal
routing are NEVER written to the public catalog.
"""
from __future__ import annotations

import json
import sys

from . import seeds
from .lib import dump_yaml, write_text


def build_ts():
    cores = []
    for c in seeds.CORE_SYSTEMS:
        cores.append(
            {
                "id": c["id"],
                "nameAr": c["name_ar"],
                "nameEn": c["name_en"],
                "promiseAr": c["promise_ar"],
                "outcomeAr": c["outcome_ar"],
            }
        )

    smap = seeds.sector_need_map()
    sectors = []
    for sid, sector_ar in seeds.SECTORS:
        # public-safe: expose the need names + the CORE system only (no internal systems)
        needs = []
        cores_for_sector = []
        for need_id in smap[sid]:
            need = seeds.need_by_id(need_id)
            # public-safe: expose which CORE system addresses the need (1 of 5),
            # never the internal specialized system.
            needs.append({"id": need["id"], "nameAr": need["name_ar"], "coreSystem": need["core_system"]})
            if need["core_system"] not in cores_for_sector:
                cores_for_sector.append(need["core_system"])
        sectors.append(
            {
                "id": sid,
                "nameAr": sector_ar,
                "needs": needs,
                "coreSystems": cores_for_sector,
            }
        )

    header = (
        "// AUTO-GENERATED by scripts/dealix/generate_site_catalog.py — do not edit by hand.\n"
        "// Public catalog only: 5 core systems + 20 sector solutions.\n"
        "// The 40 internal systems and routing are intentionally NOT exposed here.\n\n"
        "export interface CoreSystem { id: string; nameAr: string; nameEn: string; promiseAr: string; outcomeAr: string; }\n"
        "export interface SectorNeed { id: string; nameAr: string; coreSystem: string; }\n"
        "export interface SectorSolution { id: string; nameAr: string; needs: SectorNeed[]; coreSystems: string[]; }\n\n"
    )
    body = (
        "export const coreSystems: CoreSystem[] = "
        + json.dumps(cores, ensure_ascii=False, indent=2)
        + ";\n\n"
        + "export const sectorSolutions: SectorSolution[] = "
        + json.dumps(sectors, ensure_ascii=False, indent=2)
        + ";\n"
    )
    write_text("src/marketing/catalog.ts", header + body)
    return cores, sectors


def build_routes_manifest(cores, sectors):
    routes = ["/", "/systems", "/solutions", "/pricing", "/diagnostic"]
    for c in cores:
        routes.append(f"/systems/{c['id']}")
    for s in sectors:
        routes.append(f"/solutions/{s['id']}")
    dump_yaml(
        "data/site/site_routes.yaml",
        {
            "router": "react-router (SPA)",
            "public_routes": routes,
            "notes": "Generated from seeds; the SPA renders /systems/:slug and /solutions/:sector dynamically.",
        },
    )
    return routes


def main():
    cores, sectors = build_ts()
    routes = build_routes_manifest(cores, sectors)
    print(f"Public site catalog generated: {len(cores)} core systems, {len(sectors)} sectors, {len(routes)} routes.")
    print("  -> src/marketing/catalog.ts")
    print("  -> data/site/site_routes.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
