"""Shared helpers for the Dealix engine: paths, IO, and a dependency-free
JSON-Schema (subset) validator so checks run with zero external deps.

The validator supports the subset used by Dealix schemas:
  type, properties, required, items, enum, minimum, maximum,
  minItems, maxItems, minLength, additionalProperties (bool), const.
If the `jsonschema` package is installed it is used instead (CI installs it),
otherwise we fall back to the built-in validator below.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

try:  # pyyaml is available locally and in CI
    import yaml
except Exception:  # pragma: no cover
    yaml = None

ROOT = Path(__file__).resolve().parents[2]


# --------------------------------------------------------------------------- IO
def load_yaml(path):
    p = ROOT / path if not os.path.isabs(str(path)) else Path(path)
    if yaml is None:
        raise RuntimeError("pyyaml is required to read %s" % p)
    with open(p, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def dump_yaml(path, data):
    p = ROOT / path if not os.path.isabs(str(path)) else Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write("# Generated by the Dealix engine. Source of truth: scripts/dealix/seeds.py\n")
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, width=100)


def load_json(path):
    p = ROOT / path if not os.path.isabs(str(path)) else Path(path)
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def load_jsonl(path):
    p = ROOT / path if not os.path.isabs(str(path)) else Path(path)
    rows = []
    with open(p, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def dump_jsonl(path, rows):
    p = ROOT / path if not os.path.isabs(str(path)) else Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_text(path, text):
    p = ROOT / path if not os.path.isabs(str(path)) else Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(text)


# --------------------------------------------------------------- schema validate
def validate(instance, schema, path="$"):
    """Return a list of human-readable error strings (empty == valid)."""
    # Prefer the real library when present (CI installs jsonschema).
    try:
        import jsonschema  # type: ignore

        v = jsonschema.Draft7Validator(schema)
        return [f"{'/'.join(str(p) for p in e.path) or '$'}: {e.message}" for e in v.iter_errors(instance)]
    except Exception:
        return _validate(instance, schema, path)


def _validate(instance, schema, path):
    errors = []
    t = schema.get("type")
    if t:
        if not _type_ok(instance, t):
            errors.append(f"{path}: expected type {t}, got {type(instance).__name__}")
            return errors  # type mismatch -> stop deeper checks here
    if "const" in schema and instance != schema["const"]:
        errors.append(f"{path}: expected const {schema['const']!r}")
    if "enum" in schema and instance not in schema["enum"]:
        errors.append(f"{path}: {instance!r} not in enum {schema['enum']}")
    if isinstance(instance, dict):
        for req in schema.get("required", []):
            if req not in instance:
                errors.append(f"{path}: missing required property '{req}'")
        props = schema.get("properties", {})
        for key, subschema in props.items():
            if key in instance:
                errors += _validate(instance[key], subschema, f"{path}.{key}")
        if schema.get("additionalProperties") is False:
            extra = set(instance) - set(props)
            if extra:
                errors.append(f"{path}: unexpected properties {sorted(extra)}")
    if isinstance(instance, list):
        if "minItems" in schema and len(instance) < schema["minItems"]:
            errors.append(f"{path}: expected >= {schema['minItems']} items, got {len(instance)}")
        if "maxItems" in schema and len(instance) > schema["maxItems"]:
            errors.append(f"{path}: expected <= {schema['maxItems']} items, got {len(instance)}")
        item_schema = schema.get("items")
        if item_schema:
            for i, item in enumerate(instance):
                errors += _validate(item, item_schema, f"{path}[{i}]")
    if isinstance(instance, str):
        if "minLength" in schema and len(instance) < schema["minLength"]:
            errors.append(f"{path}: string shorter than {schema['minLength']}")
    if isinstance(instance, (int, float)) and not isinstance(instance, bool):
        if "minimum" in schema and instance < schema["minimum"]:
            errors.append(f"{path}: {instance} < minimum {schema['minimum']}")
        if "maximum" in schema and instance > schema["maximum"]:
            errors.append(f"{path}: {instance} > maximum {schema['maximum']}")
    return errors


def _type_ok(instance, t):
    types = t if isinstance(t, list) else [t]
    for tt in types:
        if tt == "object" and isinstance(instance, dict):
            return True
        if tt == "array" and isinstance(instance, list):
            return True
        if tt == "string" and isinstance(instance, str):
            return True
        if tt == "integer" and isinstance(instance, int) and not isinstance(instance, bool):
            return True
        if tt == "number" and isinstance(instance, (int, float)) and not isinstance(instance, bool):
            return True
        if tt == "boolean" and isinstance(instance, bool):
            return True
        if tt == "null" and instance is None:
            return True
    return False


# ------------------------------------------------------------------- reporting
class CheckResult:
    """Collects pass/fail lines for a single check script."""

    def __init__(self, name):
        self.name = name
        self.errors = []
        self.notes = []

    def fail(self, msg):
        self.errors.append(msg)

    def ok(self, msg):
        self.notes.append(msg)

    def finish(self):
        print(f"=== {self.name} ===")
        for note in self.notes:
            print(f"  ok   {note}")
        for err in self.errors:
            print(f"  FAIL {err}")
        if self.errors:
            print(f"RESULT: FAIL ({len(self.errors)} issue(s))")
            raise SystemExit(1)
        print("RESULT: PASS")
        return 0
