// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function ContactPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">تواصل</h1>
      <p className="mt-2 text-muted-foreground">تواصل معنا عبر القنوات الرسمية.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>نموذج تواصل</li>
      </ul>
    </main>
  )
}
