// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function DiagnosticPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">التشخيص</h1>
      <p className="mt-2 text-muted-foreground">اكتشف احتياجك الأساسي.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>اختر قطاعك</li>
        <li>أجب عن 3 أسئلة</li>
        <li>احصل على نظام مقترح</li>
      </ul>
    </main>
  )
}
