// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function ExecutiveCommandOsPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">نظام القيادة التنفيذية</h1>
      <p className="mt-2 text-muted-foreground">القائد لا يرى الأرقام يوميًا، والقرارات تتأخر بسبب تشتت البيانات.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>لوحة قيادة يومية (إيراد، فرص، متابعات)</li>
        <li>تقرير قيمة أسبوعي للقيادة</li>
        <li>بوابات قرار (decision gates) واضحة</li>
        <li>تنبيهات على المؤشرات الحرجة</li>
      </ul>
    </main>
  )
}
