// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function FollowUpRecoveryOsPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">نظام استعادة المتابعات</h1>
      <p className="mt-2 text-muted-foreground">المتابعات بطيئة والعملاء المهتمون يضيعون بلا رد في الوقت المناسب.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>تسلسلات متابعة مؤتمتة</li>
        <li>حملة استرجاع للعملاء الخاملين</li>
        <li>قواعد توقيت وتذكير</li>
        <li>قائمة أولوية يومية للمتابعة</li>
      </ul>
    </main>
  )
}
