// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function PricingPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">الأسعار</h1>
      <p className="mt-2 text-muted-foreground">تسعير افتتاحي شفّاف.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>نظام تشغيل الإيرادات: 7500 SAR</li>
        <li>نظام القيادة التنفيذية: 9000 SAR</li>
        <li>نظام استعادة المتابعات: 6000 SAR</li>
        <li>نظام عملاء واتساب: 5500 SAR</li>
        <li>نظام العروض والإثبات: 6500 SAR</li>
      </ul>
    </main>
  )
}
