// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function ProposalProofOsPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">نظام العروض والإثبات</h1>
      <p className="mt-2 text-muted-foreground">إعداد العروض بطيء، والتسعير غير واضح، وإثبات النتائج للعميل ضعيف.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>قوالب عروض مصغّرة سريعة</li>
        <li>بنك تسعير واضح</li>
        <li>تقارير إثبات نتائج</li>
        <li>بوابة اعتماد قبل الإرسال</li>
      </ul>
    </main>
  )
}
