// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function RevenueOperatingSystemPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">نظام تشغيل الإيرادات</h1>
      <p className="mt-2 text-muted-foreground">لا توجد عملية مبيعات موحدة؛ الفرص تتسرب وخط الأنابيب غير واضح.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>خريطة عملية بيع من أول تواصل حتى الإغلاق</li>
        <li>نموذج تأهيل (qualification) موحد</li>
        <li>قوالب متابعة ورسائل جاهزة</li>
        <li>لوحة خط أنابيب أسبوعية</li>
      </ul>
    </main>
  )
}
