// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function SolutionRealEstatePage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">حلول العقارات</h1>
      <p className="mt-2 text-muted-foreground">آلام القطاع والأنظمة المناسبة.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>بطء متابعة العملاء المهتمين</li>
        <li>تسرّب الصفقات قبل الإغلاق</li>
        <li>ضعف استرجاع العملاء الخاملين</li>
        <li>طول دورة البيع</li>
      </ul>
    </main>
  )
}
