// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function SolutionRecruitmentPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">حلول التوظيف</h1>
      <p className="mt-2 text-muted-foreground">آلام القطاع والأنظمة المناسبة.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>ضعف توليد العملاء المحتملين</li>
        <li>ضعف تأهيل العملاء</li>
        <li>طول دورة البيع</li>
        <li>ضعف إدارة الاعتراضات</li>
      </ul>
    </main>
  )
}
