// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function SolutionProfessionalServicesPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">حلول الخدمات الاحترافية</h1>
      <p className="mt-2 text-muted-foreground">آلام القطاع والأنظمة المناسبة.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>ضعف معدل تحويل العروض</li>
        <li>بطء إعداد العروض</li>
        <li>ضعف إثبات النتائج للعميل</li>
        <li>عدم وجود تسعير واضح</li>
      </ul>
    </main>
  )
}
