// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function SolutionMarketingAgenciesPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">حلول وكالات التسويق</h1>
      <p className="mt-2 text-muted-foreground">آلام القطاع والأنظمة المناسبة.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>ضعف توليد العملاء المحتملين</li>
        <li>ضعف معدل تحويل العروض</li>
        <li>عدم وضوح خط أنابيب المبيعات</li>
        <li>ضعف إثبات النتائج للعميل</li>
      </ul>
    </main>
  )
}
