// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function SolutionsIndexPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">الحلول حسب القطاع</h1>
      <p className="mt-2 text-muted-foreground">حلول لكل قطاع.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>وكالات التسويق</li>
        <li>شركات التدريب</li>
        <li>العيادات</li>
        <li>العقارات</li>
        <li>الخدمات الاحترافية</li>
        <li>التوظيف</li>
        <li>البرمجيات (SaaS)</li>
        <li>اللوجستيات</li>
      </ul>
    </main>
  )
}
