// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function StartPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">ابدأ</h1>
      <p className="mt-2 text-muted-foreground">ابدأ سبرنت افتتاحي.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>اطلب عرضًا مصغّرًا</li>
      </ul>
    </main>
  )
}
