// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function SystemsIndexPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">الأنظمة</h1>
      <p className="mt-2 text-muted-foreground">الأنظمة الخمسة الأساسية.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>نظام تشغيل الإيرادات</li>
        <li>نظام القيادة التنفيذية</li>
        <li>نظام استعادة المتابعات</li>
        <li>نظام عملاء واتساب</li>
        <li>نظام العروض والإثبات</li>
      </ul>
    </main>
  )
}
