// AUTO-GENERATED by scripts/launch/build.py — Dealix site route.
export default function WhatsappClientOsPage() {
  return (
    <main dir="rtl" className="mx-auto max-w-3xl p-8">
      <h1 className="text-3xl font-bold">نظام عملاء واتساب</h1>
      <p className="mt-2 text-muted-foreground">قناة واتساب فوضوية: ردود متأخرة وطلبات غير موثقة وتجربة حجز ضعيفة.</p>
      <ul className="mt-6 list-disc pr-6 space-y-1">
        <li>هيكلة قناة واتساب وتصنيف المحادثات</li>
        <li>قوالب رد سريعة موثّقة</li>
        <li>مسار حجز/طلب واضح</li>
        <li>سجل طلبات موثّق</li>
      </ul>
    </main>
  )
}
