#!/usr/bin/env python3
"""Dealix Diagnostic generator — bilingual brief in 30 seconds.

When a warm intro lands, the founder runs this script with the
prospect's basic info and gets a complete bilingual Diagnostic brief
ready to send (after manual review). Pure local generation —
NO LLM call, NO live send, NO scraping. Just structured composition
over the YAML matrix + the existing Self-Growth OS scorecard.

Usage:
    python scripts/dealix_diagnostic.py \\
        --company "ACME Saudi Co." \\
        --sector b2b_services \\
        --region riyadh \\
        --pipeline-state "WhatsApp incoming, no qualification, founder responds at night"

    # Show the bundle catalog instead of running a Diagnostic:
    python scripts/dealix_diagnostic.py --list-bundles

The output is markdown, ready to paste into Notion/email/WhatsApp
(after the founder's manual approval).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

import yaml  # noqa: E402


YAML_PATH = REPO_ROOT / "docs" / "registry" / "SERVICE_READINESS_MATRIX.yaml"


# Sector → recommended starting bundle. Keep this list short and
# explicit; if the founder wants more sectors, add them via PR.
_SECTOR_DEFAULTS: dict[str, str] = {
    "b2b_services": "growth_starter",
    "b2b_saas": "growth_starter",
    "agency": "partnership_growth",
    "training_consulting": "growth_starter",
    "local_services": "growth_starter",
    "ecommerce_b2c": "growth_starter",
    "real_estate": "growth_starter",
    "healthcare_clinic": "growth_starter",
}


def _load_matrix() -> dict[str, Any]:
    with YAML_PATH.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _bundle(matrix: dict[str, Any], bundle_id: str) -> dict[str, Any] | None:
    for b in matrix.get("bundles") or []:
        if b.get("id") == bundle_id:
            return b
    return None


def _services_in_bundle(matrix: dict[str, Any], bundle_id: str) -> list[dict[str, Any]]:
    return [
        s for s in matrix.get("services") or []
        if s.get("bundle") == bundle_id
    ]


def _recommended_bundle(sector: str) -> str:
    return _SECTOR_DEFAULTS.get(sector, "growth_starter")


# ─────────────────────── markdown rendering ────────────────────────


def render_markdown(
    *,
    company: str,
    sector: str,
    region: str,
    pipeline_state: str,
    matrix: dict[str, Any],
) -> str:
    bundle_id = _recommended_bundle(sector)
    bundle = _bundle(matrix, bundle_id) or {}
    services = _services_in_bundle(matrix, bundle_id)

    today = date.today().isoformat()
    bundle_ar = bundle.get("name_ar", bundle_id)
    bundle_en = bundle.get("name_en", bundle_id)
    summary_ar = bundle.get("summary_ar", "")
    summary_en = bundle.get("summary_en", "")

    md: list[str] = []

    # ── Header ──
    md.append(f"# Diagnostic — {company}")
    md.append("")
    md.append(f"> **Date:** {today}  \\")
    md.append(f"> **Sector:** `{sector}`  \\")
    md.append(f"> **Region:** `{region}`  \\")
    md.append("> **Generated by:** Dealix Diagnostic CLI (manual review required before send)")
    md.append("")
    md.append("---")
    md.append("")

    # ── Section: Arabic primary ──
    md.append("## القراءة السريعة (عربي)")
    md.append("")
    md.append(f"**الشركة:** {company}")
    md.append(f"**القطاع:** {sector} — {region}")
    md.append("")
    md.append("**الوضع الحاليّ كما وصفتم:**")
    md.append(f"> {pipeline_state}")
    md.append("")
    md.append("**التشخيص الأوّليّ — الفجوات الأكثر أهميّة:**")
    md.append(f"1. لا يوجد مسار واضح للاستقبال + التأهيل + الردّ خلال SLA محدّد.")
    md.append(f"2. الردّ يعتمد على المؤسس، ممّا يخلق عنق زجاجة بعد ساعات الذروة.")
    md.append(f"3. لا توجد أدلّة مكتوبة (Proof Pack) لإقناع العميل التالي.")
    md.append("")
    md.append(f"**التوصية:** ابدؤوا بـ **{bundle_ar}** ({bundle_id}).")
    if summary_ar:
        md.append(f"> {summary_ar}")
    md.append("")
    md.append("**ما يشمله الـ Pilot 7 أيّام (499 ريال):**")
    for s in services[:7]:
        sid = s.get("service_id", "?")
        name_ar = s.get("name_ar", sid)
        sla = s.get("sla", "—")
        md.append(f"- `{sid}` — {name_ar} (SLA: {sla})")
    md.append("")
    md.append("**ما لن نفعله (سياسة Dealix الثابتة):**")
    md.append("- ❌ لا cold WhatsApp ولا cold email — موافقة العميل شرط.")
    md.append("- ❌ لا scraping ولا قوائم مشتراة.")
    md.append("- ❌ لا ضمانات أرقام/ترتيب — التزام بالعمل والـ Proof Pack.")
    md.append("- ❌ لا خصم آليّ — الدفع عبر Moyasar test mode بإشرافكم.")
    md.append("")
    md.append("**معايير النجاح في 7 أيّام:**")
    md.append("- 10 فرص مؤهَّلة جاهزة للمتابعة.")
    md.append("- مسوّدات عربيّة للعشر فرص (مع موافقتكم قبل الإرسال).")
    md.append("- خطّة متابعة 72 ساعة لكلّ فرصة.")
    md.append("- Proof Pack موقَّع يوضّح ما حدث.")
    md.append("")
    md.append("**التسعير:**")
    md.append("- **Pilot 7 أيّام:** 499 ريال (سعر تعريفيّ ثابت حتى العميل #5).")
    md.append("- **بعد الـ Pilot:** Executive Growth OS — 2,999 ريال/شهر (اختياريّ، لا التزام).")
    md.append("")
    md.append("**القرار المطلوب:**")
    md.append("☐ مهتمّون — أرسلوا فاتورة Pilot.")
    md.append("☐ نحتاج جلسة 30 دقيقة قبل القرار.")
    md.append("☐ غير مهتمّ الآن — أعيدوا التواصل بعد 90 يوم.")
    md.append("")
    md.append("---")
    md.append("")

    # ── Section: English secondary ──
    md.append("## Executive summary (English)")
    md.append("")
    md.append(f"**Company:** {company}")
    md.append(f"**Sector / region:** {sector} / {region}")
    md.append("")
    md.append("**Current state (as described):**")
    md.append(f"> {pipeline_state}")
    md.append("")
    md.append("**Initial assessment — top three gaps:**")
    md.append(f"1. No structured inbound → qualification → reply pipeline with explicit SLAs.")
    md.append(f"2. Reply path depends on the founder, creating a bottleneck after peak hours.")
    md.append(f"3. No written Proof Pack to convince the next prospect.")
    md.append("")
    md.append(f"**Recommended starting bundle:** **{bundle_en}** (`{bundle_id}`).")
    if summary_en:
        md.append(f"> {summary_en}")
    md.append("")
    md.append("**Pilot 7 days, 499 SAR — included:**")
    for s in services[:7]:
        sid = s.get("service_id", "?")
        name_en = s.get("name_en", sid)
        sla = s.get("sla", "—")
        md.append(f"- `{sid}` — {name_en} (SLA: {sla})")
    md.append("")
    md.append("**What we will NOT do (hard policy):**")
    md.append("- ❌ No cold WhatsApp / cold email — explicit consent required.")
    md.append("- ❌ No scraping or purchased lists.")
    md.append("- ❌ No revenue / ranking guarantees — only the work + Proof Pack.")
    md.append("- ❌ No auto-charge — Moyasar test-mode invoice, founder-supervised.")
    md.append("")
    md.append("**Success criteria in 7 days:**")
    md.append("- 10 qualified opportunities ready for follow-up.")
    md.append("- Arabic drafts for all 10 (your approval required before any send).")
    md.append("- 72-hour follow-up plan per opportunity.")
    md.append("- Signed Proof Pack documenting outcomes.")
    md.append("")
    md.append("**Pricing:**")
    md.append("- **Pilot 7 days:** 499 SAR (locked introductory price until customer #5).")
    md.append("- **Post-pilot:** Executive Growth OS — 2,999 SAR/month (opt-in, no commitment).")
    md.append("")
    md.append("**Decision options:**")
    md.append("☐ Interested — send the Pilot invoice.")
    md.append("☐ Need a 30-min call first.")
    md.append("☐ Not now — re-engage in 90 days.")
    md.append("")
    md.append("---")
    md.append("")
    md.append("> ⚠️ **Founder review required before sending.** This brief is a")
    md.append("> machine-composed draft from the YAML service matrix. Read,")
    md.append("> adjust, then approve manually.")
    return "\n".join(md)


def list_bundles(matrix: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("Available bundles:")
    for b in matrix.get("bundles") or []:
        bid = b.get("id", "?")
        name_ar = b.get("name_ar", "")
        name_en = b.get("name_en", "")
        cust = "customer-facing" if b.get("customer_facing") else "internal"
        lines.append(f"  • {bid:<22}  {name_en:<35}  {name_ar}  [{cust}]")
    lines.append("")
    lines.append("Sector → bundle defaults:")
    for sector, bundle in sorted(_SECTOR_DEFAULTS.items()):
        lines.append(f"  • {sector:<22}  →  {bundle}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate a bilingual Diagnostic brief for a warm intro.",
    )
    p.add_argument("--company", help="prospect company name")
    p.add_argument(
        "--sector",
        default="b2b_services",
        help=f"one of: {', '.join(sorted(_SECTOR_DEFAULTS.keys()))}",
    )
    p.add_argument("--region", default="ksa", help="prospect region (e.g. riyadh, jeddah, dammam, ksa)")
    p.add_argument(
        "--pipeline-state",
        default="(unknown — fill in after the discovery call)",
        help="one-line description of the prospect's current pipeline state",
    )
    p.add_argument("--list-bundles", action="store_true",
                   help="list bundles and sector defaults, then exit")
    p.add_argument("--json", action="store_true",
                   help="emit JSON metadata instead of markdown")
    args = p.parse_args(argv)

    matrix = _load_matrix()

    if args.list_bundles:
        print(list_bundles(matrix))
        return 0

    if not args.company:
        p.error("--company is required (or pass --list-bundles)")

    if args.json:
        bundle_id = _recommended_bundle(args.sector)
        payload = {
            "schema_version": 1,
            "generated_at": datetime.now(UTC).isoformat(),
            "company": args.company,
            "sector": args.sector,
            "region": args.region,
            "pipeline_state": args.pipeline_state,
            "recommended_bundle": bundle_id,
            "services_in_bundle": [
                s.get("service_id") for s in _services_in_bundle(matrix, bundle_id)
            ],
            "approval_status": "approval_required",
            "guardrails": {
                "no_live_send": True,
                "no_scraping": True,
                "no_cold_outreach": True,
                "no_revenue_guarantee": True,
                "manual_review_before_send": True,
            },
        }
        print(json.dumps(payload, indent=2, ensure_ascii=False))
        return 0

    print(render_markdown(
        company=args.company,
        sector=args.sector,
        region=args.region,
        pipeline_state=args.pipeline_state,
        matrix=matrix,
    ))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
