Write-Host "Dealix Next Commands" -ForegroundColor Cyan
Write-Host ""
Write-Host "1) Doctor:"
Write-Host "   .\scripts\dealix-doctor.ps1"
Write-Host ""
Write-Host "2) See services:"
Write-Host "   .\scripts\dealix.ps1 services"
Write-Host ""
Write-Host "3) Assess a problem:"
Write-Host "   .\scripts\dealix.ps1 assess `"عندنا بيانات عملاء مبعثرة ومبيعات غير مرتبة`""
Write-Host ""
Write-Host "4) Create a client:"
Write-Host "   .\scripts\dealix.ps1 new-client acme --name `"ACME Saudi`" --sector `"B2B Services`""
Write-Host ""
Write-Host "5) Generate proposal:"
Write-Host "   .\scripts\dealix.ps1 offer --client `"ACME Saudi`" --service lead-intelligence --problem `"leads are messy`""
Write-Host ""
Write-Host "6) Generate proof pack:"
Write-Host "   .\scripts\dealix.ps1 proof-pack --client `"ACME Saudi`" --service lead-intelligence --value-type Revenue --metric `"qualified accounts ranked`" --baseline unknown --result `"top 50 accounts ranked`" --evidence `"proof report`" --next-value `"Pilot Conversion Sprint`""
Write-Host ""
Write-Host "7) Start Aider safely:"
Write-Host "   .\scripts\dealix-aider-v5.ps1"