#!/usr/bin/env python3
"""
Generate Dealix acquisition + outreach reports from data/acquisition/*.jsonl.

Outputs:
  reports/acquisition/DAILY_COMPANY_INTELLIGENCE_PACKS.md
  reports/acquisition/CALL_FOLLOWUP_QUEUE.md
  reports/acquisition/MINI_PROPOSAL_QUEUE.md
  reports/acquisition/EMAIL_TO_CALL_HANDOFF_QUEUE.md
  reports/acquisition/FOLLOW_UP_SEQUENCE_QUEUE.md
  reports/acquisition/OBJECTION_REVIEW.md
  reports/outreach/DAILY_400_SYSTEM_DRAFT_PRODUCTION.md
  reports/outreach/TOP_100_SYSTEM_APPROVAL_QUEUE.md
  reports/outreach/SYSTEM_BASED_CLIENT_NEED_CARDS.md
  reports/outreach/SYSTEM_EMAIL_DRAFTS_REVIEW.md

Reports are reproducible: re-run any time after data changes.
Run: python3 scripts/generate_acquisition_reports.py
"""

from collections import Counter

from dealix_common import (
    SYSTEM_SHORT, TOP_QUALITY_THRESHOLD, load_jsonl, md_cell, now_ast, write_report,
)

DAILY_DRAFT_CAPACITY = 400
FOOTER = "\n---\n*Auto-generated by Dealix Acquisition Reports — sending stays behind founder approval. Re-run: `python3 scripts/generate_acquisition_reports.py`*\n"


def by_system(rows):
    c = Counter(r.get("recommended_system") for r in rows)
    return c


def main():
    print("Generating acquisition + outreach reports ...")
    packs = load_jsonl("data/acquisition/company_intelligence_packs.jsonl")
    cards = load_jsonl("data/acquisition/client_need_cards.jsonl")
    briefs = load_jsonl("data/acquisition/call_briefs.jsonl")
    proposals = load_jsonl("data/acquisition/mini_proposals.jsonl")
    sequences = load_jsonl("data/acquisition/follow_up_sequences.jsonl")
    objections = load_jsonl("data/acquisition/objection_responses.jsonl")
    ts = now_ast()

    # ---------------- DAILY_COMPANY_INTELLIGENCE_PACKS ----------------
    sys_counts = by_system(packs)
    ev_counts = Counter(p.get("evidence_level") for p in packs)
    lines = [f"# Daily Company Intelligence Packs", f"Generated: {ts} AST", "",
             f"إجمالي الحزم المُجهّزة: **{len(packs)}**", "",
             "## التوزيع حسب النظام", "", "| System | Packs |", "|---|---:|"]
    for s, label in SYSTEM_SHORT.items():
        lines.append(f"| {label} | {sys_counts.get(s, 0)} |")
    lines += ["", "## التوزيع حسب مستوى الدليل", "", "| Evidence | Packs |", "|---|---:|"]
    for ev in ["L0", "L1", "L2", "L3", "L4"]:
        lines.append(f"| {ev} | {ev_counts.get(ev, 0)} |")
    lines += ["", "## الحزم", "", "| ID | Company | Sector | System | Pain (likely) | Evidence | Quality | Status |",
              "|---|---|---|---|---|---|---:|---|"]
    for p in packs:
        q = (p.get("draft_quality") or {}).get("total", "")
        lines.append("| {id} | {co} | {sec} | {sys} | {pain} | {ev} | {q} | {st} |".format(
            id=md_cell(p.get("id")), co=md_cell(p.get("company")), sec=md_cell(p.get("sector")),
            sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"), p.get("recommended_system"))),
            pain=md_cell(p.get("likely_pain"))[:60], ev=md_cell(p.get("evidence_level")),
            q=q, st=md_cell(p.get("status"))))
    lines.append(FOOTER)
    write_report("acquisition/DAILY_COMPANY_INTELLIGENCE_PACKS.md", "\n".join(lines))

    # ---------------- CALL_FOLLOWUP_QUEUE ----------------
    lines = [f"# Call Follow-up Queue", f"Generated: {ts} AST", "",
             "قائمة اتصال جاهزة لمتصل بشري (لا اتصال آلي). كل Call Brief مشتق من إيميل مُرسل.", "",
             f"إجمالي Call Briefs: **{len(briefs)}**", "",
             "| ID | Company | Role | System | Objective | Opening line | Next step | Owner | Status |",
             "|---|---|---|---|---|---|---|---|---|"]
    for b in briefs:
        lines.append("| {id} | {co} | {role} | {sys} | {obj} | {open} | {next} | {own} | {st} |".format(
            id=md_cell(b.get("id")), co=md_cell(b.get("company")), role=md_cell(b.get("contact_role")),
            sys=md_cell(SYSTEM_SHORT.get(b.get("recommended_system"))), obj=md_cell(b.get("call_objective"))[:40],
            open=md_cell(b.get("opening_line"))[:50], next=md_cell(b.get("next_step"))[:40],
            own=md_cell(b.get("owner")), st=md_cell(b.get("status"))))
    lines.append(FOOTER)
    write_report("acquisition/CALL_FOLLOWUP_QUEUE.md", "\n".join(lines))

    # ---------------- MINI_PROPOSAL_QUEUE ----------------
    pending = [p for p in proposals if p.get("status") in ("draft", "pending_approval")]
    lines = [f"# Mini Proposal Queue", f"Generated: {ts} AST", "",
             "**كل Mini Proposal يتطلب موافقة founder قبل الإرسال.**", "",
             f"إجمالي: **{len(proposals)}** | بانتظار موافقة/مسودة: **{len(pending)}**", "",
             "| ID | Company | System | Title | Deliverables | Starter price | Status | Approval |",
             "|---|---|---|---|---|---|---|---|"]
    for p in proposals:
        sp = (p.get("starter_price") or {}).get("display", "")
        dels = "، ".join(p.get("deliverables", []))
        lines.append("| {id} | {co} | {sys} | {t} | {d} | {sp} | {st} | {ap} |".format(
            id=md_cell(p.get("id")), co=md_cell(p.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))), t=md_cell(p.get("title")),
            d=md_cell(dels)[:60], sp=md_cell(sp), st=md_cell(p.get("status")),
            ap="مطلوبة" if p.get("approval_required") else "—"))
    lines.append(FOOTER)
    write_report("acquisition/MINI_PROPOSAL_QUEUE.md", "\n".join(lines))

    # ---------------- EMAIL_TO_CALL_HANDOFF_QUEUE ----------------
    brief_companies = {b.get("company") for b in briefs}
    lines = [f"# Email → Call Handoff Queue", f"Generated: {ts} AST", "",
             "القاعدة: كل إيميل مُرسل يجب أن يُنتج follow_up_due_date + call_brief + next_action + owner.", "",
             "| Company | System | Pack status | Has call brief? | Next action | Owner |",
             "|---|---|---|---|---|---|"]
    for p in packs:
        has_brief = "نعم" if p.get("company") in brief_companies else "لا — يلزم تجهيز Call Brief"
        lines.append("| {co} | {sys} | {st} | {hb} | {na} | {own} |".format(
            co=md_cell(p.get("company")), sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))),
            st=md_cell(p.get("status")), hb=has_brief, na=md_cell(p.get("next_action"))[:45],
            own=md_cell(p.get("owner"))))
    lines.append(FOOTER)
    write_report("acquisition/EMAIL_TO_CALL_HANDOFF_QUEUE.md", "\n".join(lines))

    # ---------------- FOLLOW_UP_SEQUENCE_QUEUE ----------------
    lines = [f"# Follow-up Sequence Queue", f"Generated: {ts} AST", "",
             "تسلسلات متابعة (مسودات تبقى خلف موافقة founder). cadence افتراضي [3,7,14] أيام، حد أقصى 3.", "",
             f"إجمالي التسلسلات: **{len(sequences)}**", "",
             "| ID | Company | System | Steps | Day offsets | Status | Stop conditions |",
             "|---|---|---|---:|---|---|---|"]
    for s in sequences:
        offsets = ", ".join(str(st.get("day_offset")) for st in s.get("steps", []))
        stops = "، ".join(s.get("rules", {}).get("stop_conditions", []))
        lines.append("| {id} | {co} | {sys} | {n} | {off} | {st} | {stop} |".format(
            id=md_cell(s.get("id")), co=md_cell(s.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(s.get("recommended_system"))), n=len(s.get("steps", [])),
            off=offsets, st=md_cell(s.get("status")), stop=md_cell(stops)))
    lines.append(FOOTER)
    write_report("acquisition/FOLLOW_UP_SEQUENCE_QUEUE.md", "\n".join(lines))

    # ---------------- OBJECTION_REVIEW ----------------
    cat_counts = Counter(o.get("category") for o in objections)
    lines = [f"# Objection Review", f"Generated: {ts} AST", "",
             "بنك الاعتراضات والردود الآمنة (بلا وعود مضمونة).", "",
             f"إجمالي: **{len(objections)}**", "", "## حسب التصنيف", "", "| Category | Count |", "|---|---:|"]
    for cat, n in sorted(cat_counts.items()):
        lines.append(f"| {cat} | {n} |")
    lines += ["", "## الردود", "", "| ID | Objection | Category | Frequency | Response |",
              "|---|---|---|---|---|"]
    for o in objections:
        lines.append("| {id} | {ob} | {cat} | {fr} | {rsp} |".format(
            id=md_cell(o.get("id")), ob=md_cell(o.get("objection")), cat=md_cell(o.get("category")),
            fr=md_cell(o.get("frequency")), rsp=md_cell(o.get("response"))[:70]))
    lines.append(FOOTER)
    write_report("acquisition/OBJECTION_REVIEW.md", "\n".join(lines))

    # ---------------- DAILY_400_SYSTEM_DRAFT_PRODUCTION ----------------
    lines = [f"# Daily 400 System Draft Production", f"Generated: {ts} AST", "",
             f"الطاقة التصميمية: **{DAILY_DRAFT_CAPACITY} draft/day**. المُجهّز في هذه الدفعة: **{len(packs)}**.", "",
             "> ملاحظة حوكمة: الإنتاج آلي، لكن **الإرسال يبقى خلف موافقة founder** (راجع AGENTS.md §9).", "",
             "## الإنتاج حسب النظام", "", "| System | Drafts |", "|---|---:|"]
    for s, label in SYSTEM_SHORT.items():
        lines.append(f"| {label} | {sys_counts.get(s, 0)} |")
    sendable = [p for p in packs if p.get("status") == "approved_to_send"]
    lines += ["", "## جاهزية الإرسال", "",
              f"- مسودات بحالة approved_to_send: **{len(sendable)}** (هي وحدها القابلة للإرسال بعد الموافقة)",
              f"- باقي المسودات تبقى drafts حتى مراجعة Top 100 وموافقة founder.", FOOTER]
    write_report("outreach/DAILY_400_SYSTEM_DRAFT_PRODUCTION.md", "\n".join(lines))

    # ---------------- TOP_100_SYSTEM_APPROVAL_QUEUE ----------------
    scored = [p for p in packs if (p.get("draft_quality") or {}).get("total", 0) >= TOP_QUALITY_THRESHOLD]
    scored.sort(key=lambda p: (p.get("draft_quality") or {}).get("total", 0), reverse=True)
    top = scored[:100]
    lines = [f"# Top 100 System Approval Queue", f"Generated: {ts} AST", "",
             f"العتبة: Draft Quality Score ≥ **{TOP_QUALITY_THRESHOLD}/100**. مؤهّل الآن: **{len(scored)}** (تُعرض أعلى {len(top)}).", "",
             "للمراجعة والموافقة من founder قبل الإرسال.", "",
             "| Rank | ID | Company | System | Quality | Subject | Evidence | Approve? |",
             "|---:|---|---|---|---:|---|---|---|"]
    for i, p in enumerate(top, 1):
        q = (p.get("draft_quality") or {}).get("total", "")
        lines.append("| {r} | {id} | {co} | {sys} | {q} | {subj} | {ev} | ☐ |".format(
            r=i, id=md_cell(p.get("id")), co=md_cell(p.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))), q=q,
            subj=md_cell(p.get("email_subject"))[:45], ev=md_cell(p.get("evidence_level"))))
    lines.append(FOOTER)
    write_report("outreach/TOP_100_SYSTEM_APPROVAL_QUEUE.md", "\n".join(lines))

    # ---------------- SYSTEM_BASED_CLIENT_NEED_CARDS ----------------
    lines = [f"# System-based Client Need Cards", f"Generated: {ts} AST", "",
             f"إجمالي البطاقات: **{len(cards)}**", ""]
    for s, label in SYSTEM_SHORT.items():
        group = [c for c in cards if c.get("recommended_system") == s]
        if not group:
            continue
        lines += [f"## {label} ({len(group)})", "", "| ID | Company | Signal | Likely pain | Email angle | CTA |",
                  "|---|---|---|---|---|---|"]
        for c in group:
            lines.append("| {id} | {co} | {sig} | {pain} | {ang} | {cta} |".format(
                id=md_cell(c.get("id")), co=md_cell(c.get("company")), sig=md_cell(c.get("signal"))[:35],
                pain=md_cell(c.get("likely_pain"))[:40], ang=md_cell(c.get("email_angle"))[:40],
                cta=md_cell(c.get("CTA"))[:35]))
        lines.append("")
    lines.append(FOOTER)
    write_report("outreach/SYSTEM_BASED_CLIENT_NEED_CARDS.md", "\n".join(lines))

    # ---------------- SYSTEM_EMAIL_DRAFTS_REVIEW ----------------
    lines = [f"# System Email Drafts Review", f"Generated: {ts} AST", "",
             "مراجعة المسودات قبل الموافقة. القاعدة: لا fake Re:/Fwd:، لا claims مضمونة، يوجد CTA، النظام محدد.", "",
             "| ID | Company | System | Subject | Quality | Status |", "|---|---|---|---|---:|---|"]
    for p in packs:
        q = (p.get("draft_quality") or {}).get("total", "")
        lines.append("| {id} | {co} | {sys} | {subj} | {q} | {st} |".format(
            id=md_cell(p.get("id")), co=md_cell(p.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))),
            subj=md_cell(p.get("email_subject"))[:45], q=q, st=md_cell(p.get("status"))))
    lines.append(FOOTER)
    write_report("outreach/SYSTEM_EMAIL_DRAFTS_REVIEW.md", "\n".join(lines))

    print("Acquisition + outreach reports done.")


if __name__ == "__main__":
    main()
