#!/usr/bin/env python3
"""
Generate Dealix delivery reports from data/delivery/*.jsonl.

Outputs:
  reports/delivery/DELIVERY_PIPELINE_STATUS.md
  reports/delivery/DELIVERY_BLOCKERS.md
  reports/delivery/WEEKLY_VALUE_REPORT_QUEUE.md
  reports/delivery/DELIVERY_ACCEPTANCE_REVIEW.md

Run: python3 scripts/generate_delivery_reports.py
"""

from collections import Counter

from dealix_common import SYSTEM_SHORT, load_jsonl, md_cell, now_ast, write_report

FOOTER = "\n---\n*Auto-generated by Dealix Delivery Reports. Delivery cannot start before required_inputs_received=true. Re-run: `python3 scripts/generate_delivery_reports.py`*\n"

STARTED_STATES = {"delivery_started", "first_output_ready", "client_review", "accepted", "weekly_value_report", "renewal_candidate"}
ACTIVE_FOR_WEEKLY = {"delivery_started", "first_output_ready", "client_review", "accepted", "weekly_value_report", "renewal_candidate"}


def main():
    print("Generating delivery reports ...")
    pipelines = load_jsonl("data/delivery/pipelines.jsonl")
    tasks = load_jsonl("data/delivery/tasks.jsonl")
    weeklies = load_jsonl("data/delivery/weekly_value_reports.jsonl")
    gates = load_jsonl("data/delivery/acceptance_gates.jsonl")
    ts = now_ast()

    # ---------------- DELIVERY_PIPELINE_STATUS ----------------
    state_counts = Counter(p.get("current_state") for p in pipelines)
    lines = [f"# Delivery Pipeline Status", f"Generated: {ts} AST", "",
             f"إجمالي مسارات التسليم: **{len(pipelines)}**", "",
             "## التوزيع حسب الحالة", "", "| State | Count |", "|---|---:|"]
    for st, n in state_counts.most_common():
        lines.append(f"| {st} | {n} |")
    lines += ["", "## المسارات", "",
              "| ID | Company | System | State | Inputs received | Open tasks | Owner | Updated |",
              "|---|---|---|---|---|---:|---|---|"]
    for p in pipelines:
        open_tasks = sum(1 for t in tasks if t.get("pipeline_id") == p.get("id") and t.get("status") != "done")
        lines.append("| {id} | {co} | {sys} | {st} | {ir} | {ot} | {own} | {up} |".format(
            id=md_cell(p.get("id")), co=md_cell(p.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))), st=md_cell(p.get("current_state")),
            ir="✅" if p.get("required_inputs_received") else "⛔", ot=open_tasks,
            own=md_cell(p.get("owner")), up=md_cell(p.get("updated_at"))))
    lines.append(FOOTER)
    write_report("delivery/DELIVERY_PIPELINE_STATUS.md", "\n".join(lines))

    # ---------------- DELIVERY_BLOCKERS ----------------
    lines = [f"# Delivery Blockers", f"Generated: {ts} AST", "",
             "العوائق التي تمنع التقدم — خصوصًا انتظار required_inputs.", "",
             "## مسارات بانتظار مدخلات أو بها عوائق", "",
             "| Pipeline | Company | System | State | Inputs? | Blockers |", "|---|---|---|---|---|---|"]
    any_block = False
    for p in pipelines:
        blockers = p.get("blockers", [])
        waiting_inputs = (p.get("current_state") == "intake_required" and not p.get("required_inputs_received"))
        if blockers or waiting_inputs:
            any_block = True
            blk = "، ".join(blockers) if blockers else "بانتظار استلام required_inputs"
            lines.append("| {id} | {co} | {sys} | {st} | {ir} | {blk} |".format(
                id=md_cell(p.get("id")), co=md_cell(p.get("company")),
                sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))), st=md_cell(p.get("current_state")),
                ir="✅" if p.get("required_inputs_received") else "⛔", blk=md_cell(blk)))
    if not any_block:
        lines.append("| — | لا عوائق مسارات حالية | — | — | — | — |")
    blocked_tasks = [t for t in tasks if t.get("status") == "blocked"]
    lines += ["", "## مهام موقوفة (blocked)", "", "| Task | Pipeline | Company | Title | Depends on inputs? |",
              "|---|---|---|---|---|"]
    if blocked_tasks:
        for t in blocked_tasks:
            lines.append("| {id} | {pl} | {co} | {t} | {d} |".format(
                id=md_cell(t.get("id")), pl=md_cell(t.get("pipeline_id")), co=md_cell(t.get("company")),
                t=md_cell(t.get("title"))[:45], d="نعم" if t.get("depends_on_inputs") else "لا"))
    else:
        lines.append("| — | لا مهام موقوفة | — | — | — |")
    lines.append(FOOTER)
    write_report("delivery/DELIVERY_BLOCKERS.md", "\n".join(lines))

    # ---------------- WEEKLY_VALUE_REPORT_QUEUE ----------------
    reported_companies = {w.get("company") for w in weeklies}
    lines = [f"# Weekly Value Report Queue", f"Generated: {ts} AST", "",
             "تقارير القيمة الأسبوعية (قيمة مُلاحَظة، بلا وعود).", "",
             f"تقارير صادرة: **{len(weeklies)}**", "",
             "| ID | Company | System | Week | Acceptance | Owner |", "|---|---|---|---|---|---|"]
    for w in weeklies:
        lines.append("| {id} | {co} | {sys} | {wk} | {ac} | {own} |".format(
            id=md_cell(w.get("id")), co=md_cell(w.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(w.get("recommended_system"))), wk=md_cell(w.get("week_of")),
            ac=md_cell(w.get("acceptance_status")), own=md_cell(w.get("owner"))))
    due = [p for p in pipelines if p.get("current_state") in ACTIVE_FOR_WEEKLY and p.get("company") not in reported_companies]
    lines += ["", "## مسارات نشطة تحتاج تقرير قيمة هذا الأسبوع", "", "| Pipeline | Company | System | State |",
              "|---|---|---|---|"]
    if due:
        for p in due:
            lines.append("| {id} | {co} | {sys} | {st} |".format(
                id=md_cell(p.get("id")), co=md_cell(p.get("company")),
                sys=md_cell(SYSTEM_SHORT.get(p.get("recommended_system"))), st=md_cell(p.get("current_state"))))
    else:
        lines.append("| — | كل المسارات النشطة لها تقرير | — | — |")
    lines.append(FOOTER)
    write_report("delivery/WEEKLY_VALUE_REPORT_QUEUE.md", "\n".join(lines))

    # ---------------- DELIVERY_ACCEPTANCE_REVIEW ----------------
    status_counts = Counter(g.get("status") for g in gates)
    lines = [f"# Delivery Acceptance Review", f"Generated: {ts} AST", "",
             f"بوابات القبول: **{len(gates)}** (passed: {status_counts.get('passed',0)}, open: {status_counts.get('open',0)}, failed: {status_counts.get('failed',0)})", "",
             "| ID | Company | System | Gate (state) | Status | Evidence | Reviewed by | Criteria |",
             "|---|---|---|---|---|---|---|---|"]
    for g in gates:
        crit = "، ".join(g.get("criteria", []))
        lines.append("| {id} | {co} | {sys} | {gt} | {st} | {ev} | {rb} | {cr} |".format(
            id=md_cell(g.get("id")), co=md_cell(g.get("company")),
            sys=md_cell(SYSTEM_SHORT.get(g.get("recommended_system"))), gt=md_cell(g.get("state")),
            st=md_cell(g.get("status")), ev=md_cell(g.get("evidence_level")), rb=md_cell(g.get("reviewed_by")),
            cr=md_cell(crit)[:55]))
    lines.append(FOOTER)
    write_report("delivery/DELIVERY_ACCEPTANCE_REVIEW.md", "\n".join(lines))

    print("Delivery reports done.")


if __name__ == "__main__":
    main()
