#!/usr/bin/env python3
"""
Generate agent governance docs from the single source of truth
(``core.safety.permissions.AGENT_REGISTRY``).

This keeps docs/agents/* consistent with what the test-suite enforces, so the
permission matrix can never silently drift from the code that guards it.

Usage:  python3 scripts/generate_agent_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.safety.permissions import AGENT_REGISTRY, PERMISSION_LEVELS, FORBIDDEN_ACTIONS  # noqa: E402

DOCS = ROOT / "docs" / "agents"
GEN_NOTE = "<!-- GENERATED by scripts/generate_agent_docs.py from core.safety.permissions. Do not edit by hand. -->"


def _matrix_table() -> str:
    rows = [
        "| # | Agent | Permission | Risk | Approval | Handoff |",
        "|---|-------|-----------|------|----------|---------|",
    ]
    for i, a in enumerate(AGENT_REGISTRY.values(), 1):
        rows.append(
            f"| {i} | {a['name']} | {a['permission_level']} ({PERMISSION_LEVELS[a['permission_level']]}) "
            f"| {a['risk_level']} | {'Yes' if a['required_approval'] else 'No'} "
            f"| {', '.join(a['handoff_targets'])} |"
        )
    return "\n".join(rows)


def _catalog() -> str:
    parts = []
    for i, a in enumerate(AGENT_REGISTRY.values(), 1):
        parts.append(
            f"### {i}. {a['name']}\n\n"
            f"- **Mission:** {a['mission']}\n"
            f"- **Permission level:** {a['permission_level']} — {PERMISSION_LEVELS[a['permission_level']]}\n"
            f"- **Risk level:** {a['risk_level']}\n"
            f"- **Input files:** {', '.join(a['input_files'])}\n"
            f"- **Output files:** {', '.join(a['output_files'])}\n"
            f"- **Allowed actions:** {', '.join(a['allowed_actions'])}\n"
            f"- **Forbidden actions:** {', '.join(a['forbidden_actions'])}\n"
            f"- **Required approval:** {'Yes' if a['required_approval'] else 'No'}\n"
            f"- **Required verification:** {', '.join(a['required_verification'])}\n"
            f"- **Handoff targets:** {', '.join(a['handoff_targets'])}\n"
            f"- **Collision rules:** {a['collision_rules']}\n"
        )
    return "\n".join(parts)


def _header(title_ar: str, title_en: str) -> str:
    return (
        f"# {title_ar}\n\n_{title_en}_\n\n{GEN_NOTE}\n\n"
        f"> المصدر الوحيد للحقيقة: `core/safety/permissions.py` — يتم فرضه عبر "
        f"`tests/test_agent_permissions_market.py`.\n\n"
        f"## مستويات الصلاحيات (Permission Levels)\n\n"
        + "\n".join(f"- **{k}** — {v}" for k, v in PERMISSION_LEVELS.items())
        + "\n\n## ممنوع على جميع الوكلاء (Forbidden for ALL agents)\n\n"
        + "\n".join(f"- `{x}`" for x in FORBIDDEN_ACTIONS)
        + "\n\n"
    )


def main() -> int:
    DOCS.mkdir(parents=True, exist_ok=True)
    matrix = _matrix_table()
    catalog = _catalog()

    (DOCS / "AGENT_ROLE_CATALOG_AR.md").write_text(
        _header("كتالوج أدوار الوكلاء", "Agent Role Catalog") + catalog, encoding="utf-8"
    )
    (DOCS / "AGENT_PERMISSION_MATRIX_AR.md").write_text(
        _header("مصفوفة صلاحيات الوكلاء", "Agent Permission Matrix") + matrix + "\n", encoding="utf-8"
    )
    (DOCS / "MARKET_AGENT_REGISTRY.md").write_text(
        f"# Market Agent Registry\n\n{GEN_NOTE}\n\n"
        "Single source of truth: `core/safety/permissions.py`.\n\n" + catalog,
        encoding="utf-8",
    )
    (DOCS / "MARKET_AGENT_PERMISSION_MATRIX.md").write_text(
        f"# Market Agent Permission Matrix\n\n{GEN_NOTE}\n\n" + matrix + "\n",
        encoding="utf-8",
    )
    print(f"Generated 4 agent docs for {len(AGENT_REGISTRY)} agents in {DOCS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
