"""Phase 2 strategic initiatives 101-200 (waves 11-20)."""

from __future__ import annotations

# (id, title_en, wave, owner_os, raci_R, deliverable, verification)
INITIATIVES_PHASE2: list[tuple[int, str, int, str, str, str, str]] = [
    (101, "AI cost per measured revenue SAR", 11, "finance", "CTO", "dealix/transformation/ai_unit_economics.yaml", "pytest tests/test_ai_unit_economics.py -q"),
    (102, "Per-tenant LLM budget guardrails", 11, "platform", "CTO", "auto_client_acquisition/llm_gateway_v10/budget_policy.yaml", "pytest tests/test_llm_gateway_v10.py -q"),
    (103, "Agent action ROI events in value ledger", 11, "value", "CTO", "value_os/value_ledger.py ai_spend kind", "pytest tests/test_value_attribution.py -q"),
    (104, "Arabic outbound draft grounding eval", 11, "trust", "CTO", "tests/fixtures/arabic_draft_golden.json", "pytest tests/test_arabic_draft_grounding.py -q"),
    (105, "Approval queue SLA breach alerts", 11, "trust", "CTO", "auto_client_acquisition/control_plane_os/sla_alerts.py", "pytest tests/test_control_plane_sla_alerts.py -q"),
    (106, "Prompt version registry", 11, "trust", "CTO", "auto_client_acquisition/governance_os/prompt_registry.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (107, "Agent role capability matrix", 11, "platform", "CTO", "auto_client_acquisition/ai_workforce_v10/capability_matrix.yaml", "pytest tests/test_ai_workforce_v10.py -q"),
    (108, "Governance red-team synthetic cases", 11, "trust", "CTO", "tests/test_governance_red_team.py", "pytest tests/test_governance_red_team.py -q"),
    (109, "Token spend anomaly detection", 11, "observability", "CTO", "auto_client_acquisition/observability_v10/token_anomaly_rules.yaml", "pytest tests/test_observability_v10.py -q"),
    (110, "Human override audit export API", 11, "trust", "CTO", "api/routers/audit_export.py", "pytest tests/test_audit_export_override.py -q"),
    (111, "Multi-tenant isolation evidence pack", 12, "platform", "CTO", "docs/enterprise/TENANT_ISOLATION_EVIDENCE.md", "pytest tests/test_tenant_isolation_systems_26_35.py -q"),
    (112, "Enterprise SSO readiness gate", 12, "platform", "CTO", "api/routers/enterprise_sso_readiness.py", "pytest tests/test_enterprise_sso_readiness.py -q"),
    (113, "KSA data residency manifest", 12, "trust", "CTO", "dealix/registers/data_residency_ksa.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (114, "SOC2 control mapping", 12, "trust", "CTO", "docs/enterprise/SOC2_CONTROL_MAP.md", "verify_global_ai_transformation.py --check-initiatives"),
    (115, "Customer audit read-only API", 12, "trust", "CTO", "api/routers/customer_audit_view.py", "pytest tests/test_customer_audit_view.py -q"),
    (116, "Encryption-at-rest checklist", 12, "trust", "CTO", "docs/enterprise/ENCRYPTION_CHECKLIST.md", "verify_global_ai_transformation.py --check-initiatives"),
    (117, "Secrets rotation hooks", 12, "reliability", "CTO", "docs/SECURITY_RUNBOOK.md", "verify_global_ai_transformation.py --check-reliability"),
    (118, "Security questionnaire generator", 12, "trust", "CTO", "scripts/generate_security_questionnaire.py", "python3 scripts/generate_security_questionnaire.py"),
    (119, "Vendor risk registry", 12, "trust", "CTO", "dealix/registers/vendor_risk.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (120, "Pen-test remediation tracker", 12, "trust", "CTO", "dealix/transformation/pentest_tracker.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (121, "CAC payback API", 13, "finance", "Revenue", "api/routers/unit_economics.py", "pytest tests/test_unit_economics_router.py -q"),
    (122, "LTV from revenue memory", 13, "finance", "Revenue", "auto_client_acquisition/operating_finance_os/ltv_from_events.py", "pytest tests/test_ltv_from_events.py -q"),
    (123, "Churn risk composite", 13, "delivery", "Operations", "api/routers/customer_success_scores.py", "pytest tests/test_customer_health_v2.py -q"),
    (124, "Expansion forecast by proof level", 13, "sales", "Revenue", "api/routers/expansion_engine.py", "pytest tests/test_expansion_forecast.py -q"),
    (125, "DSO cash collection KPI", 13, "finance", "Revenue", "dealix/transformation/kpi_registry.yaml", "verify_global_ai_transformation.py"),
    (126, "Per-customer unit economics cockpit", 13, "finance", "Revenue", "api/routers/customer_unit_economics.py", "pytest tests/test_customer_unit_economics.py -q"),
    (127, "Margin floor in pricing engine", 13, "finance", "Revenue", "auto_client_acquisition/value_os/pricing_engine.py", "pytest tests/test_pricing_engine.py -q"),
    (128, "Cohort retention API", 13, "finance", "Revenue", "api/routers/cohort_retention.py", "pytest tests/test_cohort_retention.py -q"),
    (129, "Revenue leakage rules", 13, "sales", "Revenue", "auto_client_acquisition/revenue_os/leakage_rules.yaml", "bash scripts/revenue_os_master_verify.sh"),
    (130, "Finance reconciliation weekly", 13, "finance", "Revenue", "scripts/run_finance_reconciliation_weekly.sh", "bash scripts/run_finance_reconciliation_weekly.sh"),
    (131, "Win loss registry with evidence", 14, "gtm", "CEO", "dealix/registers/win_loss.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (132, "Competitive battlecard library", 14, "gtm", "CEO", "docs/sales-kit/battlecards/README.md", "verify_global_ai_transformation.py --check-initiatives"),
    (133, "Analyst briefing pack generator", 14, "strategy", "CEO", "scripts/generate_analyst_briefing_pack.py", "python3 scripts/generate_analyst_briefing_pack.py"),
    (134, "Category narrative linter", 14, "strategy", "CEO", "scripts/lint_category_narrative.py", "python3 scripts/lint_category_narrative.py"),
    (135, "Market signal to offer mapper v2", 14, "gtm", "Revenue", "api/routers/revenue_os_catalog.py", "bash scripts/revenue_os_master_verify.sh"),
    (136, "Founder market signal API hardening", 14, "gtm", "Revenue", "api/routers/revenue_os_catalog.py", "pytest tests/test_revenue_os_catalog.py -q"),
    (137, "Reference customer program", 14, "gtm", "CEO", "docs/transformation/reference_customer_program_ar.md", "verify_global_ai_transformation.py --check-initiatives"),
    (138, "Case study approval workflow", 14, "sales", "Revenue", "api/routers/case_study_engine.py", "pytest tests/test_case_study_governance.py -q"),
    (139, "Category benchmark doc", 14, "strategy", "CEO", "docs/strategic/CATEGORY_BENCHMARK_AR.md", "verify_global_ai_transformation.py --check-initiatives"),
    (140, "Thought leadership draft gate", 14, "product", "CEO", "dealix/transformation/lane_policy.yaml", "pytest tests/test_lane_policy.py -q"),
    (141, "Feature flag registry linked to lanes", 15, "platform", "CTO", "dealix/transformation/feature_flags.yaml", "pytest tests/test_feature_flags_registry.py -q"),
    (142, "Internal experiment assignment", 15, "product", "CTO", "platform_core/experiment_assign.py", "pytest tests/test_experiment_assign.py -q"),
    (143, "Release train calendar", 15, "platform", "CTO", "dealix/transformation/release_train.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (144, "API deprecation policy", 15, "platform", "CTO", "docs/architecture/API_DEPRECATION_POLICY.md", "verify_global_ai_transformation.py --check-initiatives"),
    (145, "Breaking change notification drafts", 15, "platform", "CTO", "api/routers/changelog_drafts.py", "pytest tests/test_changelog_drafts.py -q"),
    (146, "Product telemetry privacy budget", 15, "trust", "CTO", "dealix/registers/telemetry_budget.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (147, "Canary readiness gate", 15, "platform", "CTO", "api/routers/unified_readiness.py", "pytest tests/test_unified_readiness.py -q"),
    (148, "Rollback runbook API link", 15, "reliability", "CTO", "api/routers/control_plane_os.py", "pytest tests/test_control_plane_rollback_flow.py -q"),
    (149, "FE BE version skew check", 15, "platform", "CTO", "scripts/check_fe_be_version_skew.py", "python3 scripts/check_fe_be_version_skew.py"),
    (150, "Governed changelog generator", 15, "platform", "CTO", "scripts/generate_governed_changelog.py", "python3 scripts/generate_governed_changelog.py"),
    (151, "Customer health 2.0 from events", 16, "delivery", "Operations", "auto_client_acquisition/customer_success/health_v2.py", "pytest tests/test_customer_health_v2.py -q"),
    (152, "Detractor playbook drafts", 16, "delivery", "Operations", "dealix/transformation/detractor_playbooks.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (153, "Vertical success plans", 16, "delivery", "Operations", "auto_client_acquisition/adoption_os/first_14_days_playbook.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (154, "Executive sponsor field governance", 16, "delivery", "Operations", "docs/crm/executive_sponsor_fields.md", "verify_global_ai_transformation.py --check-initiatives"),
    (155, "Renewal 90-day early warning", 16, "sales", "Revenue", "scripts/generate_weekly_operating_proof_pack.py", "generate_weekly_operating_proof_pack.py"),
    (156, "NPS governed follow-up", 16, "delivery", "Operations", "api/routers/nps.py", "pytest tests/test_nps_governed.py -q"),
    (157, "QBR auto-population", 16, "delivery", "Operations", "scripts/generate_qbr_pack.py", "python3 scripts/generate_qbr_pack.py"),
    (158, "Adoption milestone alerts", 16, "delivery", "Operations", "auto_client_acquisition/adoption_os/milestone_alerts.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (159, "White-glove escalation registry", 16, "strategy", "CEO", "dealix/transformation/escalation_registry.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (160, "Customer council PERB bridge", 16, "gtm", "CEO", "docs/transformation/customer_council_ar.md", "verify_global_ai_transformation.py --check-initiatives"),
    (161, "Partner sandbox tenant", 17, "platform", "CTO", "auto_client_acquisition/sandbox_os/partner_tenant.py", "pytest tests/test_partner_sandbox.py -q"),
    (162, "Integration certification", 17, "platform", "CTO", "docs/partners/INTEGRATION_CERTIFICATION.md", "verify_global_ai_transformation.py --check-initiatives"),
    (163, "Webhook delivery SLO and DLQ", 17, "platform", "CTO", "api/routers/customer_webhooks.py", "pytest tests/test_webhook_slo.py -q"),
    (164, "Public API rate tiers", 17, "platform", "CTO", "platform_core/rate_tiers.yaml", "pytest tests/test_platform_foundation.py -q"),
    (165, "OAuth client governance", 17, "trust", "CTO", "dealix/registers/oauth_clients.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (166, "Partner revenue share attribution", 17, "value", "Revenue", "auto_client_acquisition/value_os/attribution_paths.yaml", "pytest tests/test_value_attribution.py -q"),
    (167, "Marketplace criteria", 17, "gtm", "Revenue", "docs/partners/MARKETPLACE_CRITERIA.md", "verify_global_ai_transformation.py --check-initiatives"),
    (168, "ISV co-sell playbook", 17, "gtm", "Revenue", "docs/partners/ISV_COSELL_AR.md", "verify_global_ai_transformation.py --check-initiatives"),
    (169, "Partner API changelog", 17, "platform", "CTO", "docs/partners/API_CHANGELOG.md", "verify_global_ai_transformation.py --check-initiatives"),
    (170, "Developer trust status page", 17, "trust", "CTO", "api/routers/developer_trust_status.py", "pytest tests/test_developer_trust_status.py -q"),
    (171, "RAG freshness score", 18, "data", "CTO", "auto_client_acquisition/knowledge_v10/freshness_score.py", "pytest tests/test_knowledge_v10.py -q"),
    (172, "Embedding lineage in events", 18, "data", "CTO", "auto_client_acquisition/revenue_memory/embedding_lineage.py", "pytest tests/test_embedding_lineage.py -q"),
    (173, "Project intelligence sales brief export", 18, "product", "CTO", "dealix/execution/sales_brief_export.py", "pytest tests/test_sales_brief_export.py -q"),
    (174, "Competitive notes founder manual", 18, "strategy", "CEO", "dealix/registers/competitive_notes.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (175, "Answer grounding score API", 18, "trust", "CTO", "api/routers/grounding_score.py", "pytest tests/test_grounding_score.py -q"),
    (176, "Chunk quality score", 18, "data", "CTO", "auto_client_acquisition/knowledge_v10/chunk_quality.py", "pytest tests/test_chunk_quality.py -q"),
    (177, "Hallucination incident register", 18, "trust", "CTO", "dealix/transformation/hallucination_register.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (178, "Arabic tone compliance scorer", 18, "trust", "CTO", "auto_client_acquisition/governance_os/arabic_tone_rules.yaml", "pytest tests/test_arabic_tone_rules.py -q"),
    (179, "Intelligence layer cost cap", 18, "finance", "CTO", "dealix/transformation/ai_unit_economics.yaml", "pytest tests/test_ai_unit_economics.py -q"),
    (180, "Weekly cross-OS snapshot v2", 18, "strategy", "CEO", "dealix/execution/weekly_cross_os_snapshot.py", "pytest tests/test_weekly_cross_os_snapshot_v2.py -q"),
    (181, "Runbook-as-code top incidents", 19, "reliability", "CTO", "docs/ops/runbooks/README.md", "verify_global_ai_transformation.py --check-initiatives"),
    (182, "Auto-remediation proposals approval", 19, "reliability", "CTO", "auto_client_acquisition/runtime_safety_os/remediation_proposals.py", "pytest tests/test_remediation_proposals.py -q"),
    (183, "Postgres pool capacity model", 19, "platform", "CTO", "docs/ops/DB_CAPACITY_MODEL.md", "verify_global_ai_transformation.py --check-initiatives"),
    (184, "Cost-to-serve from logs", 19, "finance", "CEO", "scripts/estimate_cost_to_serve.py", "python3 scripts/estimate_cost_to_serve.py"),
    (185, "Engineering OKR initiative link", 19, "strategy", "CEO", "strategic_initiatives_registry.yaml okr_key", "verify_global_ai_transformation.py --check-initiatives"),
    (186, "CI initiative coverage report", 19, "platform", "CTO", "scripts/report_initiative_coverage.py", "python3 scripts/report_initiative_coverage.py"),
    (187, "API domain migration batch 2", 19, "platform", "CTO", "api/routers/domains/analytics", "pytest tests/test_api_domain_batch2.py -q"),
    (188, "API domain migration batch 3", 19, "platform", "CTO", "api/routers/domains/admin", "pytest tests/test_api_domain_batch3.py -q"),
    (189, "Dead code sunset registry", 19, "platform", "CTO", "dealix/transformation/dead_code_sunset.yaml", "verify_global_ai_transformation.py --check-initiatives"),
    (190, "Performance budget per route", 19, "reliability", "CTO", "dealix/transformation/slo_by_domain.yaml", "python3 scripts/reliability_drills_scorecard.py"),
    (191, "Second-line leadership matrix", 20, "people_ops", "CEO", "dealix/transformation/ownership_matrix.yaml", "verify_global_ai_transformation.py"),
    (192, "Board metrics read API", 20, "strategy", "CEO", "api/routers/board_metrics.py", "pytest tests/test_board_metrics.py -q"),
    (193, "M&A data room export", 20, "strategy", "CEO", "scripts/generate_ma_data_room_pack.py", "python3 scripts/generate_ma_data_room_pack.py"),
    (194, "IPO-light control matrix", 20, "trust", "CEO", "docs/enterprise/IPO_LIGHT_CONTROLS.md", "verify_global_ai_transformation.py --check-initiatives"),
    (195, "OS owner succession backups", 20, "people_ops", "CEO", "dealix/transformation/ownership_matrix.yaml", "verify_global_ai_transformation.py"),
    (196, "DEALIX 2040 endgame", 20, "strategy", "CEO", "docs/transformation/DEALIX_2040_ENDGAME_AR.md", "verify_global_ai_transformation.py --check-initiatives"),
    (197, "Institution mode phase 2", 20, "people_ops", "CEO", "docs/transformation/INSTITUTION_MODE_PHASE2_AR.md", "verify_global_ai_transformation.py --check-initiatives"),
    (198, "Strategic hire scorecard", 20, "people_ops", "CEO", "docs/people_ops/HIRE_SCORECARD.md", "verify_global_ai_transformation.py --check-initiatives"),
    (199, "Culture ops decision log", 20, "people_ops", "CEO", "docs/transformation/evidence/culture_decisions.log", "verify_global_ai_transformation.py --check-initiatives"),
    (200, "Dealix 200 completion gate", 20, "strategy", "CEO", "scripts/run_phase2_top10_bundle.sh", "bash scripts/run_phase2_top10_bundle.sh"),
]

PHASE2_ACTIVE_IDS = {101, 111, 121, 122, 131, 141, 147, 151, 161, 175, 200}
