#!/usr/bin/env bash
# CTO weekly anchor: executive checklist + ownership/KPI sync hints + session report stub.
# See docs/transformation/CTO_EXECUTIVE_CADENCE_AR.md
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="$(command -v python3)"
DATE_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DATE_DAY="${DATE_UTC:0:10}"
ANCHOR_LOG="${ROOT}/docs/transformation/evidence/cto_weekly_anchor.log"
SESSION_REPORT="${ROOT}/docs/transformation/evidence/session_report_${DATE_DAY}.md"

cd "$ROOT"

echo "== CTO anchor: executive weekly checklist =="
bash "${ROOT}/scripts/run_executive_weekly_checklist.sh"

echo ""
echo "== CTO anchor: platform KPI signals =="
"$PYTHON_BIN" "${ROOT}/scripts/populate_kpi_baselines_platform_signals.py"

echo ""
echo "== CTO anchor: founder commercial registry status =="
"$PYTHON_BIN" "${ROOT}/scripts/apply_kpi_founder_commercial.py" --status || true

echo ""
echo "== CTO anchor: business NOW snapshot =="
bash "${ROOT}/scripts/run_business_now.sh" || true

mkdir -p "$(dirname "$ANCHOR_LOG")"
echo "${DATE_UTC} cto_weekly_anchor=OK checklist=PASS" >>"$ANCHOR_LOG"

mkdir -p "$(dirname "$SESSION_REPORT")"
if [[ ! -f "$SESSION_REPORT" ]]; then
  {
    echo "# CEO one-session readiness report — ${DATE_DAY}"
    echo ""
    echo "## Generated by"
    echo ""
    echo "- scripts/run_cto_weekly_anchor.sh (weekly anchor; full bundle: run_ceo_one_session_readiness.sh)"
    echo ""
    echo "## Founder-only"
    echo ""
    echo "- Fill dealix/transformation/kpi_founder_commercial_registry.yaml then run apply_kpi_founder_commercial.py"
    echo "- Update ownership_matrix executive_review.last_ownership_matrix_review_iso"
  } >"$SESSION_REPORT"
fi

echo ""
echo "CTO_WEEKLY_ANCHOR: OK"
echo "Anchor log: ${ANCHOR_LOG}"
echo "Session report: ${SESSION_REPORT}"
