"""Master verification for Dealix Ultimate Commercial OS.

Usage:
    python3 scripts/verify_dealix_ultimate_os.py
"""
from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

REQUIRED = [
    # Brand
    "business/brand/DEALIX_BRAND_SYSTEM.md",
    "business/brand/DEALIX_LOGO_AND_IDENTITY_SYSTEM.md",
    "business/brand/DEALIX_COPY_BANK_AR.md",
    "business/brand/DEALIX_COPY_BANK_EN.md",
    "apps/web/public/dealix-logo.svg",
    "apps/web/public/dealix-mark.svg",
    "apps/web/public/dealix-og.svg",
    # Website pages
    "apps/web/app/brand/page.tsx",
    "apps/web/app/offers/page.tsx",
    "apps/web/app/pricing/page.tsx",
    "apps/web/app/cases/page.tsx",
    "apps/web/app/revenue-machine/page.tsx",
    "apps/web/app/sales-assets/page.tsx",
    "apps/web/app/lead-engine/page.tsx",
    "apps/web/app/persuasion-room/page.tsx",
    "apps/web/app/command-center/page.tsx",
    "apps/web/app/war-room/page.tsx",
    "apps/web/app/pipeline/page.tsx",
    "apps/web/app/delivery-os/page.tsx",
    "apps/web/app/partner-room/page.tsx",
    "apps/web/app/daily-draft/page.tsx",
    "apps/web/app/kpi-finance/page.tsx",
    "apps/web/app/client-acquisition/page.tsx",
    "apps/web/app/automated-sales/page.tsx",
    # APIs
    "apps/web/app/api/company-os/ceo-brief/route.ts",
    "apps/web/app/api/company-os/founder-dashboard/route.ts",
    "apps/web/app/api/sales-machine/ultimate-pack/route.ts",
    "apps/web/app/api/sales-machine/daily-pack/route.ts",
    # Libraries
    "apps/web/lib/company-os/company-os.ts",
    "apps/web/lib/company-os/pipeline.ts",
    "apps/web/lib/sales-machine/ultimate-sales-os.ts",
    "apps/web/lib/sales-automation/lead-sources.ts",
    "apps/web/lib/generated/founder-dashboard.ts",
    # Sales machine docs
    "business/sales-machine/DEALIX_MASTER_SALES_FILE_AR.md",
    "business/sales-machine/DEALIX_MASTER_SALES_FILE_EN.md",
    "business/sales-machine/OBJECTION_HANDLING_LIBRARY.md",
    "business/sales-machine/PERSUASION_ANGLE_MATRIX.md",
    "business/sales-machine/LEAD_SOURCE_CONNECTORS_SPEC.md",
    "business/sales-machine/SALES_DAILY_OPERATING_SYSTEM.md",
    "business/sales-machine/INDUSTRY_WEAKNESS_TAXONOMY.md",
    "business/sales-machine/OFFER_MATCHING_RULES.md",
    "business/sales-machine/HUMAN_REVIEW_POLICY.md",
    # CRM
    "business/crm/schema.md",
    "business/crm/prospects.seed.json",
    "business/crm/README.md",
    # Proposals
    "business/proposals/PROPOSAL_TEMPLATE_AR.md",
    "business/proposals/PROPOSAL_TEMPLATE_EN.md",
    "business/proposals/PROPOSAL_SECTIONS_LIBRARY.md",
    # Delivery
    "business/delivery/CLIENT_DELIVERY_SOP.md",
    "business/delivery/CLIENT_ONBOARDING_CHECKLIST.md",
    "business/delivery/PROOF_REPORT_TEMPLATE.md",
    "business/delivery/WEEKLY_COMMAND_REPORT_TEMPLATE.md",
    "business/delivery/CHANGE_REQUEST_POLICY.md",
    "business/delivery/DELIVERY_AUTOMATION_BLUEPRINT.md",
    # Governance
    "business/governance/AI_HUMAN_REVIEW_POLICY.md",
    "business/governance/PDPL_AWARE_DATA_BOUNDARIES.md",
    "business/governance/OUTREACH_COMPLIANCE_POLICY.md",
    "business/governance/NO_SPAM_POLICY.md",
    "business/governance/SOURCE_AND_DATA_USAGE_REGISTER.md",
    "business/legal-lite/CLIENT_BOUNDARIES.md",
    # Pricing/Finance
    "business/pricing/OFFER_LADDER.md",
    "business/pricing/PRICING_STRATEGY_AR.md",
    "business/pricing/PRICING_STRATEGY_EN.md",
    "business/pricing/QUOTE_RULES.md",
    "business/finance/UNIT_ECONOMICS_MODEL.md",
    "business/finance/KPI_FINANCE_CONTROL.md",
    # CEO
    "business/ceo/FOUNDER_WAR_ROOM.md",
    "business/reports/DAILY_CEO_BRIEF_TEMPLATE.md",
    "business/reports/WEEKLY_OPERATING_REVIEW.md",
    # AI
    "business/ai/AI_TASK_ROUTING.md",
    "docs/ai/AI_MODEL_ROUTER_PLAN.md",
    "docs/integrations/INTEGRATION_ARCHITECTURE.md",
    "docs/integrations/GOOGLE_PLACES_CONNECTOR_PLAN.md",
    "docs/integrations/WHATSAPP_BUSINESS_CONNECTOR_PLAN.md",
    "docs/integrations/HUBSPOT_OR_CRM_CONNECTOR_PLAN.md",
    "docs/integrations/OPEN_DATA_CONNECTOR_PLAN.md",
    "docs/integrations/EMAIL_OUTREACH_CONNECTOR_PLAN.md",
    "docs/security/SALES_AUTOMATION_SECURITY_MODEL.md",
    "docs/security/DATA_MINIMIZATION.md",
    "docs/security/AUDIT_LOGGING_PLAN.md",
    # Scripts
    "scripts/import_leads_csv.py",
    "scripts/score_leads.py",
    "scripts/generate_outreach_drafts.py",
    "scripts/approve_outreach_draft.py",
    "scripts/reject_outreach_draft.py",
    "scripts/generate_prospect_pack.py",
    "scripts/generate_followup_queue.py",
    "scripts/generate_proposal.py",
    "scripts/generate_client_brief.py",
    "scripts/generate_workflow_review_agenda.py",
    "scripts/generate_delivery_plan.py",
    "scripts/generate_weekly_command_report.py",
    "scripts/generate_daily_ceo_brief.py",
    "scripts/generate_weekly_operating_review.py",
    "scripts/generate_ultimate_sales_os_pack.py",
    "scripts/generate_sales_machine_pack.py",
    "scripts/verify_dealix_ultimate_os.py",
    "scripts/verify_ultimate_sales_os.py",
    "scripts/verify_sales_machine.py",
    "scripts/verify_client_acquisition_delivery_os.py",
    # V6 — Production data, auth, admin, reliability
    "business/_schemas/account.schema.json",
    "business/_schemas/lead.schema.json",
    "business/_schemas/draft.schema.json",
    "business/_schemas/proposal.schema.json",
    "business/_schemas/deal.schema.json",
    "business/_schemas/proof_item.schema.json",
    "business/_schemas/client.schema.json",
    "business/_schemas/audit_event.schema.json",
    "scripts/lib/data_adapter.py",
    "scripts/lib/json_adapter.py",
    "scripts/lib/db_adapter.py",
    "scripts/lib/repository.py",
    "scripts/lib/audit_log.py",
    "scripts/lib/backup.py",
    "scripts/lib/errors.py",
    "scripts/check_required_env.py",
    "scripts/generate_env_report.py",
    "scripts/restore_business_data.py",
    "scripts/dealix_v6_run_all.py",
    "docs/data/V6_PRODUCTION_DATA_ARCHITECTURE.md",
    "docs/data/POSTGRES_MIGRATION_PLAN.md",
    "docs/data/SQLITE_LOCAL_DEV_PLAN.md",
    "docs/data/DATA_RETENTION_POLICY.md",
    "docs/data/BACKUP_RESTORE_STRATEGY.md",
    "docs/auth/V6_ADMIN_ACCESS_MODEL.md",
    "docs/auth/PRODUCTION_AUTH_REQUIREMENTS.md",
    "docs/auth/SESSION_SECURITY_PLAN.md",
    "docs/auth/ROLE_BASED_ACCESS_PLAN.md",
    "apps/web/middleware.ts",
    "apps/web/app/login/page.tsx",
    "apps/web/app/api/auth/check/route.ts",
    "apps/web/app/api/auth/logout/route.ts",
    # V7 — Connectors, lead intelligence, CRM sync
    "connectors/base.py",
    "connectors/csv_connector.py",
    "connectors/manual_research_connector.py",
    "connectors/website_signal_analyzer.py",
    "connectors/hubspot_connector_stub.py",
    "connectors/google_places_connector_stub.py",
    "connectors/whatsapp_business_connector_stub.py",
    "connectors/email_connector_stub.py",
    "connectors/registry.py",
    "connectors/normalizer.py",
    "connectors/source_audit.py",
    "business/_data/sources.registry.json",
    "business/sources/SOURCE_REGISTRY.md",
    "business/sources/SOURCE_RISK_MATRIX.md",
    "business/sources/TERMS_REVIEW_CHECKLIST.md",
    "business/sources/LEAD_SOURCE_OPERATING_RULES.md",
    "business/lead-intelligence/LEAD_QUALITY_ENGINE.md",
    "business/lead-intelligence/SIGNAL_LIBRARY.md",
    "business/lead-intelligence/WEAKNESS_HYPOTHESIS_GUIDE.md",
    "business/lead-intelligence/ACCOUNT_RESEARCH_CHECKLIST.md",
    "docs/integrations/V7_CRM_SYNC_ARCHITECTURE.md",
    "docs/integrations/HUBSPOT_SYNC_PLAN.md",
    "docs/integrations/CRM_FIELD_MAPPING.md",
    "scripts/audit_lead_sources.py",
    "scripts/export_crm_csv.py",
    # V8 — AI Router, prompt registry, evals
    "scripts/lib/ai_router.py",
    "scripts/lib/ai_safety.py",
    "business/ai/PROMPT_REGISTRY.md",
    "business/ai/AI_OUTPUT_QUALITY_BAR.md",
    "business/ai/prompts/lead_scoring_explanation.md",
    "business/ai/prompts/weakness_hypothesis.md",
    "business/ai/prompts/outreach_draft_ar.md",
    "business/ai/prompts/outreach_draft_en.md",
    "business/ai/prompts/proposal_section_ar.md",
    "business/ai/prompts/proposal_section_en.md",
    "business/ai/evals/outreach_eval_cases.json",
    "business/ai/evals/proposal_eval_cases.json",
    "business/ai/evals/safety_eval_cases.json",
    "business/ai/evals/lead_scoring_eval_cases.json",
    "docs/ai/V8_AI_AGENT_ARCHITECTURE.md",
    "docs/ai/MODEL_PROVIDER_MATRIX.md",
    "docs/ai/DETERMINISTIC_FALLBACK_POLICY.md",
    "docs/ai/AI_SAFETY_AND_REVIEW_GATES.md",
    "scripts/run_ai_evals.py",
    "scripts/dealix_v8_run_all.py",
    "tests/test_ai_router_fallback.py",
    # V9 — Growth, SEO, content, industry pages, campaigns
    "apps/web/app/industries/page.tsx",
    "apps/web/app/industries/[id]/page.tsx",
    "apps/web/app/book/page.tsx",
    "apps/web/app/resources/page.tsx",
    "apps/web/lib/industries/industry-pages.ts",
    "business/lead-magnets/WORKFLOW_LEAKAGE_CHECKLIST_AR.md",
    "business/lead-magnets/WORKFLOW_LEAKAGE_CHECKLIST_EN.md",
    "business/lead-magnets/REVENUE_OS_READINESS_SCORECARD_AR.md",
    "business/lead-magnets/REVENUE_OS_READINESS_SCORECARD_EN.md",
    "business/lead-magnets/REVIEW_OS_AUDIT_TEMPLATE_AR.md",
    "business/lead-magnets/REVIEW_OS_AUDIT_TEMPLATE_EN.md",
    "business/lead-magnets/COMMAND_CENTER_REQUIREMENTS_TEMPLATE_AR.md",
    "business/lead-magnets/COMMAND_CENTER_REQUIREMENTS_TEMPLATE_EN.md",
    "business/campaigns/CAMPAIGN_OPERATING_SYSTEM.md",
    "docs/growth/SEO_STRATEGY.md",
    "docs/growth/CONTENT_ENGINE.md",
    "docs/growth/LINKEDIN_CONTENT_PLAYBOOK.md",
    "docs/growth/FOUNDER_CONTENT_ROUTINE.md",
    "scripts/generate_content_calendar.py",
    "scripts/generate_campaign_pack.py",
    "scripts/dealix_v9_run_all.py",
    # V10 — Enterprise release, observability, compliance, data room, final PR
    "business/enterprise/ENTERPRISE_READINESS_PACK.md",
    "business/enterprise/SECURITY_QUESTIONNAIRE_TEMPLATE.md",
    "business/enterprise/DATA_BOUNDARY_STATEMENT.md",
    "business/enterprise/AI_GOVERNANCE_STATEMENT.md",
    "business/enterprise/HUMAN_REVIEW_STATEMENT.md",
    "business/enterprise/SERVICE_LEVEL_BOUNDARIES.md",
    "business/enterprise/IMPLEMENTATION_ASSURANCE_PLAN.md",
    "business/enterprise/ENTERPRISE_BUYER_FAQ_AR.md",
    "business/enterprise/ENTERPRISE_BUYER_FAQ_EN.md",
    "business/data-room/GTM_SYSTEM.md",
    "business/data-room/RISK_AND_MITIGATION.md",
    "business/data-room/ROADMAP.md",
    "business/demo/DEALIX_DEMO_SCRIPT_AR.md",
    "business/demo/DEALIX_DEMO_SCRIPT_EN.md",
    "apps/web/app/enterprise-readiness/page.tsx",
    "docs/ops/V10_OBSERVABILITY_PLAN.md",
    "docs/ops/ERROR_BUDGET_LITE.md",
    "docs/ops/INCIDENT_RESPONSE_RUNBOOK.md",
    "docs/ops/BACKUP_SCHEDULE.md",
    "docs/ops/CHANGELOG_AND_RELEASE_PROCESS.md",
    "scripts/generate_release_notes.py",
    "scripts/generate_health_snapshot.py",
    "scripts/incident_report_template.py",
    "scripts/generate_demo_pack.py",
    "scripts/dealix_v10_run_all.py",
]


def main() -> int:
    missing = [r for r in REQUIRED if not (REPO_ROOT / r).exists()]
    if missing:
        print("MISSING:")
        for m in missing:
            print(f"  - {m}")
        return 1
    print("Dealix Ultimate Commercial OS verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
