// AUTO-GENERATED by scripts/launch/build.py — do not edit by hand.
import type { ReactElement } from 'react'
import HomePage from './pages/site/HomePage'
import SystemsIndexPage from './pages/site/SystemsIndexPage'
import PricingPage from './pages/site/PricingPage'
import DiagnosticPage from './pages/site/DiagnosticPage'
import StartPage from './pages/site/StartPage'
import ContactPage from './pages/site/ContactPage'
import SolutionsIndexPage from './pages/site/SolutionsIndexPage'
import RevenueOperatingSystemPage from './pages/site/RevenueOperatingSystemPage'
import ExecutiveCommandOsPage from './pages/site/ExecutiveCommandOsPage'
import FollowUpRecoveryOsPage from './pages/site/FollowUpRecoveryOsPage'
import WhatsappClientOsPage from './pages/site/WhatsappClientOsPage'
import ProposalProofOsPage from './pages/site/ProposalProofOsPage'
import SolutionMarketingAgenciesPage from './pages/site/SolutionMarketingAgenciesPage'
import SolutionTrainingCompaniesPage from './pages/site/SolutionTrainingCompaniesPage'
import SolutionClinicsPage from './pages/site/SolutionClinicsPage'
import SolutionRealEstatePage from './pages/site/SolutionRealEstatePage'
import SolutionProfessionalServicesPage from './pages/site/SolutionProfessionalServicesPage'
import SolutionRecruitmentPage from './pages/site/SolutionRecruitmentPage'
import SolutionSaasPage from './pages/site/SolutionSaasPage'
import SolutionLogisticsPage from './pages/site/SolutionLogisticsPage'

export const siteRoutes: { path: string; element: ReactElement }[] = [
  { path: '/', element: <HomePage /> },
  { path: '/systems', element: <SystemsIndexPage /> },
  { path: '/pricing', element: <PricingPage /> },
  { path: '/diagnostic', element: <DiagnosticPage /> },
  { path: '/start', element: <StartPage /> },
  { path: '/contact', element: <ContactPage /> },
  { path: '/solutions', element: <SolutionsIndexPage /> },
  { path: '/systems/revenue-operating-system', element: <RevenueOperatingSystemPage /> },
  { path: '/systems/executive-command-os', element: <ExecutiveCommandOsPage /> },
  { path: '/systems/follow-up-recovery-os', element: <FollowUpRecoveryOsPage /> },
  { path: '/systems/whatsapp-client-os', element: <WhatsappClientOsPage /> },
  { path: '/systems/proposal-proof-os', element: <ProposalProofOsPage /> },
  { path: '/solutions/marketing-agencies', element: <SolutionMarketingAgenciesPage /> },
  { path: '/solutions/training-companies', element: <SolutionTrainingCompaniesPage /> },
  { path: '/solutions/clinics', element: <SolutionClinicsPage /> },
  { path: '/solutions/real-estate', element: <SolutionRealEstatePage /> },
  { path: '/solutions/professional-services', element: <SolutionProfessionalServicesPage /> },
  { path: '/solutions/recruitment', element: <SolutionRecruitmentPage /> },
  { path: '/solutions/saas', element: <SolutionSaasPage /> },
  { path: '/solutions/logistics', element: <SolutionLogisticsPage /> },
]
