/**
 * Dealix Sector Diagnostic Catalog
 *
 * Canonical sector playbook metadata for L0-L4 diagnosis and proposal drafting.
 * This is a capability map, not a case-study or ROI claim. Any customer-facing
 * result must be backed by a customer baseline, consent, acceptance criteria,
 * and evidence review.
 */

export type SectorDiagnostic = {
  id: string;
  nameAr: string;
  nameEn: string;
  signals: string[];
  economicProblems: string[];
  priorityWorkflows: string[];
  dealixOffers: string[];
  deliverables: string[];
  kpis: string[];
  buyers: string[];
  guardrails: string[];
};

const COMMON_DELIVERABLES = [
  "baseline and evidence register",
  "as-is/to-be workflow map",
  "prioritised opportunity backlog",
  "human-review queue and approval rules",
  "weekly proof report",
  "implementation and rollback plan",
];

const COMMON_GUARDRAILS = [
  "no fabricated ROI, testimonials, or case studies",
  "diagnostic before quote, scope, duration, or payment",
  "human approval for external communication and material decisions",
  "least-privilege access, data minimisation, and retention rules",
];

export const SECTOR_DIAGNOSTIC_CATALOG: SectorDiagnostic[] = [
  { id: "government-b2g", nameAr: "الحكومة وB2G", nameEn: "Government / B2G", signals: ["مناقصات ووثائق كثيرة", "موافقات متعددة", "تقارير امتثال متكررة"], economicProblems: ["تأخر المشتريات", "ضياع المعرفة", "بطء القرار", "مخاطر الحوكمة"], priorityWorkflows: ["المناقصات والتأهيل", "تحويل المعرفة إلى إجراءات", "فرز الوثائق والمراسلات", "التقارير والامتثال"], dealixOffers: ["Command Center", "Knowledge-to-Action", "Document Intelligence", "AI Governance"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن دورة الموافقة", "زمن البحث عن الوثيقة", "نسبة اكتمال المتطلبات", "زمن إصدار التقرير"], buyers: ["الرئيس التنفيذي", "التحول الرقمي", "المشتريات", "الامتثال", "تقنية المعلومات"], guardrails: [...COMMON_GUARDRAILS, "مراجعة قانونية وأمنية قبل أي تكامل أو استخدام لبيانات حساسة"] },
  { id: "construction-epc", nameAr: "الإنشاءات وEPC", nameEn: "Construction / EPC", signals: ["مشاريع متعددة", "RFI وvariation orders", "مطالبات ودفعات مرحلية"], economicProblems: ["تأخر المشاريع", "تسرب قيمة المطالبات", "تأخر الفوترة والتحصيل", "فوضى الوثائق"], priorityWorkflows: ["RFI وsubmittals", "التغييرات والمطالبات", "تقدم الأعمال والدفعات", "تسليم المشروع"], dealixOffers: ["Project Command Center", "Document-to-Cash", "Claims Intelligence", "Contractor Coordination"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن RFI", "زمن اعتماد التغيير", "أيام الفوترة إلى التحصيل", "نسبة الوثائق المكتملة"], buyers: ["مدير المشاريع", "المدير التجاري", "المالية", "المشتريات", "مالك المشروع"], guardrails: COMMON_GUARDRAILS },
  { id: "industrial-manufacturing", nameAr: "الصناعة والتصنيع", nameEn: "Industrial / Manufacturing", signals: ["أوامر إنتاج", "استثناءات جودة", "صيانة وموردون"], economicProblems: ["توقف الإنتاج", "هدر الجودة", "تأخر التوريد", "قرارات صيانة متأخرة"], priorityWorkflows: ["استثناءات الإنتاج", "الجودة وCAPA", "الصيانة الوقائية", "المشتريات والموردون"], dealixOffers: ["Operations OS", "Quality Intelligence", "Procurement Control", "Maintenance Knowledge"], deliverables: COMMON_DELIVERABLES, kpis: ["وقت معالجة الاستثناء", "نسبة العيوب", "OEE أو مقياس التشغيل المتاح", "زمن دورة الشراء"], buyers: ["مدير العمليات", "الجودة", "الصيانة", "المشتريات", "المدير المالي"], guardrails: COMMON_GUARDRAILS },
  { id: "logistics-supply-chain", nameAr: "اللوجستيات وسلاسل الإمداد", nameEn: "Logistics / Supply Chain", signals: ["شحنات واستثناءات", "تحديثات يدوية", "إثبات تسليم"], economicProblems: ["تأخر التسليم", "تسرب تكلفة الشحن", "ضعف الرؤية", "تأخر معالجة الاستثناء"], priorityWorkflows: ["استثناءات الشحن", "المخزون وإعادة الطلب", "إثبات التسليم", "تحديثات العميل وSLA"], dealixOffers: ["Logistics Command Center", "Exception Management", "Customer Update OS", "Fleet/Shipment Intelligence"], deliverables: COMMON_DELIVERABLES, kpis: ["التسليم في الموعد", "زمن حل الاستثناء", "نسبة تحديثات SLA", "دقة المخزون"], buyers: ["العمليات", "سلسلة الإمداد", "خدمة العملاء", "المالية", "مدير الحساب"], guardrails: COMMON_GUARDRAILS },
  { id: "energy-utilities-og", nameAr: "الطاقة والمرافق والنفط والغاز", nameEn: "Energy / Utilities / O&G", signals: ["عمليات ميدانية", "مقاولون", "تصاريح وسجلات سلامة"], economicProblems: ["تأخر العمل الميداني", "ضعف ضبط المقاولين", "فقدان المعرفة", "مخاطر السلامة والامتثال"], priorityWorkflows: ["أوامر العمل الميدانية", "تقارير المقاولين", "السلامة والتصاريح", "المعرفة التشغيلية"], dealixOffers: ["Field Operations OS", "Contractor Control", "Safety Knowledge", "Executive Command"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن إغلاق أمر العمل", "نسبة اكتمال تقارير المقاول", "حوادث/near-miss المسجلة", "زمن الوصول لإجراء معتمد"], buyers: ["العمليات", "السلامة", "إدارة المشاريع", "المشتريات", "تقنية المعلومات"], guardrails: [...COMMON_GUARDRAILS, "لا قرار سلامة أو تشغيل حرج بدون صاحب صلاحية بشري"] },
  { id: "mining-metals", nameAr: "التعدين والمعادن", nameEn: "Mining / Metals", signals: ["معدات ثقيلة", "مواقع بعيدة", "صيانة وموردون"], economicProblems: ["توقف المعدات", "تأخر قطع الغيار", "فجوات تقارير الموقع", "مخاطر الموردين"], priorityWorkflows: ["صيانة المعدات", "المشتريات وقطع الغيار", "تقارير الموقع", "إدارة الموردين"], dealixOffers: ["Site Command Center", "Maintenance Intelligence", "Supplier Workflow", "Document Intelligence"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن التوقف", "زمن توفير القطعة", "اكتمال تقرير الموقع", "نسبة التزام المورد"], buyers: ["مدير الموقع", "الصيانة", "المشتريات", "السلامة", "المدير المالي"], guardrails: COMMON_GUARDRAILS },
  { id: "real-estate-proptech-fm", nameAr: "العقار وPropTech وإدارة المرافق", nameEn: "Real Estate / PropTech / FM", signals: ["عقارات ووحدات متعددة", "بلاغات مرافق", "وسطاء ومقاولون"], economicProblems: ["تسرب فرص التأجير", "بطء البلاغات", "ضعف تحصيل الإيجار", "تأخر المقاولين"], priorityWorkflows: ["التأجير والـleads", "بلاغات FM", "المقاولون", "الوثائق والتحصيل"], dealixOffers: ["Leasing Revenue OS", "FM Command Center", "Vendor Control", "Collections Workflow"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن الرد على lead", "زمن إغلاق البلاغ", "نسبة الإشغال", "أيام التأخر في التحصيل"], buyers: ["إدارة الأصول", "التأجير", "FM", "المالية", "مدير العقار"], guardrails: COMMON_GUARDRAILS },
  { id: "healthcare", nameAr: "الرعاية الصحية", nameEn: "Healthcare", signals: ["حجوزات وملفات", "انتظار ومواعيد", "متطلبات خصوصية عالية"], economicProblems: ["عدم الحضور", "تأخر الخدمة الإدارية", "تكدس الدعم", "مخاطر الخصوصية"], priorityWorkflows: ["الحجز والتذكير", "رحلة المريض الإدارية", "الفوترة والمطالبات", "المعرفة الداخلية"], dealixOffers: ["Patient Operations OS", "Admin Automation", "Knowledge Assistant", "Reputation Workflow"], deliverables: COMMON_DELIVERABLES, kpis: ["نسبة عدم الحضور", "زمن الرد", "زمن دورة المطالبة", "زمن معالجة الطلب الإداري"], buyers: ["الرئيس التنفيذي", "العمليات", "الإيرادات", "الجودة", "الخصوصية وتقنية المعلومات"], guardrails: [...COMMON_GUARDRAILS, "عدم تقديم قرار طبي أو معالجة بيانات صحية خارج التفويض والحوكمة"] },
  { id: "finance-fintech-insurance", nameAr: "المالية والتقنية المالية والتأمين", nameEn: "Finance / Fintech / Insurance", signals: ["طلبات ووثائق KYC", "موافقات", "مطالبات أو تحصيل"], economicProblems: ["تأخر onboarding", "تسرب التحصيل", "تراكم المطالبات", "مخاطر الاحتيال والامتثال"], priorityWorkflows: ["KYC والوثائق", "خدمة العملاء", "المطالبات", "التحصيل والتقارير"], dealixOffers: ["Document-to-Decision", "Collections OS", "Case Triage", "Governed AI Control"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن onboarding", "زمن معالجة المطالبة", "نسبة التحصيل", "نسبة الحالات المصعّدة"], buyers: ["العمليات", "المخاطر", "الامتثال", "المالية", "تقنية المعلومات"], guardrails: [...COMMON_GUARDRAILS, "مراجعة تنظيمية وأمنية؛ لا قرار ائتماني أو تأميني آلي نهائي"] },
  { id: "retail-ecommerce", nameAr: "التجزئة والتجارة الإلكترونية", nameEn: "Retail / eCommerce", signals: ["كتالوج وقنوات متعددة", "طلبات ومرتجعات", "دعم ومحادثات"], economicProblems: ["تسرب التحويل", "نفاد المخزون", "تكلفة الدعم", "المرتجعات والتسرب المالي"], priorityWorkflows: ["الكتالوج", "الطلب إلى التسليم", "الدعم", "المرتجعات والاسترداد"], dealixOffers: ["Commerce Revenue OS", "Catalog Intelligence", "Support Workflow", "Returns Control"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن الرد", "معدل التحويل", "زمن معالجة المرتجع", "نسبة الطلبات المتأخرة"], buyers: ["التجارة الإلكترونية", "التسويق", "العمليات", "خدمة العملاء", "المالية"], guardrails: COMMON_GUARDRAILS },
  { id: "tourism-hospitality-events", nameAr: "السياحة والضيافة والفعاليات", nameEn: "Tourism / Hospitality / Events", signals: ["حجوزات وموسمية", "ضيوف متعدد اللغات", "شركاء وفعاليات"], economicProblems: ["إلغاء وعدم حضور", "ضعف upsell", "تأخر الاستجابة", "فوضى التشغيل"], priorityWorkflows: ["الحجز والتأكيد", "تجربة الضيف", "المبيعات والشراكات", "تشغيل الفعالية"], dealixOffers: ["Guest Operations OS", "Booking Revenue OS", "Partner Workflow", "Multilingual Support"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن الرد", "نسبة التحويل للحجز", "الإيراد الإضافي", "تقييم الخدمة"], buyers: ["المدير العام", "التشغيل", "المبيعات", "تجربة العميل", "المالية"], guardrails: COMMON_GUARDRAILS },
  { id: "professional-services", nameAr: "الخدمات المهنية", nameEn: "Professional Services", signals: ["عروض ومشاريع", "معرفة موزعة", "فواتير وساعات"], economicProblems: ["تأخر العرض", "ضعف الاستفادة من الخبراء", "تسرب نطاق المشروع", "تأخر التحصيل"], priorityWorkflows: ["proposal-to-delivery", "تخصيص الخبراء", "إدارة المعرفة", "الفوترة والتحصيل"], dealixOffers: ["Proposal OS", "Delivery OS", "Knowledge-to-Action", "Utilization Command"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن إصدار العرض", "نسبة الفوز", "الاستفادة من الفريق", "أيام التحصيل"], buyers: ["الشريك/المؤسس", "العمليات", "المبيعات", "المالية", "مدير المشروع"], guardrails: COMMON_GUARDRAILS },
  { id: "technology-saas-sis", nameAr: "التقنية وSaaS ومتكاملو الأنظمة", nameEn: "Technology / SaaS / SIs", signals: ["pipeline وtrials", "تذاكر دعم", "تنفيذ وتوسعة"], economicProblems: ["تسرب pipeline", "churn", "تأخر التنفيذ", "تشتت معرفة المنتج"], priorityWorkflows: ["RevOps", "onboarding", "الدعم", "التوسعة والاحتفاظ", "حوكمة الوكلاء"], dealixOffers: ["Revenue OS", "Customer Success OS", "Support Intelligence", "Agent Governance"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن أول قيمة", "تحويل trial", "زمن حل التذكرة", "نسبة التجديد والتوسعة"], buyers: ["CEO", "المبيعات", "CS", "الدعم", "المنتج/التقنية"], guardrails: COMMON_GUARDRAILS },
  { id: "telecom-media-marketing", nameAr: "الاتصالات والإعلام والتسويق", nameEn: "Telecom / Media / Marketing", signals: ["حملات وقنوات", "عملاء وتذاكر", "محتوى وموافقات"], economicProblems: ["هدر الإنفاق", "بطء الحملة", "ضعف الاحتفاظ", "تأخر الموافقات"], priorityWorkflows: ["تخطيط الحملة", "المحتوى والموافقات", "خدمة العميل", "تحليل القنوات"], dealixOffers: ["Campaign Operations OS", "Content Intelligence", "Customer Workflow", "Marketing Command"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن إطلاق الحملة", "تكلفة الفرصة/lead", "زمن الموافقة", "نسبة الاحتفاظ"], buyers: ["التسويق", "الإيرادات", "العمليات", "العلامة", "تقنية المعلومات"], guardrails: [...COMMON_GUARDRAILS, "موافقة بشرية على النشر والرسائل التجارية"] },
  { id: "education-workforce", nameAr: "التعليم والقوى العاملة", nameEn: "Education / Workforce", signals: ["قبول وتسجيل", "محتوى تدريبي", "دعم متعلمين"], economicProblems: ["تسرب المتعلمين", "بطء القبول", "تكرار الدعم", "ضعف متابعة النتائج"], priorityWorkflows: ["القبول والتسجيل", "المحتوى والمعرفة", "الدعم", "التوظيف والتدريب"], dealixOffers: ["Admissions OS", "Learning Operations", "Knowledge Assistant", "Workforce Command"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن القبول", "نسبة الإكمال", "زمن الرد", "نسبة التوظيف/الاحتفاظ"], buyers: ["الإدارة", "القبول", "البرامج", "الموارد البشرية", "تقنية المعلومات"], guardrails: COMMON_GUARDRAILS },
  { id: "agriculture-food-water", nameAr: "الزراعة والغذاء والمياه", nameEn: "Agriculture / Food / Water", signals: ["موردون ومخزون", "جودة وسلامة", "تشغيل موسمي"], economicProblems: ["هدر المخزون", "تأخر التوريد", "مخاطر الجودة", "ضعف التنبؤ"], priorityWorkflows: ["التوريد والمخزون", "الجودة", "التوزيع", "التنبؤ الموسمي"], dealixOffers: ["Supply Chain OS", "Quality Workflow", "Procurement Control", "Forecasting Command"], deliverables: COMMON_DELIVERABLES, kpis: ["هدر المخزون", "زمن التوريد", "نسبة اجتياز الجودة", "دقة التنبؤ"], buyers: ["العمليات", "الجودة", "المشتريات", "التوزيع", "المالية"], guardrails: [...COMMON_GUARDRAILS, "لا تجاوز لمتطلبات سلامة الغذاء أو المياه"] },
  { id: "mobility-automotive-fleet", nameAr: "التنقل والسيارات والأساطيل", nameEn: "Mobility / Automotive / Fleet", signals: ["أسطول ومواعيد صيانة", "رحلات أو حجوزات", "خدمة ما بعد البيع"], economicProblems: ["توقف الأسطول", "تكلفة الصيانة", "ضعف الاستفادة", "تأخر خدمة العميل"], priorityWorkflows: ["إدارة الأسطول", "الصيانة", "الحجوزات والرحلات", "خدمة ما بعد البيع"], dealixOffers: ["Fleet Command Center", "Maintenance OS", "Booking Workflow", "Customer Service OS"], deliverables: COMMON_DELIVERABLES, kpis: ["جاهزية الأسطول", "زمن الإصلاح", "تكلفة الرحلة", "زمن حل طلب العميل"], buyers: ["مدير الأسطول", "التشغيل", "الصيانة", "خدمة العملاء", "المالية"], guardrails: COMMON_GUARDRAILS },
  { id: "export-import-rhq-market-entry", nameAr: "التصدير والاستيراد وRHQ ودخول السوق", nameEn: "Export / Import / RHQ / Market Entry", signals: ["أسواق وشركاء جدد", "وثائق وشحن", "متطلبات محلية"], economicProblems: ["احتكاك دخول السوق", "تأخر التأهيل", "مخاطر الموردين", "ضعف التوطين"], priorityWorkflows: ["بحث السوق", "تأهيل الشركاء", "جاهزية المورد", "التوطين والوثائق"], dealixOffers: ["Market Entry Intelligence", "Partner Discovery", "Supplier Readiness", "Localization OS"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن التأهيل", "عدد الفرص المؤهلة", "زمن الجاهزية", "نسبة اكتمال الوثائق"], buyers: ["التوسع", "التجارة الدولية", "المشتريات", "الشؤون القانونية", "الشريك المحلي"], guardrails: [...COMMON_GUARDRAILS, "تحقق بشري من العقوبات والملكية والالتزامات النظامية"] },
  { id: "creative-sports-gaming", nameAr: "الإبداع والرياضة والألعاب", nameEn: "Creative / Sports / Gaming", signals: ["محتوى وجمهور", "رعاة وشراكات", "حقوق وفعاليات"], economicProblems: ["تسرب فرص الرعاية", "بطء إنتاج المحتوى", "ضعف تفعيل الجمهور", "فوضى الحقوق"], priorityWorkflows: ["المحتوى", "الرعاية", "إدارة المجتمع", "الحقوق والتجارية"], dealixOffers: ["Content Operations", "Sponsorship Revenue OS", "Community Workflow", "Rights Intelligence"], deliverables: COMMON_DELIVERABLES, kpis: ["زمن العرض للرعاية", "نسبة تفعيل الرعاية", "زمن إنتاج المحتوى", "معدل تفاعل الجمهور"], buyers: ["الإدارة", "التجاري", "التسويق", "الإنتاج", "الشؤون القانونية"], guardrails: [...COMMON_GUARDRAILS, "موافقة حقوق ونشر بشرية قبل أي مخرج خارجي"] },
  { id: "associations-nonprofits", nameAr: "الجمعيات والمنظمات غير الربحية", nameEn: "Associations / Nonprofits", signals: ["أعضاء ومانحون", "منح وتقارير", "متطوعون"], economicProblems: ["ضعف الاحتفاظ بالأعضاء", "تأخر تقارير المنح", "تشتت المعرفة", "بطء جمع التبرعات"], priorityWorkflows: ["الأعضاء", "المنح والتقارير", "المانحون", "المتطوعون والمعرفة"], dealixOffers: ["Member Operations OS", "Grant Reporting", "Donor Workflow", "Knowledge Command"], deliverables: COMMON_DELIVERABLES, kpis: ["نسبة الاحتفاظ بالأعضاء", "زمن تقرير المنحة", "زمن متابعة المانح", "نسبة اكتمال السجلات"], buyers: ["مجلس الإدارة", "التشغيل", "المنح", "المالية", "علاقات المانحين"], guardrails: COMMON_GUARDRAILS },
];

export function getSectorDiagnostic(id: string) {
  return SECTOR_DIAGNOSTIC_CATALOG.find((sector) => sector.id === id);
}

export function listSectorIds() {
  return SECTOR_DIAGNOSTIC_CATALOG.map((sector) => sector.id);
}
